tesseract-ocr/tesseract

README, README.md
See https://code.google.com/p/tesseract-ocr/issues/detail?id=563 for background on leptonica. The README was basically a markdown already, let's recognise it as such.
=> [infra] updating readme

training/tesstrain_utils.sh
There are three paths on OS X: 
/Library/Fonts/
/System/Library/Fonts/
and
/Users/`whoami`/Library/Fonts
Setting the font path is probably unavoidable on Mac, but at least we can use a default path that exists.
=> /usr/share/fonts is the wrong path on Mac

ChangeLog
following changes are to have same consistent bullet formatting, date formats and newest on top order of revisions.
=> ChangeLog reformatting for consistent ordering

autogen.sh
Use `[ "$foo" = "bar" ]` instead of `[ "$foo" == "bar" ]`.
The latter is a bashism.
=> autogen.sh: fix a bashism

api/capi.cpp
Make TessDeleteResultRenderer use delete, not delete[]. Handles should be deleted with delete and all other handles are deleted with delete.
=> Fix incorrect use of delete[] in TessDeleteResultRenderer 

training/pango_font_info.cpp
See: https://groups.google.com/d/msgid/tesseract-ocr/55B12C3C.3010908%40vol.at
```
pango_font_info.cpp:223:46: error: 'strcasestr' was not declared in this scope
is_fraktur_ = (strcasestr(family, "Fraktur") != NULL);
```
=> strcasestr needed on Cygwin too

configure.ac, training/Makefile.am
For the next part of #61 - again, I have no way of testing this.
=> libicui18n is only called libicuin on mingw, not cygwin

ccutil/platform.h
In VC14 _snprintf_ function is provided in standard library therefore triggering error: _"Do not define snprintf as a macro. Macro definition of snprintf conflicts with Standard Library function declaration"_.
Added preprocessor directive to skip defining snprintf if compiling with VC14.
Signed-off-by: Jaka Konda <jaka.konda@outlook.com>
=> Fix VC14 (VS2015) compile issue with snprintf

.gitignore, api/Makefile.am, ccmain/Makefile.am, ccstruct/Makefile.am, configure.ac, opencl/Makefile.am, opencl/openclwrapper.cpp, textord/Makefile.am, training/Makefile.am
I had to redo how flags were handled for OpenCL, and in the process I quite likely broke something on the *nix side. I think the template I've set up is more in line with autotools best practices (https://stackoverflow.com/questions/20230827/how-to-set-include-paths-with-autotools) and should be flexible enough to fix.
Unfortunately, with these changes OS X/OpenCL compiles, but the output of the binary is garbage, as opposed to crashing. :(
=> Get --enable-opencl to compile (but not work)

ccutil/helpers.h
This patch fixes the problem reported here on the mailing list:
https://groups.google.com/forum/#!topic/tesseract-ocr/HbjEPm4CiiQ
=> Add ULL to constants which overflow 32 bits

.gitignore, java/Makefile.am, java/Manifest.txt, viewer/svutil.cpp
This patch makes it easier to build and run ScrollView.
- add a Makefile target, fetch-jars, to fetch dependencies so they don't have to be copied by hand
- add a Manifest to the jar so dependencies don't need to be specified on the command line
- ignore .class and .jar files for Git
=> Simplify build and run of ScrollView

training/language-specific.sh, training/tesstrain.sh, training/tesstrain_utils.sh
Improvements to the tesstrain.sh script.
The only difference from default usage is that the --bin_dir option has been removed, in favour of $PATH.
See the commit log for details.
=> Improve tesstrain.sh script

README.md
for consistency with instructions that show up while installing
=> adds sudo to "make install" command

configure.ac, training/unicharset_extractor.cpp
I found some issues with building unicharset_extractor under Fedora as it wouldn't detect wchar correctly.
=> Unicharset extractor problems with wchar

api/tesseractmain.cpp
test:
```
tesseract eurotext.tif eurotext -l osd -psm 0
```
=> OSD: Print script name instead of meaningless script id

ccutil/genericvector.h, ccutil/helpers.h
While building tesseract with clang for 64 bit architecture there are following warnings:
helpers.h:33:32: Implicit conversion loses integer precision: 'unsigned long' to 'int'
genericvector.h:338:27: Implicit conversion loses integer precision: 'unsigned long' to 'int'
This patch does explicit type casting and eliminates those warnings on 64bit platforms.
=> Type mismatch on 64bit platforms

ccutil/scanutils.cpp, cmake/Configure.cmake, configure.ac, viewer/svutil.cpp
Fix compilation on linux with musl libc library (http://musl-libc.org).
=> Compile with musl libc

ccstruct/pageres.h, ccstruct/ratngs.cpp, ccstruct/ratngs.h, ccutil/genericvector.h
gcc reports these warnings with -Wextra:
ccstruct/pageres.h:330:3: warning:
base class 'class ELIST_LINK' should be explicitly initialized
in the copy constructor [-Wextra]
ccstruct/ratngs.cpp:115:1: warning:
base class 'class ELIST_LINK' should be explicitly initialized
in the copy constructor [-Wextra]
ccstruct/ratngs.h:291:3: warning:
base class 'class ELIST_LINK' should be explicitly initialized
in the copy constructor [-Wextra]
ccutil/genericvector.h:435:3: warning:
base class 'class GenericVector<WERD_RES*>' should be explicitly initialized
in the copy constructor [-Wextra]
=> Fix compiler warnings for copy constructors

.travis.yml
This command fails currently:
wget http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.sh
Obviously cmake.org now redirects to https connections, so we have to
fix the URL.
=> Fix Travis build error (error when getting cmake)

ccstruct/polyaprx.cpp, ccstruct/quspline.cpp, classify/intmatcher.cpp, classify/intproto.cpp, cutil/bitvec.h, textord/oldbasel.cpp, wordrec/gradechop.cpp
This fixes clang compiler warnings like this one:
wordrec/gradechop.cpp:52:3: warning:
'register' storage class specifier is deprecated [-Wdeprecated-register]
=> Remove register attribute for local variables

ccstruct/split.cpp, ccutil/clst.cpp, ccutil/clst.h, ccutil/elst.cpp, ccutil/elst.h, ccutil/elst2.cpp, ccutil/elst2.h, textord/tabvector.cpp
This fixes warnings from clang.
=> Remove checks for this == NULL

ccmain/osdetect.h
This fixes a warning from clang.
=> ccmain: Remove unused private class member

api/tesseractmain.cpp
Coverity bug report: CID 1270421 "Buffer not null terminated".
=> tesseractmain: Fix unterminated string

ccmain/recogtraining.cpp
Coverity bug report: CID 1270401 (#1 of 1): Use after free
As the comment (which was also fixed) says, ReadNextBox() already
calls fclose(box_file), so don't call it a 2nd time.
=> Fix duplicate fclose

api/pdfrenderer.cpp
Coverity bug reports:
CID 1270405: Uninitialized scalar variable
CID 1270408: Uninitialized scalar variable
CID 1270409: Uninitialized scalar variable
CID 1270410: Uninitialized scalar variable
Those variables are set conditionally in the while loop
and must keep their values in following iterations, so
they must be declared outside of the loop.
=> pdfrenderer: Fix uninitialized local variables

training/tesstrain.sh, training/tesstrain_utils.sh
The way tesstrain.sh handled font names was really weird, using '+'
signs as a delimiter. However quoting arguments is a much more
straightforward, standard and sensible way to do things.
So whereas previously one would have used this:
--fontlist Times New Roman + Arial Black
Now they should be specified like this:
--fontlist "Times New Roman" "Arial Black"
=> Use shell quoting rather than pluses to separate font arguments in tesstrain.sh

api/tesseractmain.cpp
Commit 99110df75781c6907c84a3d23695a6900b933a97 improved the help text
in several aspects, but also introduced new inconsistencies which this
patch tries to fix.
* Align columns (this needed replacing tabs by spaces).
* Start explaining text with uppercase.
* Replace "the stdout" by "stdout.
* Small changes in help text for page segmentation modes.
* Split options in OCR options and single options
(partially revert commit 99110df75781c6907c84a3d23695a6900b933a97).
In addition, whitespace characters at end of lines were removed.
=> tesseractmain: Prettify help message

api/tesseractmain.cpp, ccmain/tesseractclass.cpp, ccmain/tesseractclass.h, tessdata/configs/hocr, tessdata/configs/makebox, tessdata/configs/pdf, tessdata/configs/txt, tessdata/configs/unlv
Revert fd429c32, 43834da7, 05de195e.
See #49, #59.
The code in this commit solves the issue in a more elegant way, IMHO.
Now you can use:
* `tesseract eurotext.tif eurotext txt pdf`
* `tesseract eurotext.tif eurotext txt hocr`
* `tesseract eurotext.tif eurotext txt hocr pdf`
NOTE:
With `tesseract eurotext.tif eurotext`
or `tesseract eurotext.tif eurotext txt`
the psm will be set to '3', but...
With `tesseract eurotext.tif eurotext txt pdf`
or `tesseract eurotext.tif eurotext txt hocr`
the psm will be set to '1'.
=> If there is no explicit renderer(s), default to TessTextRenderer

ccutil/host.h
NULL is already defined in stddef.h,
so a local definition is not be needed.
=> Remove unneeded definition for NULL

training/language-specific.sh
See also tesseract-ocr/langdata#23.
Re-do of #188 to re-run and (hopefully) fix tests.
=> Use different font list and exposures for "lat" language training in language-specific.sh

opencl/openclwrapper.cpp
CALLOC and FREE were renamed to LEPT_*
The alternative to using the TESSERACT_LIBLEPT_PREREQ macro introduced in this pull request, to define CALLOC and FREE to their new names, would be to depend on Leptonica >=1.73 and use the LEPT_* variants in Tesseract's code directly.
I opted for this pull request's approach for better backward compatibility.
See-Also: https://bugs.gentoo.org/show_bug.cgi?id=573382
=> Compatibility with Leptonica 1.73

tessdata/configs/hocr
Tiny change to add the hocr_font_info config parameter to the hocr config file as a way of documenting its existence to interested parties. It is turned off, matching the default in the code.
=> Document hocr_font_info in config

api/baseapi.cpp
This fixes the duplicate line IDs caused by inserting height information
into the middle of the ID and it moves the line height info into
the title attribute like everything else, rather than using non-standard
HTML attributes (which won't validate).
This change may break consumers of the HTML output, but 3.04 has only
been in the wild for 6 months and the current HTML is invalid, so I 
believe the benefit outweighs the cost for the fix.
=> INCOMPATIBLE fix to hOCR line height information - fixes #225.

api/baseapi.cpp
This incorporates #223 & #224 to generate less verbose hOCR output with fewer `dir` and `lang` tags.
It also incorporates a fix for the Microsoft build breakage introduced by the last PR.
=> hOCR improvements

ccmain/docqual.cpp
In one of our test-cases valgrind complained about a jump-condition based on an un-initialized value:
==9451== Conditional jump or move depends on uninitialised value(s)
==9451==    at 0x35CEEC31F7: tesseract::Tesseract::quality_based_rejection(PAGE_RES_IT&, unsigned char) (in /usr/lib64/libtesseract.so.3.0.3)
==9451==    by 0x35CEEB6370: tesseract::Tesseract::rejection_passes(PAGE_RES*, ETEXT_DESC*, TBOX const*, char const*) (in /usr/lib64/libtesseract.so.3.0.3)
==9451==    by 0x35CEEBB0D0: tesseract::Tesseract::recog_all_words(PAGE_RES*, ETEXT_DESC*, TBOX const*, char const*, int) (in /usr/lib64/libtesseract.so.3.0.3)
==9451==    by 0x35CEEA905A: tesseract::TessBaseAPI::Recognize(ETEXT_DESC*) (in /usr/lib64/libtesseract.so.3.0.3)
==9451==    by 0x35CEEA9B2B: …
=> Initialize output parameters of word_char_quality() to zero before early exit

api/baseapi.cpp, api/baseapi.h, api/renderer.cpp, api/renderer.h, api/tesseractmain.cpp, ccmain/tesseractclass.cpp, ccmain/tesseractclass.h, tessdata/configs/Makefile.am, tessdata/configs/hocrtsv, tessdata/configs/tsv
This is a cleaned up version of #18 which adds a tabular output format and which came from https://code.google.com/archive/p/email-hocr-tsv/.
The differences from #18 include:
- rebased to avoid merge commits both in the original repo and on the branch
- removed all references to hOCR since that's an internal implementation detail that has nothing to do with the functionality (it was created by cloning & hacking on the hOCR renderer)
- removed a bunch of dead code and made some other minor simplifications
Note that it does not include some of the information that was added to the hOCR output after it was created two years ago, such as writing direction, font attributes, etc. It's not clear to me how useful/necessary those are.
=> Add TSV result renderer

viewer/svutil.h
As with 0c492cb, in VC14 snprintf function is provided in standard library there triggering error. "snprintf Do not define snprintf as a macro. Macro definition of snprintf conflicts with Standard Library function declaration"
=> Fix other instance of VS2015 compiler problem

api/tesseractmain.cpp
Most command line programs print the version to stdout.
This seams to be reasonable for Tesseract, too.
Now a shell statement like "VERSION=$(tesseract --version)" works
without I/O redirection.
=> Print version to stdout instead to stderr

ccstruct/pageres.cpp
The format string expects 3 int arguments.
=> Add missing argument for tprintf

training/pango_font_info.cpp
- In training/ango_font_info.cpp
=> Add missing % char from format specifier in tlog()

ccmain/pagesegmain.cpp
Format string and arguments did not match.
=> Fix order of arguments for tprintf

textord/colpartition.cpp
The format string expects two int arguments.
=> Fix arguments for tprintf

configure.ac
Calling pkg-config directly is a bad idea because it returns
the compiler flags for native builds.
=> configure: Fix cross compiler flags for cairo and pango

ccstruct/matrix.h
I've ran into this issue with `reinterpret_cast` while trying to compile Tesseract 3.04.01 on FreeBSD. The proposed change fixes this by no longer using `NULL`.
_Background:_
Since C++11, the null pointer constant `NULL` may be defined as either `0` or `nullptr` (see http://en.cppreference.com/w/cpp/types/NULL). It seems on most systems (like Mac OS X and Linux) it is still defined as `0` when using `-std=c++11`. However, this is not the case on my FreeBSD system (10.2-RELEASE), where it being defined as `nullptr` causes the `reinterpret_cast` to be rejected:
```
./matrix.h:292:63: error: reinterpret_cast from 'nullptr_t' to 'BLOB_CHOICE_LIST *' is not allowed
: BandTriMatrix<BLOB_CHOICE_LIST *>(dimension, bandwidth, NOT_CLASSIFIED) {}
^~~~~~~~~~~~~~
./matrix.h:33:24: note: expanded from …
```
=> Fix incompatibility with some C++11 implementations

ccutil/scanutils.cpp
As pointed out by Stefan Weil, conditionally defining off_t using a
macro isn't a valid approach. off_t does not have a fixed size and is
used in ABI definitions (e.g. syscalls), so silently guessing its size
risks breaking the build. Additionally, all sane and modern platforms
will have off_t.
=> Remove conditional definition of off_t

configure.ac
The different checks had set ENABLE_TRAINING unconditionally,
thus overwriting the value from the preceding checks.
So if _pango_ and _cairo_ were available, but _icu_ was missing,
users would still be offered to build the training tools.
The changes for _icu_ and _has_cpp11_ are not strictly necessary,
but are made here to have uniform code patterns.
=> configure: Fix check for dependencies needed for training

ccutil/strngs.cpp
Location: file `ccutil/strngs.cpp`, method `STRING::add_str_double`
Because of a wrong value for `kMaxDoubleSize`, some small values are truncated by one byte.
Example: `-4.0382147e-006` has 16 bytes including the terminating null byte. But `kMaxDoubleSize` has value 15 and the number is truncated to `-4.0382147e-00`. As result, the number becomes way too large by a factor of 10<sup>6</sup>! (I had found such wrong values in `.tr` files inside the parameters for feature `mf`.)
Also the description for `kMaxDoubleSize` is wrong. The largest length for a formatted number with `%.8g` is `-1.2345678e-999<nul>`. The precision of format specifier `g` specifies the maximum number of significant digits. The length including the terminating null byte is 16 (eight digits, two signs, decimal marker, …
=> Fix of add_str_double

configure.ac
This is not strictly necessary, but recommended in the GNU autoconf manual.
No [] was added to arguments like true or false.
=> configure: Enclose most macro arguments in []

textord/imagefind.cpp
=> Bypass Leptonica error message with pixGenHalftoneMask()

training/text2image.cpp
Asserts should not be used for missing or invalid input in the command
line! This leads to a bad UX.
=> Replace asserts with tprintf() and exit(1)

training/text2image.cpp
Asserts should not be used for missing or invalid input in the command
line! This leads to a bad UX.
=> Replace use of TLOG_FATAL() with tprintf() and exit(1)

training/stringrenderer.cpp, training/stringrenderer.h
This enables all OpenType ligatures for a specific font, where
available. Specifically, it explicitly enables the OpenType
features liga (standard ligatures), hlig (historical ligatures),
clig (contextual ligatures), and dlig (discretionary ligatures).
This feature requires Pango 1.38 or newer.
=> Enable all ligatures available in a font for text2image rendering

Makefile.am
This fixes wrong behaviour of "make training" when dependencies for
training were incomplete.
=> Makefile: Fix phony training target

training/pango_font_info.cpp
Commit 65504c8cd2300b0dd7c9352e66d0a69a5918f340 misplaced the #endif.
The definition of _GNU_SOURCE is only needed for Cygwin.
Defining _GNU_SOURCE on Linux results in compiler warnings because this
macro is already defined by the compiler.
Fix this by moving the #endif to the right place. In addition the code
for Cygwin is made more robust: If a future Cygwin compiler defines
_GNU_SOURCE, too, the code will still work.
=> Fix Cygwin compatibility – part III

training/text2image.cpp
On msys2 pango seems to always returns empty string for the suggested
font. It's a good idea to check that the string is not empty before
printing it - on all platforms.
=> Check that pango's suggested font name is not an empty string

api/baseapi.cpp, api/renderer.cpp
In Tesseract's coordinate system, width is just right - left, [cf. slide 2]
(github.com/tesseract-ocr/docs/blob/master/das_tutorial2016/2ArchitectureAndDataStructures.pdf).
You can verify the bug by running `tesseract A.png - -c tessedit_create_tsv=1 -psm 10` with this image ![test image](https://cloud.githubusercontent.com/assets/19879328/16364527/8fe92dba-3be9-11e6-81fb-893596c14e90.png). It yields a word bbox of 18x21 for this 17x20 pixel image:
level|page_num|block_num|par_num|line_num|word_num|left|top|width|height|conf|text
-----|--------|---------|-------|--------|--------|----|---|-----|------|----|----
1|1|0|0|0|0|0|0|17|20|-1|
2|1|1|0|0|0|0|0|18|21|-1|
3|1|1|1|0|0|0|0|18|21|-1|
4|1|1|1|1|0|0|0|18|21|-1|
5|1|1|1|1|1|0|0|18|21|95|A
=> Fix TSV bounding box width/hight calculation

api/baseapi.cpp
This occurrence should have been included in commit 29d971e
but was overlooked by error. I apologize for my lapse.
=> Fix TSV bounding box width/hight calculation (addition to #358)

api/tesseractmain.cpp
Showing them in a window (default) is not acceptable for a console
application like Tesseract which must be able to work in batch mode.
=> win32: Show TIFF warnings on console

training/stringrenderer.h
gcc reported this warning:
../training/stringrenderer.cpp:
In member function ‘void tesseract::StringRenderer::SetLayoutProperties()’:
../training/stringrenderer.cpp:211:42: warning:
ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
set_features("liga, clig, dlig, hlig");
^
=> stringrenderer: Fix compiler warning (-Wwrite-strings)

training/text2image.cpp
This changes the error message for a missing font from
Could not find font named Times New Roman.Please correct --font arg.
(missing space after first sentence) to
Could not find font named Times New Roman.
Please correct --font arg.
=> text2image: Add linefeed to error message

ccutil/errcode.h
The implementation for MS C did not pass the variable arguments to
tprintf.
The standard is supported since C99 / C++11, so one implementation
is sufficient.
=> ccutil: Fix and simplify implementation of variadic macro

opencl/oclkernels.h
https://code.google.com/p/tesseract-ocr/issues/detail?id=1351
(http://web.archive.org/web/20150413012200/https://code.google.com/p/tesseract-ocr/issues/detail?id=1351)
=> Issue 1351: OpenCL build - kernel_ThresholdRectToPix() not accounting for padding bits in the output pix?!

dict/dawg_cache.cpp
Migrating from https://code.google.com/p/tesseract-ocr/issues/detail?id=1316
=> Issue 1316: The traineddata file must be closed after it was opened

training/tlog.h
The implementation was also wrong because it did not use __VA_ARGS__.
=> tlog: Remove unused macro TLOG_FATAL

training/fileio.cpp, training/fileio.h, training/text2image.cpp
Assertions are good for programming errors, but not for wrong user input.
The new code no longer needs File::ReadFileToStringOrDie, so remove that
method.
=> fileio: Replace assert with tprintf() and exit(1)

configure.ac
There is no good reason to suppress useful compiler warnings.
=> configure: Don't use -Wno-uninitialized for debug builds

vs2010/port/strcasestr.cpp
A haystack which is shorter than the needle resulted in negative value
for length_haystack which was forced to a very large unsigned value.
The resulting buffer overflow while reading the haystack would crash
text2image when it was called with a short font name.
=> vs2010: Fix implementation of strcasestr

api/baseapi.cpp, api/baseapi.h
It conflicts with a previous 'class' declaration for ETEXT_DESC:
include/tesseract/baseapi.h:594:21:
Struct 'ETEXT_DESC' was previously declared as a class
=> Remove unneeded 'struct' from TessBaseAPI::GetHOCRText (issue #414)

api/baseapi.cpp, ccmain/control.cpp, ccmain/osdetect.cpp, ccmain/pagesegmain.cpp, classify/intfeaturemap.cpp, textord/colfind.cpp, textord/strokewidth.cpp, textord/tabfind.cpp, textord/tablefind.cpp, textord/tordmain.cpp
This fixes several warnings from the clang compiler.
=> Remove some unused constants

training/pango_font_info.h, training/stringrenderer.h
This fixes several gcc warnings:
warning:
type qualifiers ignored on function return type [-Wignored-qualifiers]
=> training: Remove unnecessary const qualifiers

api/tesseractmain.cpp, ccutil/params.cpp
These two commits fix 15 memory blocks leaked by running `tesseract --tessdata-dir /usr/share/tessdata` (see PR #441).
=> Fix some memory leaks

api/baseapi.cpp, dict/dict.cpp
Avoid dynamic memory allocation for the static variable 'cache'.
Now the destructor for that variable is called automatically
when Tesseract terminates and releases all associated memory.
=> Fix memory leaks at program termination

opencl/openclwrapper.cpp
valgrind report: Mismatched free() / delete / delete []
gpuInfo->mpArryDevsID is created by "new cl_device_id[1]",
so it must be destroyed by delete[].
=> opencl: Fix mismatched new[] / free

configure.ac
openclwrapper calls function TIFFReadRGBAImageOriented which is provided
by libtiff, so add that library to OPENCL_LIBS.
This fixes a linker error (unresolved symbol) when opencl is enabled.
=> opencl: Add tiff library needed by openclwrapper

opencl/openclwrapper.cpp, opencl/openclwrapper.h
It is only used locally in opencl/openclwrapper.cpp.
For all other files which include openclwrapper.h, the compiler
complained about an unused static variable:
opencl/openclwrapper.h:175:16: warning:
‘MORPH_BC’ defined but not used [-Wunused-variable]
=> opencl: Move declaration of MORPH_BC from .h to .cpp file

opencl/opencl_device_selection.h
=> opencl: Remove unused function getNumDeviceWithEmptyScore

classify/adaptmatch.cpp
Commit b1f03cb6975ee4bde6d8c9450ea55f111cc36ac1 added a call of function
FreeFeatureSet to fix a memory leak, but introduced a new bug because the
local variable FloatFeatures was not always assigned a value.
Now FloatFeatures is always assigned a value, and we only need a single
place where FreeFeatureSet is called.
=> Fix crash caused by undefined value of local variable

.gitignore, Makefile.am
This is a missing commit from Tesseract 3.04.
=> add option "make training-uninstall"

doc/tesseract.1.asc
`C++` needs to escaped as `C\+\+` in the AsciiDoc source code.
=> Fix a typo in tesseract(1) man page

INSTALL.GIT.md, lstm/lstmrecognizer.h, lstm/recodebeam.h, lstm/series.cpp, lstm/series.h, lstm/static_shape.h, lstm/stridemap.cpp, lstm/stridemap.h, lstm/weightmatrix.cpp, lstm/weightmatrix.h, opencl/openclwrapper.cpp
=> Fix some typos (found by codespell)

lstm/lstmrecognizer.cpp
gcc report:
lstm/lstmrecognizer.cpp:608:47: error: 'isnan' was not declared in this scope
ASSERT_HOST(!isnan(output.f(t)[null_char_]));
=> lstm: Fix compilation (undeclared 'isnan')

ccutil/ambigs.h
The compare method is called very often, so even small improvements
are important.
The new code avoids one comparison in each loop iteration.
This results in smaller code (60 bytes for x86_64, gcc).
=> ccutil/ambigs: Optimize tesseract::UnicharIdArrayUtils::compare

ccstruct/blamer.cpp
gcc report:
ccstruct/blamer.cpp:343:65: warning:
'truth_x' may be used uninitialized in this function [-Wmaybe-uninitialized]
=> Fix compiler warning (-Wmaybe-uninitialized)

CMakeLists.txt
Cmake builds need the additional directories `arch` and `lstm`
to find all include files and also for linking.
=> Fix broken cmake builds

arch/dotproductavx.cpp
=> Fix 32 bit builds (missing _mm256_extract_epi64)

ccutil/host.h
POSIX provides portable data types for signed and unsigned integer values
of different size.
This patch maps those POSIX data types to the Tesseract specific types.
In a next step, the Tesseract data types can be eliminated by replacing
them with the POSIX data types.
~~Use also standard definitions for the printf format specifiers.
MS Visual Studio does not support that standard (at least not in older
versions), so local definitions are needed there.~~
~~NULL is standard, so a local definition should not be needed.~~
Signed-off-by: Stefan Weil sw@weilnetz.de
=> Introduce POSIX data types

ccmain/cube_reco_context.cpp, cube/beam_search.cpp, cube/bmp_8.cpp, cube/classifier_base.h, cube/cube_object.cpp
It is not necessary to check for null pointers.
Remove also unneeded delete operations and add missing delete operations
in cube/bmp_8.cpp.
Simplify also a conditional statement in cube/cube_object.cpp.
=> cube: Simplify delete operations

ccmain/cube_control.cpp, cube/char_samp.cpp
The latest Coverity Scan reports 10 fixed defects and 2 new defects. Fix the new defects.
=> Fix two new coverity warnings

api/baseapi.h, ccstruct/params_training_featdef.h, ccutil/bits16.h, ccutil/strngs.h, cube/beam_search.h, dict/dawg.h, textord/blkocc.h
clang++ report:
api/baseapi.h:852:4: warning:
extra ';' after member function definition [-Wextra-semi]
[...]
=> Remove extra semicolons after member function definitions

training/Makefile.am
Mingw-w64 no longer needs special linker options,
builds with those options fail.
=> training: Update Makefile for current Mingw-w64

api/Makefile.am, ccmain/Makefile.am, ccmain/par_control.cpp, configure.ac, lstm/Makefile.am, lstm/lstm.cpp, lstm/parallel.cpp
Builds without support for OpenMP failed with the old code. Fix this:
* Add OPENMP_CXXFLAGS for ccmain.
* Replace unconditional -fopenmp by OPENMP_CXXFLAGS for lstm.
* Always use _OPENMP for conditional compilation.
* Remove OPENMP as there is already _OPENMP.
* Include omp.h conditionally.
=> openmp: Fix build with clang++ and compilers without OpenMP support

api/tesseractmain.cpp
Disable debugging and informational messages from Leptonica
for release builds.
=> tesseract: Disable Leptonica messages

dict/dawg.h
Contrary to the comment, the destructor of the base class `GenericVector` calls `GenericVector::clear()`, which actually deletes `data_`, rendering `~DawgPositionVector()` redundant.
=> Remove redundant destructor

api/baseapi.cpp, api/baseapi.h, api/capi.cpp, api/capi.h
I suggest for 4.00 removing the old API entirely because it's not really usable without a lot of fiddling, and at a major version jump there are probably other API changes anyway, not that I'd know.
For 3.x I suggest cherrypicking the first commit to add the new change and leaving DetectOS() intact but making it return FALSE instead of risk corrupting memory in the caller if there is disagreement about the OSResults results structure. Personally I think it's better to gently break the caller in this case without breaking their compilation, but opinions may differ so I am leaving 3.x untouched.
=> Add new C API for detecting orientation and script, remove old one (4.00)

java/Makefile.am
* Fix builds in subdirectories:
* Add srcdir to Manifest.txt.
* Remove srcdir from piccolo2d-core-3.0.jar and piccolo2d-extras-3.0.jar.
* Add dependency of SCROLLVIEW_CLASSES on SCROLLVIEW_LIBS.
The SCROLLVIEW_LIBS are now automatically fetched when needed.
* Add .PHONY target for fetch-jars.
* Improve rule for clean target.
=> java: Improve build rules

api/Makefile.am
Replace OPENMP_CFLAGS by OPENMP_CXXFLAGS.
This completes commit 6140be6a5575e9159e3678adf4ee9e673b3ff2cc.
=> openmp: Fix OpenMP support

Makefile.am, testing/reorgdata.sh, testing/runalltests.sh, training/tesstrain.sh, training/tesstrain_utils.sh
Examples:
In training/tesstrain.sh line 64:
if (( ${LINEDATA} )); then
^-- SC2004: $/${} is unnecessary on arithmetic variables.
In training/tesstrain.sh line 56:
source `dirname $0`/language-specific.sh
^-- SC2006: Use $(..) instead of legacy `..`.
=> Fix some issues reported by shellcheck (SC2004, SC2006)

configure.ac
All relevant versions of Leptonica support pkg-config, so the old
configuration code can be removed.
Update also the error message for missing Leptonica.
=> Simplify configuration for Leptonica

ccstruct/imagedata.cpp
The internal range is 0...(n-1), but for users a page range 1...n is
more natural. Showing a range 0...n is wrong because it would imply
n+1 pages.
Change printed text from
Loaded 72/72 pages (0-72) of document ...
to
Loaded 72/72 pages (1-72) of document ...
=> Fix page range in log message

opencl/opencl_device_selection.h
The native CPU is always available and needs an initialized profile.
Signed-off-by: Stefan Weil <stefan.weil@bib.uni-mannheim.de>
=> opencl: Fix runtime crash when no device was found

api/Makefile.am
This fixes a build regression caused by commit
d70f3c36635c251ac3286063c6c29d10b815a565.
=> Add missing Leptonica linker flags (needed for macOS)

api/tesseractmain.cpp
The old code only allowed one platform.
Add also strict error handling.
=> opencl: Show up to four OpenCL platforms

lstm/weightmatrix.cpp
cpuid.h is only available for x86 builds. There are lots of non x86
architectures, so simply checking for PowerPC is not enough.
=> Fix build for non x86

api/Makefile.am, arch/Makefile.am, arch/simddetect.cpp, arch/simddetect.h, lstm/weightmatrix.cpp
Modify also the code to use a singleton. This simplifies the code as
no locking is needed. It also slightly improves the performance because
no check whether the architecture was tested is needed.
=> lstm: Move class SIMDDetect to new source file and improve code

api/tesseractmain.cpp, arch/simddetect.cpp
This information is not needed for normal runs, so it is sufficient
to show it on request (like versions and OpenCL information).
This also fixes a crash caused by undefined order of global constructors:
When the global variable SIMDDetect::detector is initialized before the
global variable debug_file, the first tprintf call in simddetect.cpp
crashes because of a NULL pointer in debug_file. This was only seen when
running with a shared library (libtesseract.so).
=> Move AVX / SSE messages to function PrintVersionInfo (crash fix)

ccmain/tesseractclass.cpp, ccmain/tesseractclass.h
I changed the parameter description because the older text was ambiguous.
=> Improve textonly_pdf parameter description

arch/simddetect.cpp
Change SIMD detection to instead check for compilers with __get_cpuid.
Verified that this compiles and runs on macOS El Capitan with homebrew gcc.
Also added an #error if SIMD checking is missing. Compilers that have no
SIMD should make that explicit.
[sw: Merged original commits and slightly polished the commit message]
[sw: Removed test for __MINGW32__ which is no longer needed]
=> Implement SIMD detection on macOS-gcc; complain if no SIMD detection

configure.ac
The current implementation for AVX uses 64 bit code,
so run the AVX test only when the compiler is a 64 bit compiler.
This fixes the broken implementation for 32 bit hosts
which provide AVX but call the stub of DotProductAVX.
Simplify also the conditional code for AVX_OPT and SSE41_OPT.
=> configure: Run AVX test only with 64 bit compiler

arch/dotproductavx.cpp, configure.ac
_mm256_extract_epi64 is not available for 32 bit platforms,
but it can be replaced by "a very simple workaround".
=> Support AVX for 32 bit platforms

api/baseapi.cpp
The indentation is wrong since commit
fd0683f9e03934bbdf7fbebb4d21d64c37b68bc0 and results in a gcc warning:
api/baseapi.cpp: In member function 'bool tesseract::TessBaseAPI::ProcessPagesMultipageTiff(const l_uint8*, size_t, const char*, const char*, int, tesseract::TessResultRenderer*, int)':
api/baseapi.cpp:986:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
if (tessedit_page_number >= 0)
^~
api/baseapi.cpp:988:7: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
pix = (data) ? pixReadMemFromMultipageTiff(data, size, &offset)
^~~
=> Fix indentation after conditional [-Wmisleading-indentation]

autogen.sh
Increase portability by insulating `autogen.sh` from platform variance.  
<hr />
Specifically, test for the existence of either `libtoolize` or `glibtoolize` and caching its location into a script variable prior to running the utility in order to prevent either utility's invocation from spawning error messages of the form './autogen.sh: line $LINE: $COMMAND: command not found' (with the $LINE and $COMMAND pseudo-variables replaced with content relevant to what line the command that spawned this error message was on within `autogen.sh` and what command's invocation was attempted at that point, of course.)  In particular, this takes into account macOS's wonky `libtool` semantics, which involve the following idiosyncrasies:  
* The version of `libtool` that Apple bundles within both Xcode …
=> [`autogen.sh`:]  Abstract the absolute path of `libtoolize` or `glibtoolize` away into `$LIBTOOLIZE`.  

api/baseapi.cpp, ccutil/scanutils.cpp, classify/trainingsampleset.cpp, lstm/input.cpp
This fixes several compiler warnings.
=> Remove some unused local variables and functions

snap/snapcraft.yaml
This is a package for the secure installation of apps that works in most Linux distributions.
Landing it upstream will enable builds that then can be distributed to many users through the Ubuntu store.
=> Add the packaging metadata to build the tesseract snap

ChangeLog
This is a kind of API change, worth documenting. It broke gscan2pdf...
=> Add item to ChangeLog for options writing to stdout instead of stderr

api/baseapi.cpp
Expression (wordstr[w] != '\0') is always true if (wordstr[w] == ' ') is true.
=> Remove redundant condition from TessBaseAPI::AdaptToWordStr()

tessdata/configs/Makefile.am
The  'lstm.train' config file doesn't install when `make install`. So, add entry for  'lstm.train'.
=> Update Makefile.am (add 'lstm.train')

configure.ac
The OpenCL code of Tesseract uses TIFF functions, but the TIFF library
was not added to the linker flags for macOS.
This fixes builds with OpenCL on Mac.
=> opencl: Add missing TIFF library for macOS

api/Makefile.am, configure.ac
This includes and builds on @stweil 's patch to fix linkage on macOS.
~~@zdenop This includes PR #809, so if you accept this you can close PR #809.~~ Let's see if @stweil wants to cherrypick this and added other 3.05 changes.
=> [3.05] Fix #786 OpenCL linkage on macOS

api/Makefile.am
This change is needed to link Tesseract 4.00 with OpenCL on macOS.
=> [4.00] Fix #786 OpenCL linkage fails on macOS

appveyor.yml
All of the appveyor build checks are failing for 3.05 on a parse error.
=> [3.05] Fix YAML parse error in appveyor.yml

configure.ac
The OpenCL code of Tesseract uses TIFF functions, but the TIFF library
was not added to the linker flags for macOS.
This fixes builds with OpenCL on Mac.
=> [3.05] opencl: Add missing TIFF library for macOS

testing/counttestset.sh, testing/reorgdata.sh, testing/runalltests.sh, testing/runtestset.sh
Fix these kinds of warnings:
SC2002: Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead.
SC2086: Double quote to prevent globbing and word splitting.
SC2166: Prefer [ p ] && [ q ] as [ p -a q ] is not well defined.
=> testing: Fix warnings from shellcheck

.travis.yml, ChangeLog, opencl/openclwrapper.cpp
* Use the latest version which is available for Travis CI.
* Remove also some unneeded whitespace.
* Remove unneeded code for old versions of Leptonica.
* Fix the ChangeLog.
=> Leptonica related updates

opencl/openclwrapper.cpp
A Tesseract binary with OpenCL support can also run on a host without
any OpenCL platform, as it simply uses the normal CPU based code.
=> opencl: Fix crash on hosts with no OpenCL platform

ccstruct/debugpixa.h
L_Bmf works for C++ code, but the common form is L_BMF, so use that.
=> ccstruct: Fix Leptonica data type

doc/Doxyfile
Fix this warning from doxygen:
warning: doxygen no longer ships with the FreeSans font.
You may want to clear or change DOT_FONTNAME.
Otherwise you run the risk that the wrong font is being used for dot generated graphs.
=> doc: Remove unsupported font name

api/tesseractmain.cpp, doc/tesseract.1, doc/tesseract.1.asc, doc/tesseract.1.html, doc/tesseract.1.xml
Also fix "C\\++" in the manpage. I've put that in a separate commit, not least because asciidoc is adding an additional escape character for --psm in the manpage.
=> tidy tesseract(1) adding missing options

ccstruct/rejctmap.cpp, ccstruct/rejctmap.h, ccutil/memry.cpp, ccutil/memry.h, classify/adaptive.cpp, classify/adaptmatch.cpp, classify/mfoutline.cpp, classify/ocrfeatures.cpp
Both functions simply call malloc, free.
Remove also unneeded null pointer checks and use calloc where possible.
=> Replace alloc_struct, free_struct

api/pdfrenderer.cpp, opencl/openclwrapper.cpp, opencl/openclwrapper.h
The Tesseract project prefers that names, so fix the remaining exceptions.
=> Use Leptonica struct names L_Compressed_Data, Pix

ccutil/genericvector.h, wordrec/language_model.cpp, wordrec/lm_state.h
These commits reduce the number of memory allocations (in my test cases by about 15%).
`GenericVector` should not prematurely allocate memory in the default constructor since quite a lot of vectors stay empty and there is no overhead in doing the allocation later.
Also, I don't see any reason to do the extra allocation in `LanguageModelDawgInfo`.
=> Avoid unnecessary memory allocations

doc/Makefile.am
It must also include man_MANS – otherwise make tries to build the
man pages also in non maintainer mode without having a rule for that.
This fixes commit 2794410c9b5095f1b6607f68584b1fe5b7a32f7c.
=> doc: Fix use of MAINTAINER_MODE

ccutil/genericvector.h
Commit 907de5995f698e2a01da25fa09f8cadaf31a095f tried to improve
GenericVector, but missed a case where vectors with less than
kDefaultVectorSize were allocated. This resulted in additional
alloc / free operations.
Commit a28b2a033df10010bba9c1f49d6410ad69b3cdde (before memory optimization)
oem 0: total heap usage: 739,238 allocs, 739,237 frees, 161,699,214 bytes allocated
oem 1: total heap usage: 690,182 allocs, 690,175 frees, 144,470,400 bytes allocated
oem 2: total heap usage: 728,213 allocs, 728,206 frees, 182,885,824 bytes allocated
Commit fd3f8f9b2d8c9ebf72b20a9d254a8e5c6900461e without genericvector change
oem 0: total heap usage: 738,980 allocs, 738,979 frees, 161,697,150 bytes allocated
oem 1: total heap usage: 690,182 allocs, 690,175 frees, 144,470,400 bytes allocated
oem 2: …
=> genericvector: Fix minimum size

.travis.yml
* Use container based Ubuntu trusty. This provides a newer gcc version
by default. CI jobs should now start faster.
* Add caching. Leptonica is now only built once for each platform.
* Get Leptonica tar instead of zip file. It's smaller,
and there is no need to store it on disk.
=> Update and improve configuration for Travis CI

ccutil/params.cpp
The local variable intval is of type int.
=> Fix wrong format string

api/pdfrenderer.cpp, ccmain/docqual.cpp, ccutil/genericvector.h, ccutil/strngs.h, classify/blobclass.cpp, classify/featdefs.cpp, lstm/networkio.cpp, lstm/stridemap.cpp, textord/textord.cpp, training/boxchar.cpp, training/commontraining.cpp, training/lstmtraining.cpp, training/normstrngs.cpp, training/stringrenderer.cpp, training/text2image.cpp
Important warnings warrant attention because they may indicate real problems.
Unimportant warnings warrant attention because they obscure the important warnings.
Unfortunately for me the nicest example of the former category, where I also immediately had a solution, was already fixed independently...
This replaces earlier attempts, now up to date, on its own branch, and with some revisions.
=> Too many warnings!

configure.ac, opencl/openclwrapper.h
libtiff is no longer needed for OpenCL, so remove that dependency.
It is still suggested for Windows to redirect warning messages
from the tesseract executable to the console.
=> 3.05: Remove most libtiff dependencies

api/Makefile.am, configure.ac, opencl/openclwrapper.h
libtiff is no longer needed for OpenCL, so remove that dependency.
It is still suggested for Windows to redirect warning messages
from the tesseract executable to the console.
=> Remove most libtiff dependencies

ccutil/ccutil.h
=> ccutil: Remove unneeded include statement

api/tesseractmain.cpp
When Tesseract terminates by calling the exit function,
the destructor of any local auto variable is not called.
Fix two cases by using static variables.
=> main: Fix two memory leaks and fix order of destructor calls

api/renderer.cpp
This error case results in fout_ == nullptr.
Closing a nullptr file is not allowed.
=> Fix crash if output file could not be opened

ccutil/tessdatamanager.cpp
Tesseract crashes with an unhandled exception (std::bad_alloc) if it gets
a bad tessdata file where the numEntries data field is very large (also
after swapping), for example 0x77777777.
=> Improve robustness of TessdataManager

autogen.sh, java/Makefile.am
Fix this automake warning for java/Makefile.am:
java/Makefile.am:67: warning: user target 'clean' defined here ...
automake: ... overrides Automake target 'clean' defined here
java/Makefile.am:67: consider using clean-local instead of clean
=> automake: Enable all warnings and fix a warning

Dockerfile
* Add comment.
* Add missing packages cmake, curl.
* Update bundler (fixes warning).
* Only clone the latest release of travis-build (save time and disk space).
* Remove empty line at end of file.
Signed-off-by: Stefan Weil <stefan@v2201612906741603.powersrv.de>
=> Fix and improve Dockerfile

ccutil/unicharset.h
The member variable default_sid_ was used without being initialized.
Valgrind report for `tesseract --oem 1 hello.png hello`:
Conditional jump or move depends on uninitialised value(s)
at 0x14352E: BITS16::set_bit(unsigned char, unsigned char) (bits16.h:50)
by 0x143E27: WERD::set_flag(WERD_FLAGS, unsigned char) (werd.h:129)
by 0x27D053: WERD_RES::SetupWordScript(UNICHARSET const&) (pageres.cpp:381)
by 0x27CAFD: WERD_RES::SetupForRecognition(UNICHARSET const&, tesseract::Tesseract*, Pix*, int, TBOX const*, bool, bool, bool, ROW*, BLOCK const*) (pageres.cpp:316)
by 0x145903: tesseract::Tesseract::SetupWordPassN(int, tesseract::WordData*) (control.cpp:182)
by 0x145780: tesseract::Tesseract::SetupAllWordsPassN(int, TBOX const*, char const*, PAGE_RES*, GenericVector<tesseract::WordData>*) …
=> UNICHARSET: Add missing initialization

lstm/fullyconnected.cpp
The constant value kNumThreads is not only used to configure the number
of threads but also to allocate vectors used in those threads.
There is only a single thread without OpenMP, so it is sufficient to
allocate vectors with only one element in that case.
Replace also the upper limit in the for loops by the known vector size.
=> Optimize LSTM code for builds without OpenMP

ccstruct/imagedata.cpp
Mingw-w64 does not provide std::chrono.
=> 3.05: Fix build for Mingw-w64

.travis.yml, snap/snapcraft.yaml
The newer version contains fixes for the pixUnsharpMaskingGray*
functions which are relevant for Tesseract (used in ImageData::PreScale
which calls pixScale).
=> Update from Leptonica 1.74.1 to 1.74.2

lstm/lstmtrainer.cpp
The new test in LSTMTrainer::UpdateErrorGraph fixes an assertion
(see issues #644, #792).
The new test in LSTMTrainer::ReadTrainingDump was added to improve
the robustness of the code.
=> LSTMTrainer: Catch empty vectors

snap/snapcraft.yaml
1.74.2 is no longer available from the leptonica website. But anyway, it seems safer going forward to download it from github. It's https, and it won't disappear as easily. Also, this is the same source used by travis, so there's less chance of shipping something untested.
=> Download the leptonica source from github

ccstruct/imagedata.cpp, viewer/scrollview.cpp
This fixes problems on Windows when Tesseract and Leptonica use different
C runtime libraries.
=> Use lept_free to free memory allocated by Leptonica

training/lang_model_helpers.cpp
Windows does not provide a mkdir function with two parameters.
=> Fix broken build for Windows

api/baseapi.cpp
The default resolution is used for images without an explicit resolution
or with an unreasonable resolution (smaller than 70 or larger than 2400).
=> Change default resolution from 70 to 300 dpi

api/tesseractmain.cpp
This causes errors caught by `TessBaseAPI::Init` in `tesseractmain.cpp:main` to not cause an exit immediately, though I doubt that this will cause serious problems.
=> move code around so that list-langs will work without an English traineddata file

.gitignore, .gitmodules, CMakeLists.txt, tests/tesseracttests.cpp
Instructions (run in Tesseract source directory):
git submodule update --init googletest
mkdir demo && cd demo
cmake ..
make
bin/tesseract_test
=> Add GoogleTest infrastructure

configure.ac
* Fix grammar.
* Fix text ("after building ..." is not necessary).
=> Fix hint for training build

ccmain/resultiterator.cpp
Empty lines in text output are needed to separate paragraphs,
but there should not be an empty line at the end of the text.
=> Don't add empty line to text output

CMakeLists.txt
On non win32 platforms the library was being built as `liblibtesseract.4.0.0.dylib` (osx shared) or `liblibtesseract.a` (linux static).
Also the `version.h` file was not being installed.
=> cmake install fixes

CMakeLists.txt
Otherwise we abort with the message `DotProductAVX can't be used on Android`.
=> CMake: Add -mavx and -msse4.1 compile flags on unix

training/Makefile.am
Puts back changes from https://github.com/tesseract-ocr/tesseract/commit/9d258e20d339142678f06d3e3c181fc60f83b593
=> fix accidental overwrite because of using old version

api/Makefile.am, arch/Makefile.am, ccmain/Makefile.am, ccstruct/Makefile.am, ccutil/Makefile.am, classify/Makefile.am, configure.ac, cutil/Makefile.am, dict/Makefile.am, lstm/Makefile.am, opencl/Makefile.am, textord/Makefile.am, training/Makefile.am, unittest/Makefile.am, viewer/Makefile.am, wordrec/Makefile.am
Libtool's convenience libraries should never be installed. Fixes #985.
=> Autotools build: Remove the option 'USING_MULTIPLELIBS'

unittest/Makefile.am
The library is provided in the build path (which is not
the same as the source path for out of tree builds).
=> unittest: Fix path for libtesseract in out of tree builds

unittest/Makefile.am, unittest/apiexample_test.cc
The test failed for out-of-tree builds with autotools because it could not find the required files.
It also failed when the "en_US.UTF-8" locale was missing.
Now it passes. This completes my previous PR #1123.
=> Fix unittest/apiexample_test

ccmain/tesseractclass.cpp, ccmain/tesseractclass.h, classify/classify.h
LSTM uses its own dictionary, expose it if LSTM code is used and the old engine's one is empty.
=> Returns the correct dictionary if lstm only used

ccstruct/pageres.cpp
See this comment https://github.com/tesseract-ocr/tesseract/issues/781#issuecomment-323304593
=> Fix to preserve_interword_spaces work again

training/normstrngs.cpp
Fixes issue https://github.com/tesseract-ocr/tesseract/issues/1114
=> change type to UChar32 to fix IsValidCodepoint

training/normstrngs.cpp
This reverts commit a404c9cdb3f88a2be1e2cf4dd3bac178b1963b31.
That code no longer matched the specification (see code comment).
=> Revert "change type to UChar32 to fix IsValidCodepoint"

api/renderer.cpp, ccmain/tesseractclass.cpp, ccmain/tesseractclass.h
Now Tesseract adds a page break (normally form feed) by default.
It is still possible to suppress page breaks by setting an empty
page_separator.
=> Remove Tesseract parameter "include_page_breaks" and use FF by default

ccmain/ltrresultiterator.cpp
**Partial** fix for issue #1074
=> Make font size estimation work with the lstm engine

training/unicharset_extractor.cpp
If unicharset_extractor was called without any argument,
a help message was printed by tesseract::ParseCommandLineFlags.
Replace that by the local help message which is better.
=> Fix help message for unicharset_extractor

ccutil/genericvector.h
ftell returns a long value which can be negative when an error occurred.
It returns LONG_MAX for directories.
Both cases were not handled by the old code.
=> Improve robustness of function LoadDataFromFile

training/validator.cpp
with Visual Studio 2015 RTM:
```
Error C2039: 'back_inserter': is not a member of 'std'
Error C3861: 'back_inserter': identifier not found
```
need "iterator" with Visual Studio 2015 (vc14).
```
#include <iterator>
```
=> fixed missing include for std::back_inserter.

api/tesseractmain.cpp, ccstruct/publictypes.h
Wrote a function to throw an error if PSM is outside 0-13 or OEM
is outside 0-5.
=> Added check if input PSM value is outside of range

ccstruct/seam.cpp, ccstruct/seam.h
ccstruct/seam.cpp:66:26: warning:
array subscript has type 'char' [-Wchar-subscripts]
Fix it by using an unsigned index and use the same type for related values.
=> Fix compiler warning (-Wchar-subscript)

ccstruct/publictypes.h
Since commit cdc35338c53a1af1fcb95473445f2aabfdb3f6d1 Tesseract checks
the value passed for `--oem NUM`.
That only works as expected when the old (now unused) engine mode values
for cube are removed.
=> Remove unused cube OCR engine modes

ccmain/applybox.cpp
The variable 'diff' gets a double value and is compared with a double value,
so it should be double, too.
=> Clean use of double / float

api/tesseractmain.cpp
These series partially reverts commit 173ad2bd0044c82973fe17b6f077e7202602cb99.
=> Support different help texts for normal and advanced users and restore legacy mode

ccmain/linerec.cpp
=> Don't drop words with low certainty

api/baseapi.cpp
Show a warning if datapath_ is NULL instead of crashing.
=> Fix CID 1164570 (Dereference after null check)

api/baseapi.cpp
If equ_detect_ can be NULL, we must catch that case and show a warning
instead of crashing in method SetEquationDetect.
=> Fix CID 1164569 (Dereference after null check)

training/language-specific.sh
I didn't keep great notes as I did this; aside from [Gadelica](http://www.leabhair.ie/sob/gadelica.zip): [(Irish description)](http://www.leabhair.ie/sob/gadelica/index.html) the fonts came from [here](http://www.gaelchlo.com/clonna.html), e.g.:
* [Bunchló Ársa GC](http://www.gaelchlo.com/bunargc.zip) and [Bunchló Ársa Dubh GC](http://www.gaelchlo.com/bunardgc.zip) [(Irish description)](http://www.gaelchlo.com/bunarsgc.html)
* [Bunchló GC](http://www.gaelchlo.com/bungc.zip) and [Bunchló Dubh GC](http://www.gaelchlo.com/bundgc.zip) [(Irish description)](http://www.gaelchlo.com/bungc.html)
=> Add Irish Uncial fonts to language-specific.sh

ccutil/unichar.h
The unqualified "string" class created class not found error when compiling with OpenCV
=> Fixed unqualified class "string"

ccutil/unichar.h, ccutil/unicharset.h
I am getting compile errors when compiling my bindings with `clang++ -std=gnu++11` (MacOS 12.13). This fixes it for me.
=> Fixes for C++11

lstm/lstm.cpp, lstm/weightmatrix.cpp, wordrec/language_model.cpp
This also adds support for environments without a log2 function (Android).
=> Replace log2(n) by local functions

lstm/lstm.cpp
=> Fix syntax error.

README.md
Fix also some whitespace issues.
=> README: Use CamelCase for GitHub

ccutil/platform.h, viewer/svutil.h
MSVC 8.0 was released in 2005 and we don't support it.
=> Remove obsolete code

ccutil/unicharset.cpp, ccutil/unicharset.h
Fix 306 warnings from MS C:
tesseract\ccutil\unicharset.h(242): warning C4267:
'argument': conversion from 'size_t' to 'int', possible loss of data
The change also avoids some type conversions.
=> Fix compiler warning (possible loss of data)

lstm/lstm.cpp
=> lstm: Use MS C intrinsic function for faster calculation of log2

doc/tesseract.1.asc
tessdata_fast includes bre.traineddata.
=> doc: Add missing language to list

ccutil/genericvector.h
gcc reports this warning about 250 times:
ccutil/genericvector.h:378:48: warning:
comparison between signed and unsigned integer expressions [-Wsign-compare]
=> Fix compiler warning (-Wsign-compare)

unittest/Makefile.am, unittest/apiexample_test.cc, unittest/osd_test.cc
tessdata_best and tessdata_fast recently changed the path for script data,
so the tests have to be updated, too.
In addition, the relative paths did not work with out-of-tree builds.
Use absolute paths and add them as C macros to the compiler flags.
=> Update unittest for new script data location and fix out-of-tree build

autogen.sh
autoconf-archive and pkg-config are required, but users often missed that requirements.
The script now detects and reports those missing requirements and removes
the incomplete generated configure script.
=> autogen: Report missing requirements

autogen.sh
It was introduced by commit d50769dc01df85c993439b2943bac4d884901441.
=> autogen: Fix typo in comment

wordrec/language_model.cpp
gcc warning:
wordrec/language_model.cpp:959:16: warning:
‘char* strncpy(char*, const char*, size_t)’ output truncated before
terminating nul copying as many bytes from a string as its length
[-Wstringop-truncation]
memcpy could also be a little bit faster than strncpy.
=> wordrec: Fix compiler warning (-Wstringop-truncation)

viewer/scrollview.cpp
gcc warnings:
viewer/scrollview.cpp:72:10: warning:
‘char* strncpy(char*, const char*, size_t)’ output truncated before
terminating nul copying as many bytes from a string as its length
[-Wstringop-truncation]
viewer/scrollview.cpp:118:14: warning:
‘char* strncpy(char*, const char*, size_t)’ specified bound depends on
the length of the source argument [-Wstringop-overflow=]
viewer/scrollview.cpp:746:10: warning:
‘char* strncpy(char*, const char*, size_t)’ output truncated before
terminating nul copying as many bytes from a string as its length
[-Wstringop-truncation]
viewer/scrollview.cpp:830:10: warning:
‘char* strncpy(char*, const char*, size_t)’ output truncated before
terminating nul copying as many bytes from a string as its length
[-Wstringop-truncation]
Signed-off-by: Stefan Weil …
=> viewer: Fix some compiler warnings (-Wstringop-truncation)

arch/dotproductavx.cpp, arch/dotproductsse.cpp
Fix these gcc warnings:
arch/dotproductavx.cpp:53:45: warning:
type qualifiers ignored on cast result type [-Wignored-qualifiers]
arch/dotproductavx.cpp:54:45: warning:
type qualifiers ignored on cast result type [-Wignored-qualifiers]
arch/dotproductsse.cpp:59:45: warning:
type qualifiers ignored on cast result type [-Wignored-qualifiers]
arch/dotproductsse.cpp:60:45: warning:
type qualifiers ignored on cast result type [-Wignored-qualifiers]
=> arch: Fix some compiler warnings (-Wignored-qualifiers)

configure.ac
While "echo -n" works on Debian GNU Linux, it fails to produce a valid
configure file on macOS, so try a different shorter solution.
=> configure: Use m4_esyscmd_s to suppress linefeed (fix needed for macOS)

ccutil/tessdatamanager.cpp, ccutil/tessdatamanager.h
This allows further simplifications for the version handling.
Move the implementation for the constructors from .h file to .cpp file
to reduce dependencies.
Remove unneeded include statements from the .h file to reduce more
dependencies.
=> tessdatamanager: Use PACKAGE_VERSION instead of TESSERACT_VERSION_STR

CMakeLists.txt, api/apitypes.h, api/baseapi.cpp, api/pdfrenderer.cpp, api/renderer.cpp, ccutil/Makefile.am, ccutil/version.h
ccutil/version.h is now no longer needed.
=> Update version handling

arch/dotproductavx.cpp
This fixes a warning from clang:
arch/dotproductavx.cpp:94:51: warning:
unexpected token in pragma diagnostic [-Wunknown-pragmas]
=> arch: Remove stray ) in pragma

ccutil/unicharcompress.cpp
This fixes a compiler warning. The variable is unused since commit
0e95e2ca874745c2682d281a7357efc4ea182002.
Remove also a related code comment.
=> Remove unused local variable max_num_strokes

api/tesseractmain.cpp
It was replaced by --psm and deprecated in commit 92d981b93.
=> Remove deprecated support for -psm argument

api/baseapi.cpp, api/baseapi.h, api/capi.cpp, api/capi.h
It was deprecated in commit a18816f83 more than 7 years ago.
=> Remove deprecated method DumpPGM

dict/dict.cpp, dict/dict.h
=> dict: Remove deprecated parameters

lstm/input.cpp
Replace float compare operation by integer compare operation
and avoid float division if it is not needed.
=> lstm: Small code optimisation

configure.ac
AX_SPLIT_VERSION only works after AM_INIT_AUTOMAKE, so that macro had
to be moved.
GENERIC_MAJOR_VERSION, GENERIC_MINOR_VERSION and GENERIC_MICRO_VERSION
are now set automatically and can be used in further processing.
=> autoconf: Get version components from PACKAGE_VERSION

ccutil/helpers.h
The method is called with a float argument several times, and the
previous implementation which only supported a double argument
resulted in type conversions and compiler warnings.
=> Add IntCastRounded for float argument

CMakeLists.txt
As Tesseract now uses semantic versioning, the old method to calculate
the library version was no longer valid.
=> Update library version handling for cmake

configure.ac, doc/Makefile.am
That macro disables automated updates when configure.ac or a Makefile.am
changes. Normally those updates are wanted because users typically
forget running ./autogen.sh.
See also the GNU documentation why AM_MAINTAINER_MODE should not be used:
https://www.gnu.org/software/automake/manual/html_node/maintainer_002dmode.html
=> configure: Don't use AM_MAINTAINER_MODE by default

lstm/fullyconnected.cpp, lstm/fullyconnected.h, lstm/lstm.cpp
This avoids NULL parameters and fixes a warning from Coverity Scan.
=> Overload method ForwardTimeStep (CID 1385636 Explicit null dereferenced)

configure.ac, doc/Makefile.am
Commit f9157fd91db9140adacc4d7cd9af5677e4f0163e changed the rules for
the documentation, so make always tried to build it and failed if
asciidoc was missing since that commit.
Now configure tests whether asciidoc is available and builds the
documentation conditionally. It also reports that to the user.
=> Don't try to build manpages if asciidoc is missing

training/tesstrain_utils.sh
as reported on #1453 `mktemp --tmpdir` doesn't work for MAC, so you need to use `mktemp -t`
=> Fix for mktemp bug on MAC OS X

configure.ac
Building with G++ on Darwin breaks with the MacPorts toolchain, when either AVX, AVX2, or SSE4.1 compiler option is set, unless G++ is actually CLANG.
This PR allows building with G++, by asking G++ to delegate assembly to the clang integrated assembler, instead of the GNU one.
GNU compilers choke when assembling with AS. After `autogen.sh` and `configure`, `make` ends quickly with such error trace:
```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -DNDEBUG -I../ccstruct -I../ccutil -I../viewer -I/opt/local/include/leptonica -I/opt/local/include/pango-1.0 -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/cairo -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/pixman-1 …
```
=> Add flag to build compiler options with G++ on macOS/MacPorts for Tesseract 4.x.

CMakeLists.txt
adds a switch to suppress building googletest and tests
reason: when adding tesseract to another project via [ExternalProject_Add](https://cmake.org/cmake/help/v3.0/module/ExternalProject.html) it is impossible to not clone submodules, which forces tesseracts cmake to build the tests. the added switch retains current default behaviour.
=> cmake switch to turn off test building

configure.ac
It is only used by the compiler.
=> configure: Remove optimize option for preprocessor

ccutil/mainblk.cpp
Warning C4996: 'access': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _access.
=> Fixed compiler warning

configure.ac
Tesseract's training tool text2image uses these two functions: 
pango_glyph_item_iter_init_start
pango_glyph_item_iter_next_cluster
That means it requires Pango >= 1.22.0:
https://developer.gnome.org/pango/stable/api-index-1-22.html
https://developer.gnome.org/pango/stable/pango-Glyph-Storage.html#pango-glyph-item-iter-init-start
https://developer.gnome.org/pango/stable/pango-Glyph-Storage.html#pango-glyph-item-iter-next-cluster
=> configure.ac: Check for the presence of pango 1.22.0 or higher

ccmain/superscript.cpp
CID: 1375399 Variable bb1 going out of scope leaks the storage it points to
=> Fixed Resource Leak detected by Coverity

training/commandlineflags.cpp, training/commandlineflags.h
- Don't support --helpshort as an undocumented alias for --help
- Don't allow any number of leading '-' characters.
The preferred form uses --OPTION, and for compatibility reasons the new
code still supports -OPTION.
Update also related documentation comments.
=> training: Fix dubious parsing of command line

training/lstmtraining.cpp
The iteration counter should be checked for each iteration,
not only at the end of a batch.
=> lstmtraining: Fix handling of --max_iterations

configure.ac
This is the autoconf version shipped in RHEL/CentOS 6.
=> configure.ac: Update minimum required autoconf version to 2.63

configure.ac
The newer macros that replace the obsolete ones are already present in configure.ac.
* AC_PROG_LIBTOOL -> LT_INIT
* AC_LANG_CPLUSPLUS -> AC_LANG([C++])
=> configure.ac: Remove obsolete macros

README.md
They are now again shown on two lines as it was before
commit 0d9cdbe6dd1e7a143f8c1d39519669d8c5cd9f57.
=> Separate build status badges from other status badges

configure.ac
g++ builds require extra flags rejected by clang++. The bug is that the
flags are actually added unconditionally. This commit fixes the
condition.
See https://github.com/tesseract-ocr/tesseract/pull/1474 and related.
Tests conducted and report: https://github.com/tesseract-ocr/tesseract/pull/1474#issuecomment-383437228
=> Fix wrong environment test that breaks clang++ builds.

ccutil/unicharset.h
Commit cb77067f554683fcf972cff0b497e9c4bfd3d877 changed the declaration of
null_script. An additional TESS_API is needed to satisfy the VS linker.
=> Fix linker regression for Visual Studio

unittest/Makefile.am
Add include path for api/tess_version.h.
=> Fix unittest (missing include path)

Makefile.am, src/api/Makefile.am, src/arch/Makefile.am, src/ccmain/Makefile.am, src/ccstruct/Makefile.am, src/classify/Makefile.am, src/cutil/Makefile.am, src/dict/Makefile.am, src/lstm/Makefile.am, src/opencl/Makefile.am, src/textord/Makefile.am, src/training/Makefile.am, src/viewer/Makefile.am, src/wordrec/Makefile.am, unittest/Makefile.am
This should fix "make" and "make training".
=> Partial fix for autotools configuration after source tree reorganisation

src/ccmain/paragraphs.cpp
It should not be needed with newer versions of Visual Studio.
=> Remove old hack for Visual Studio

cmake/Configure.cmake, cppan.yml, src/ccmain/paragraphs_internal.h
Tesseract code does not use strings.h (strngs.h was once called strings.h),
so that dependency can also be removed from cmake and cppan configuration.
=> Remove unneeded include statements for string / strings.h

src/training/stringrenderer.cpp
Coverity ID: 1386084 the set_font method has accessed resolution_ before it was initialized by the set_resolution method.
=> Fixed access to uninitialized variable

CMakeLists.txt
This fixes 208 compiler warnings of this form:
C4566: character represented by universal-character-name [...]
cannot be represented in the current code page (1252)
=> Add /utf-8 for MSVC

src/ccmain/adaptions.cpp, src/ccmain/applybox.cpp, src/ccmain/docqual.cpp, src/ccmain/output.cpp, src/ccmain/pagesegmain.cpp, src/ccmain/pgedit.cpp, src/ccmain/reject.cpp, src/ccmain/tessbox.cpp, src/ccmain/tfacepp.cpp, src/ccutil/tessdatamanager.cpp, src/dict/dawg.cpp, src/dict/dict.cpp, src/dict/stopper.cpp, src/dict/trie.cpp, src/textord/colfind.cpp, src/textord/colpartition.cpp, src/textord/imagefind.cpp, src/textord/linefind.cpp, src/textord/strokewidth.cpp, src/textord/tablefind.cpp, src/textord/tabvector.cpp, src/viewer/scrollview.cpp, src/viewer/svutil.h
It's still possible to set the warning level in the project settings,
but single source files should normally not disable compiler warnings.
=> Don't disable compiler warnings for Visual Studio

src/textord/colpartition.cpp
If height_count stays zero the maximal error calculation contains a division by zero.
=> Fixed CID 1164537 (possible division by zero)

unittest/osd_test.cc
Also got error while building on  
Linux tesseract-ocr 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:33:25 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux
with 
g++ (Ubuntu/IBM 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
```
g++ -DHAVE_CONFIG_H -I. -I..  -DNDEBUG -DTESSDATA_DIR="\"/home/ubuntu/tessdata\"" -DTESTING_DIR="\"/home/ubuntu/tesseract/testing\"" -DPANGO_ENABLE_ENGINE -I../src/api -I../src/api -I../src/arch -I../src/ccmain -I../src/ccstruct -I../src/ccutil -I../src/classify -I../src/cutil -I../src/dict -I../src/display -I../src/lstm -I../src/textord -I../src/viewer -I../src/wordrec -isystem ../googletest/googletest/include -I/usr/local/include/leptonica -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/powerpc64le-linux-gnu/glib-2.0/include -I/usr/include/cairo …
```
=> remove non-essential logging function

src/training/stringrenderer.cpp
This reverts commit 941e1c4c84ab3c94bda0da81327238908a1e4192. It is no
longer needed since commit f54800f14b41cdb7861d0769f202e79bb013cd32.
=> Revert "fixes #388 by using raw bytes utf8 encoding"

src/api/renderer.h
The commit effa574 in 20.01.2017 added the bool textonly to the constructor of TessPDFRenderer. To maintain the compatibility to older APIs which are still using only two parameter, a default value for the textonly parameter is set.
=> Added downward compatibility for older APIs

src/textord/colpartition.cpp
The following code caused a crash when Tesseract was compiled with -ftrapv:
1259	  int width = right - left;
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff665c231 in __GI_abort () at abort.c:79
#2  0x00007ffff69e34d8 in __subvsi3 () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#3  0x000055555560c1c5 in tesseract::ColPartitionGrid::FindVPartitionPartners (this=0x55555717e3c0, to_the_left=true, part=0x5555571fa380)
at ../../../src/textord/colpartitiongrid.cpp:1259
#4  0x000055555560bda0 in tesseract::ColPartitionGrid::FindPartitionPartners (this=0x55555717e3c0) at ../../../src/textord/colpartitiongrid.cpp:1196
#5  0x00005555555f52b6 in tesseract::ColumnFinder::FindBlocks (this=0x55555717e280, pageseg_mode=tesseract::PSM_AUTO, scaled_color=0x0, …
=> ColPartition: Add missing initialisation for median_left, median_right

src/classify/featdefs.cpp, src/classify/intproto.cpp, src/classify/mf.cpp, src/classify/ocrfeatures.cpp
Commit 0248c7ff9d785c5cc5e60e8bb74794c4ebb09c02 replaced math.h by cmath.
Therefore isinf and isnan are no longer declared.
Replace them by their C++ 11 variant.
Signed-off-by: Stefan Weil <stweil@ub-blade-02.bib.uni-mannheim.de>
=> Fix compilation with g++-5

src/ccutil/serialis.cpp, src/ccutil/serialis.h
Raise an assertion for unexpected arguments and use size_t instead of int
for the size argument which is typically sizeof(some_datatype).
=> TFile: Improve handling of potential integer overflow

ccstruct/boxread.cpp
This is a partial backport from 4.0.0, based on
commit ce76d1c56983b364558c88a6dc99771653d5662b.
=> Fix unterminated string (backport from 4.0.0)

src/ccutil/serialis.cpp
The assertions introduced by commit 8bea6bcc12928daf58d7f5f6370c3a548bd2801c
were too strict. The first one failed in osd_test, the second one failed
in `tesseract IMAGE BASE --psm 13 lstm.train`.
=> TFile: Relax assertion and allow FRead, FWrite with count == 0

unlvtests/counttestset.sh, unlvtests/runtestset.sh
Commit 934e612a3e64201708a86fd71b225ae4c97411d2 added too many quotes.
=> Fix script for UNLV tests

src/ccutil/scanutils.cpp
Format strings which contain "%*s" show this error in Valgrind:
==32503== Conditional jump or move depends on uninitialised value(s)
==32503==    at 0x2B8BB0: tvfscanf(_IO_FILE*, char const*, __va_list_tag*) (scanutils.cpp:486)
==32503==    by 0x2B825A: tfscanf(_IO_FILE*, char const*, ...) (scanutils.cpp:234)
==32503==    by 0x272B01: read_unlv_file(STRING, int, int, BLOCK_LIST*) (blread.cpp:54)
==32503==    by 0x1753CD: tesseract::Tesseract::SegmentPage(STRING const*, BLOCK_LIST*, tesseract::Tesseract*, OSResults*) (pagesegmain.cpp:115)
==32503==    by 0x1363CD: tesseract::TessBaseAPI::FindLines() (baseapi.cpp:2291)
==32503==    by 0x130CF1: tesseract::TessBaseAPI::Recognize(ETEXT_DESC*) (baseapi.cpp:802)
==32503==    by 0x1322D3: tesseract::TessBaseAPI::ProcessPage(Pix*, int, char …
=> scanutils: Fix illegal memory access

src/api/baseapi.cpp
Normal C++ programs like those which are built for tesseract automatically
set the locale "C".
There can be different locale settings if the tesseract library is used
in other software.
A wrong locale can cause wrong results from sscanf which is used at
different places in the tesseract code, so make sure that we have the
right locale settings and fail if that is not the case.
=> Test for correct locale settings

src/api/capi.h
Commit 87d33b6c9ed87699ff0d6588279d8268f5df6db3 added code which uses bool.
Therefore stdbool.h must be included for compilations with a C compiler.
=> capi: Fix regression caused by use of bool data type

unittest/Makefile.am
The unittest could not run when building out of source tree.
Fix the symbolic link and make sure that the directory for it exists.
=> Fix symbolic link in unittest

src/textord/scanedg.cpp
Check whether the top right point of the block is inside of the
thresholded image t_pix. Otherwise the following code would make
illegal memory accesses.
=> block_edges: Add assertions for block coordinates

src/training/tesstrain_utils.sh
Restrict width size to 2560 to avoid error during training
=>  Change default width for images output by text2image

src/ccmain/Makefile.am, src/ccutil/Makefile.am, src/lstm/Makefile.am
Install only those headers which are needed by third party applications.
=> Remove more header files from public API

src/ccstruct/dppoint.cpp, src/ccstruct/fontinfo.h, src/ccstruct/rejctmap.h, src/ccstruct/statistc.cpp, src/ccutil/Makefile.am, src/ccutil/genericvector.h, src/ccutil/serialis.cpp, src/ccutil/strngs.cpp, src/ccutil/tessdatamanager.cpp, src/training/commandlineflags.cpp, src/training/fileio.cpp, src/training/normstrngs.cpp
genericvector.h used a mix of assert and ASSERT_HOST.
By using assert only, it does no longer depend on errcode.h
which defines the ASSERT_HOST macro.
Other files which still use ASSERT_HOST now need an explicit
include statement for errcode.h.
Remove errcode.h from the public Tesseract API.
=> Replace ASSERT_HOST in genericvector.h

java/com/google/scrollview/ui/SVWindow.java
Handle also the case when the user closes the dialog
without selecting an answer.
=> Fix CID 1386106 (Explicit null dereferenced)

INSTALL.GIT.md, autogen.sh, m4/ax_check_compile_flag.m4, m4/ax_split_version.m4, snap/snapcraft.yaml
It creates much confusion and causes many issue reports,
so let us drop this dependency.
The two new files in the m4/ directory are current copies from GitHub
(https://github.com/autoconf-archive/autoconf-archive/).
=> Remove autoconf-archive dependency

src/api/pdfrenderer.cpp
The division was made with integers, giving a wrong result.
* Avoid division and use pure integer operations.
* Add missing "static" attribute.
=> pdfrenderer: Fix ClipBaseline and optimize code

src/ccstruct/blobs.cpp, src/classify/cluster.cpp, src/classify/kdtree.cpp, src/classify/kdtree.h, src/classify/protos.cpp, src/classify/protos.h, src/cutil/cutil.h, src/cutil/oldlist.cpp, src/cutil/oldlist.h, src/dict/dict.h, src/dict/permdawg.cpp, src/dict/trie.h, src/wordrec/chopper.h
* Remove unrelated include statements from cutil.h.
* Remove macros FALSE, TRUE.
* Move macro CHARS_PER_LINE from cutil.h to dict.h.
* Remove unneeded macro _ARGS.
* Remove unused typedef statements.
* Remove macro new_line (only used once).
* Remove unused macro print_string.
* Update include statements for other source files.
=> Clean up cutil.h

src/api/pdfrenderer.cpp, src/ccutil/clst.cpp, src/ccutil/elst.cpp, src/ccutil/elst2.cpp, src/classify/adaptive.cpp, src/classify/cluster.cpp, src/classify/intproto.cpp, src/opencl/openclwrapper.cpp, src/viewer/svutil.cpp
This removes unneded type casts to (char*) and (const char*).
=> Remove unneeded type casts

src/api/baseapi.cpp, src/api/pdfrenderer.cpp, src/ccmain/osdetect.cpp, src/ccmain/output.cpp, src/ccmain/paragraphs.cpp, src/ccmain/paragraphs_internal.h, src/ccmain/pgedit.cpp, src/ccmain/recogtraining.cpp, src/ccmain/superscript.cpp, src/ccstruct/ocrblock.cpp, src/ccstruct/stepblob.cpp, src/ccutil/globaloc.cpp, src/ccutil/scanutils.cpp, src/classify/adaptive.cpp, src/classify/intfx.cpp, src/classify/intmatcher.cpp, src/classify/intproto.cpp, src/classify/mfx.cpp, src/classify/mfx.h, src/classify/ocrfeatures.cpp, src/dict/dawg.cpp, src/textord/bbgrid.cpp, src/textord/makerow.cpp, src/training/commandlineflags.cpp, src/training/dawg2wordlist.cpp, src/training/normstrngs.cpp, src/training/stringrenderer.cpp, src/training/text2image.cpp, src/training/validator.cpp
Add missing include statements, add missing "static" qualifiers or
remove functions which are not used at all.
=> Fix compiler warnings [-Wmissing-prototypes]

src/ccstruct/matrix.h, src/ccutil/genericvector.h, src/ccutil/indexmapbidi.cpp, src/ccutil/strngs.cpp, src/classify/adaptmatch.cpp, src/classify/mastertrainer.cpp, src/classify/picofeat.cpp, src/classify/shapeclassifier.cpp, src/classify/trainingsample.cpp, src/classify/trainingsample.h
Sizes which are read from file and which are used to allocate memory or do calculations which can
result in an arithmetic overflow should be checked for validity before using them.
This patch set limits such sizes to UINT16_MAX (65535) which hopefully is sufficient for all
use cases in Tesseract.
=> Fix several issues reported by Coverity Scan (related to untrusted external data)

src/lstm/networkbuilder.cpp
`int depth = strtol(*str + 1, str, 10);`
`**str` holds the words in the VGSL specification, and `*str` holds a single word, lets say, `Fr64`. Now, the `strtol` function modifies `str` to point to the first character which a non-digit number, and assumes that ` *str+1 ` points to a number (of valid integer format) as a string (automatically skipping all the white spaces, and no other characters), where in reality, it seems to point to `r` in `Fr164`.This is a bad argument, which results in `strtol` returning 0.
` strtol (*str + 2, str, 10)` should be passed instead.
Kindly check issue #1748 for the full thread of discussion.
=> Fixed "Invalid F spec" error while building FullyConnected layer.

src/ccmain/thresholder.cpp, src/ccstruct/rect.cpp, src/ccutil/tprintf.cpp, src/ccutil/tprintf.h, src/training/tlog.h
Commit 4d514d5a606f43b5fbbb163a7244f5e19d0f6e88 introduced tprintf_internal
with an additional argument "level" which was removed again in commit
7dc5296fe992c4a0bbfb9a0672363e7c12d32460.
So we can now restore the original state without tprintf_internal.
Remove also the declaration of debug_window_on (it does not exist since
commit 030aae98969d41cabb500560b3bac2262b91a344) and make the
configuration parameter debug_file local as it is only used by tprintf.
=>  Replace tprintf_internal by tprintf and clean tprintf code 

src/opencl/opencl_device_selection.h, src/opencl/openclwrapper.cpp, src/opencl/openclwrapper.h
OpenclDevice::getDeviceSelection crashed when outdated information
was read from file and device.score was not set.
Change also the struct definitions from C to C++ and
eliminate some type casts.
=> opencl: Fix crash and clean code a bit

src/classify/intfeaturespace.cpp, src/classify/intfeaturespace.h, src/training/commontraining.cpp
The Serialize method is used indirectly by MasterTrainer::Serialize,
but there is no corresponding MasterTrainer::DeSerialize.
=>  IntFeatureSpace: Remove unused DeSerialize method

src/api/pdfrenderer.cpp, src/api/renderer.cpp, src/ccutil/serialis.cpp, src/ccutil/serialis.h, src/classify/blobclass.cpp, src/lstm/network.cpp, src/lstm/plumbing.cpp, src/lstm/reconfig.cpp, src/lstm/static_shape.h, src/lstm/weightmatrix.cpp
The current code uses fread (+ byte swapping) / fwrite (without byte swapping) and FRead or FReadEndian/ FWrite for de-serialization and serialization. The resulting file is always written in host endianness, so reading on a host with different endianness requires byte swapping. All functions return the number of elements read or written which must be compared with the intended value.
The new code always uses Deserialize / Serialize methods which return true for success or false for failure, like it is already done with the existing Deserialize / Serialize methods for a lot of classes.
With the new API it will be very easy to switch to a fixed little endian file format as soon as it is used for all serialization code.
=> Simplify API for serialization and add first users

cmake/Configure.cmake, configure.ac, cppan.yml
Remove some unneeded checks, simplify code and use uniform help texts.
For the Tesseract specific options now only the non default variant is explicitly shown in the help text.
=> Clean configuration code

src/ccutil/genericvector.h
One of the checks was too restrictive, as lstmeval deserializes
char arrays with 14000000 elements, so raise the limit to 30000000.
That check was added in commit 992031e8248c3b95cda23315bf390303c7c7955c.
Add also assertions which help finding such problems in debug mode.
Signed-off-by: Stefan Weil <stweil@ub-backup.bib.uni-mannheim.de>
=> Increase limit and add assertions for deserialization of large arrays

src/ccutil/genericvector.h
The last limit was still too small.
=> Increase limit for deserialization of large arrays

configure.ac
The first usage of AC_CHECK_HEADERS must be unconditional,
otherwise configure fails to detect support for shared libraries.
This fixes a regression introduced by commit a07025c993decab9ff7f3549bd78f658c04b1fe5.
=> Fix regression (shared libraries no longer supported)

src/api/baseapi.cpp, src/ccmain/linerec.cpp, src/ccmain/resultiterator.cpp, src/ccmain/resultiterator.h, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h, src/ccstruct/pageres.h, src/lstm/lstmrecognizer.cpp, src/lstm/lstmrecognizer.h, src/lstm/recodebeam.cpp, src/lstm/recodebeam.h
By using the parameter -c glyph_confidences=true the user is able to enrich
the hOCR output with additional information. Tesseract then lists additionally
the timesteps with all glyphs that were considered with their confidence
for every timestep of the LSTM.
The format of the hOCR output is slightly changed: There is now a linebreak
after every word for better readability by humans.
=> Added a feature to enrich the hOCR output with glyph confidences

src/training/tesstrain_utils.sh
This reverts commit fdc243b3638fa799cae3b921e2b137d6121425b1 because
it caused a regression reported in issue #1798.
=> Revert "Change default width for images output by text2image"

src/ccmain/control.cpp
CID: 1391264 (Improper use of negative value)
=> Fix issue reported by Coverity Scan

src/api/tesseractmain.cpp
Page segmentation mode "OSD only" requires osd.traineddata,
so use it automatically.
Report a warning if the user specified a different language.
=> Fix potential crash with --psm 0 and use osd.traineddata automatically

src/ccmain/thresholder.cpp
The ThresholdRectToPix OpenCL kernel only supports 4 channels.
=> Fix ImageThresholder::OtsuThresholdRectToPix for OpenCL

src/api/baseapi.cpp, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h, src/lstm/lstmrecognizer.cpp, src/lstm/lstmrecognizer.h, src/lstm/recodebeam.cpp, src/lstm/recodebeam.h
The parameter glyph_confidences is changed from bool to int.
An execution with value 1 outputs the hOCR file enriched with glyph confidences
for every timestep like before. An execution with value 2 outputs the timesteps
accumulated over the recognized characters.
=> Added the option for character accumulated glyph confidences.

src/ccmain/applybox.cpp, src/ccmain/tesseractclass.h
Instead of adding an empty TBOX at the end of the box list,
that corner case is now handled by passing a nullptr (like
it was already done for the first box in the list).
This avoids the calls of BoxMissMetric with a TBOX
which raises an assertion there (b == 0).
=> Fix assertion caused by access to default TBOX

src/training/validate_grapheme.cpp, src/training/validate_javanese.cpp
Added rule from https://github.com/topherseance/tesseract/commit/38cdef0d5fa9679f51ffe6051e663de8483f49c6
and
changed some more char classes
=> Javanese Virama and pre-base vowel fix

unittest/Makefile.am, unittest/applybox_test.cc
It needs an update of the test submodule.
The tests only pass with a small modification of the ground truth texts
(kTruthTextWords, kTruthTextLine).
=> unittest: Fix and enable applybox_test

unittest/apiexample_test.cc, unittest/loadlang_test.cc
since they take long to run and/or need all three tessdata repositories.
They can be forced to run by --gtest_also_run_disabled_tests argument.
=> DISABLE some tests 

cppan.yml
As far as I can tell the "official" cppan builds are fine, but when building from source, openmp wasn't working.
=> Fix typo in cppan.yml affecting /openmp

src/viewer/svutil.cpp
One of them was reported in issue #1843.
=> Remove duplicate include statements

src/ccutil/params.cpp
Wrong or old parameters in traineddata files should not terminate
the program, so make that a warning instead of a fatal error.
This fixes issue #1520.
=> Don't call exit when parameter in file is unknown

src/ccutil/errcode.cpp
The error message "segmentation fault" confuses most users,
so enforce a segmentation fault only in debug code.
Release code simply calls the abort function.
=> Don't trigger a deliberate SIGSEGV for fatal errors in release code

src/textord/makerow.cpp
Only print "Merging rows..." if textord_debug_blob==true (like all the other debug messages).
Otherwise, there are a lot of "Merging rows..." messages in console output.
=> Minor: Only print "Merging rows..." in debug mode

src/api/tesseractmain.cpp
While orientation and script detection (OSD) normally requires
osd.traineddata to detect both, it must also be possible to do
only orientation detection with eng.traineddata or any other
traineddata.
Enforce osd.traineddata only if there was no `-l` command line option.
Commit 27ce472666a6332f38888cd6855e1162fb82c729 was too restrictive.
=> Allow orientation detection with any traineddata

tessdata/configs/unlv
Setting the page segmentation mode to 6 ("Assume a single uniform block
of text") typically improves the layout detection for such texts, but
should not be done in the config file.
unlvtests/runtestset.sh adds `--psm 6` explicitly, so test results
won't change when using that script.
This is similar to commit ecfee53bac59e5467f8a8fb5026928a1d39b5c6d.
=> Don't set page segmentation mode for unlv config

doc/tesseract.1.asc
Clarify also the name(s) of the generated OCR result file(s):
Tesseract does not create a file named outbase.txt by default.
Fix also a sentence in the language section.
=> Document some more config options for tesseract

src/training/combine_tessdata.cpp, src/training/lstmtraining.cpp
This is done by creating a temporary file.
Report an error and terminate if that fails.
Use also EXIT_SUCCESS and EXIT_FAILURE for the return values of main().
=> combine_tessdata, lstmtraining: Check for write failures

src/training/lstmtraining.cpp
The purified model name `model_output` was unused,
so remove the comment and the unused code.
=> lstmtraining: Remove dead code for purified model name

src/api/baseapi.h, src/dict/dict.cpp, src/dict/dict.h, src/dict/permdawg.cpp, src/lstm/recodebeam.cpp, src/wordrec/language_model.cpp
=> Fix use of wrong UNICHARSET

src/dict/dict.cpp
wildcard_unichar_id_, apostrophe_unichar_id_, question_unichar_id_ and
slash_unichar_id_ were not initialized in the constructor.
slash_unichar_id_ was used later in a conditional.
=> Fix constructor for class Dict (uninitialized member variables)

src/classify/adaptmatch.cpp
Orientation and script detect only worked with legacy models
and crashed with LSTM models.
=> Avoid crash with --psm 0 and LSTM traineddata

src/ccmain/paragraphs.cpp, src/ccutil/scanutils.cpp, src/wordrec/params_model.cpp
isspace() must only used with an unsigned char or EOF argument,
and even then its result can depend on the current locale settings.
While this is not a problem for C/C++ executables which use the default
"C" locale, it becomes a problem when the Tesseract API is called from
languages like Python or Java which don't use the "C" locale.
By calling isasci() before calling isspace() this uncertainty can be
avoided, because any locale will hopefully give identical results for
the basic ASCII character set.
=> Always use isascii() with isspace()

unittest/Makefile.am
This fixes warnings from autogen.sh.
=> unittest: Disable build rules for tests which still fail to build

unittest/Makefile.am
I build with the following configure options:
./configure --enable-openmp --disable-debug --disable-opencl --disable-graphics 
and needed to add leptonica libs for the program to build.
=> Add Leptonica lib for baseapi_test

src/api/tesseractmain.cpp
Showing them in a window (default) is not acceptable for a console
application like Tesseract which must be able to work in batch mode.
Such error messages can be triggered by TIFF files which include
vendor specific tags.
=> win32: Show TIFF errors on console

src/training/combine_tessdata.cpp, src/training/lstmtraining.cpp
This PR adds the missing header includes for recently added errno code in a couple of training modules.
=> Add missing cerrno includes - fixes #1986

.lgtm.yml
LGTM runs "make" by default, so training files are not checked.
This should be fixed by this configuration file.
=> Add configuration for LGTM

src/training/commontraining.cpp
This fixes two warnings from LGTM:
Parameter feature_defs hides a global variable with the same name.
Parameter Config hides a global variable with the same name.
=> training: Don't hide global variables

src/api/baseapi.cpp
=> Fix use of undefined macro USE_DEVICE_SELECTION

src/viewer/svutil.cpp
The format string which builds the command only takes one or two
string arguments, so the function allocated too much memory and
passed too many arguments to snprintf.
This also fixes a compiler warning (clang).
=> Fix function ScrollViewCommand

src/training/language-specific.sh, src/training/tesstrain_utils.sh
Since `set -u ` has been introduced in `tesstrain_utils.sh` several unbound variable errors have occured when using `tesstrain.sh`.
This PR assigns empty default values to several variables to avoid these errors.
=> fix unbound variables errors

src/training/tesstrain_utils.sh
set TESSDATA_PREFIX as empty, if not defined in environment to avoid an
unbound variable
=> avoid unbound variable TESSDATA_PREFIX in tesstrain_utils.sh

src/api/baseapi.cpp, src/api/baseapi.h
TessBaseAPI::GetAvailableLanguagesAsVector returned the list of languages
without sorting, so the result was random and not user friendly.
Now `tesseract --list-langs` shows the available languages and scripts
in alphabetic order.
=> Get sorted list of available languages

src/api/tesseractmain.cpp
Commit 49d7df6dc3efc61861c783021e06567d3d4780f0 introduced a memory leak
when the output file could not be created.
=> tesseractmain: Fix memory leak

src/ccutil/tesscallback.h
Compiler warning on macOS:
tesscallback.h:29:7: warning:
'TessClosure' has no out-of-line virtual method definitions;
its vtable will be emitted in every translation unit [-Wweak-vtables]
=> Fix compiler warning

src/training/tesstrain_utils.sh
The commit 10f2c45c00 unified the usage of mktemp, but with a
incorrect bash syntax and unnecessary definition of LANG_CODE
and TIMESTAMP. This patch fixes the above problems.
=> Fix mktemp in tesstrain_utils.sh

src/training/language-specific.sh
=> Fix unbound variable $FONTS

ccutil/scanutils.cpp
The local variable k should be 10 ^ (number of digits after comma),
but will overflow when there are more than 9 digits after the comma
because an int value cannot store 10000000000.
This results in wrong double values read from .tr files for example
(or in a runtime exception if Tesseract was compiled with -ftrapv).
Using uint64_t does not fix the general problem but allows more digits
which should be sufficient for the data read by Tesseract.
=> Fix wrong results from function streamtofloat

src/ccutil/errcode.cpp, src/ccutil/scanutils.cpp, src/ccutil/unicharset.cpp, src/cutil/bitvec.cpp, src/cutil/callcpp.cpp, src/dict/context.cpp, src/lstm/functions.h, src/lstm/maxpool.cpp, src/lstm/networkscratch.h, src/lstm/reconfig.cpp, src/lstm/stridemap.h, src/training/commandlineflags.cpp, src/training/commandlineflags.h, unittest/matrix_test.cc
Format also a call of tprintf and add a missing explicit include statement.
=> Remove unused include statements for tprintf.h

configure.ac
Library rt is included in the libc on Android: https://developer.android.com/ndk/guides/stable_apis#a3
=> fix(configure) Don't add rt on Android

.gitignore, src/training/language_specific.py, src/training/tesstrain.py, src/training/tesstrain_utils.py
After attempting to chase down an error in tesstrain.sh I ended up converting to tesstrain.sh to Python. I also see interested was expressed by others in this conversion in #1503.
Only LSTM is converted right now. I have not done this work for the Tesseract 3 portions of training because IIRC, the old 3.x engine might get scrapped. If there's a need I can convert that too; the process is pretty mechanical. 
Python 3.6+ is required, which also ships with Ubuntu 18.04 and is always installed. I need Python 3.6 for its improved string substitution - this makes it follow the bash version more closely,
I attempted to keep source changes minimal so it would be easier to compare
bash to Python in code review and confirm equivalence. The first commit is structured so it's somewhat easier to …
=> RFC: Pythonize tesstrain.sh and friends

src/arch/Makefile.am
This reduces the code size for intsimdmatrixavx2 from 2700 to 2668
and slightly improves the performance for fast models with AVX2.
=> Use -ffast-math for calculation of dot product

src/api/Makefile.am, src/api/tesseractmain.cpp, src/arch/Makefile.am, src/arch/dotproduct.cpp, src/arch/dotproduct.h, src/arch/simddetect.cpp, src/arch/simddetect.h, src/lstm/weightmatrix.cpp, src/lstm/weightmatrix.h
All also a C++ implementation with more aggressive compiler options
which is optimized for the CPU where the software was built.
It is now possible to select the function used for the dot product
with -c dotproduct=FUNCTION where FUNCTION can be one of those values:
* auto      selection based on detected hardware (default)
* generic   C++ code with default compiler options
* native    C++ code optimized for build host
* avx       optimized code for AVX
* sse       optimized code for SSE
=> Add config variable for selection of dot product function

src/api/altorenderer.cpp
Using std::stringstream simplifies the code.
The <SP> element is needed between two >String> elements.
Remove also some unneeded spaces in the ALTO output.
=> Use std::stringstream to generate ALTO output and add <SP> element

CMakeLists.txt, src/arch/Makefile.am, src/arch/dotproductavx.cpp, src/arch/dotproductsse.cpp, src/arch/simddetect.cpp
The tests for SSE and AVX must only be done if the correct compiler
flags were used.
=> Fix and simplify SIMD tests

CMakeLists.txt
I tried building this on android-ndk-r18b and platform android-28 and got an error in the linking step.
Abbreviated:
```
... && :
/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lpthread
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
The command '/bin/sh -c ninja -j6' returned a non-zero code: 1
make: *** [tesseract-armv7-a/4.0.0] Error 1
```
Since pthreads is part of Bionic on Android, it has to be left out explicitly.
=> Avoid linking pthread on Android

src/classify/protos.cpp, src/training/commontraining.h
A couple of places where headers should have been included.
I found these while updating my simplemakev4 branch to build tesseract with make.
protos.cpp needs intproto.h for MAX_NUM_PROTOS.
commontraining.h needs to always use baseapi.h, as otherwise most training binaries won't build, and it doesn't rely on the HAVE_CONFIG_H it's ifdef-ed around.
=> Fix headers

src/opencl/oclkernels.h, src/opencl/openclwrapper.cpp
The OpenCL kernel pixSubtract is never used, so remove it.
=> OpenCL: Remove unused code

doc/tesseract.1.asc, src/api/tesseractmain.cpp
It never worked, so add a comment that the implementation is missing.
Add also a to-do comment.
=> Fix documentation for page segmentation mode 2

unittest/Makefile.am, unittest/unichar_test.cc, unittest/unicharset_test.cc
unichar_test still getting error
unichar_test.cc: In member function ‘virtual void {anonymous}::UnicharTest_Conversion_Test::TestBody()’:
unichar_test.cc:24:21: error: ‘char32’ was not declared in this scope
const std::vector<char32> kUTF32Src = {'a', 0x5d0, 0xca4, 0x2a714};
^~~~~~
unichar_test.cc:24:21: note: suggested alternative:
In file included from unichar_test.cc:12:0:
../src/ccutil/unichar.h:52:26: note:   ‘tesseract::char32’
using char32 = signed int;
^
=> Fixes unicharset_test

unittest/Makefile.am, unittest/include_gunit.h, unittest/unicharcompress_test.cc, unittest/unicharset_test.cc
@stweil Please review and fix.
Still getting the following errors:
unicharcompress_test.cc: In member function ‘virtual void tesseract::{anonymous}::UnicharcompressTest_GetEncodingAsString_Test::TestBody()’:
unicharcompress_test.cc:242:15: error: ‘string’ was not declared in this scope
std::vector<string> lines =
^~~~~~
unicharcompress_test.cc:242:15: note: suggested alternatives:
In file included from /usr/include/c++/6/string:39:0,
from unicharcompress_test.cc:12:
/usr/include/c++/6/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
typedef basic_string<char>    string;
^~~~~~
/usr/include/c++/6/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
In file included from ../googletest/googletest/include/gtest/internal/gtest-internal.h:40:0,
from …
=> Fix for unicharcompress_test

src/arch/simddetect.cpp
Commit d36231e3e4ddc9a6aa23e490f04678110cb1714d did not distinguish
between AVX and AVX2, so AVX2 code was enabled for IntSimdMatrix
even when only AVX was supported.
This resulted in an illegal instruction.
=> Fix selection of IntSimdMatrix method

src/arch/simddetect.cpp, unittest/Makefile.am, unittest/dawg_test.cc, unittest/layout_test.cc, unittest/mastertrainer_test.cc
@stweil Please review. Still getting build errors.
layout_test.cc: In member function ‘void {anonymous}::LayoutTest::VerifyTotalContainment(int, tesseract::MutableIterator*)’:
layout_test.cc:132:47: error: invalid use of incomplete type ‘class BLOCK’
POLY_BLOCK* pb = pr_it->block()->block->poly_block();
^~
In file included from ../src/ccstruct/blamer.h:26:0,
from ../src/ccstruct/pageres.h:27,
from layout_test.cc:12:
../src/ccstruct/boxword.h:26:7: note: forward declaration of ‘class BLOCK’
class BLOCK;
^~~~~
layout_test.cc:134:44: error: invalid use of incomplete type ‘class BLOCK’
FCOORD skew = pr_it->block()->block->skew();
^~
In file included from ../src/ccstruct/blamer.h:26:0,
from ../src/ccstruct/pageres.h:27,
from layout_test.cc:12:
../src/ccstruct/boxword.h:26:7: note: forward …
=> Fix layout_test and dawg_test

unittest/dawg_test.cc
Get unicharset and wordlist files from test/testing and use the latest
test submodule which provides those files.
=> Update file paths in dawg_test

src/training/tesstrain.sh
It seems that to decide whether to run phase S or not, tesstrain.sh was checking if ENABLE_SHAPE_CLUSTERING variable was set to "y". However, this variable is unbound, and the script fails when it reaches this point.
It looks like whether to run shape clustering or not is decided with the --run_shape_clustering flag, which is checked in the tesstrain_utils.sh script instead.
Therefore, it seemed to me that removing this if statement from tesstrain.sh seemed appropriate to solve this bug.
=> tesstrain.sh was failing with line 81: ENABLE_SHAPE_CLUSTERING: unbound variable

src/api/baseapi.cpp
Commit 5fe1390748a15c0e445a5c57c834edff27ff2f4d used an implementation
which created a new Pix object. That object was never destroyed.
=> Fix memory leak for PNG images

unittest/Makefile.am, unittest/include_gunit.h, unittest/log.h, unittest/lstm_recode_test.cc, unittest/lstm_squashed_test.cc, unittest/lstm_test.cc, unittest/lstm_test.h, unittest/tmp/README.md
I will upload required testdata files to the test repo.
=> Fix and enable lstm related unittests

configure.ac
It wrongly detects old versions of ICU as valid.
Checking with pkg-config is sufficient and also sets ICU_UC_LIBS.
=> configure: Remove header check for ICU

doc/generate_manpages.sh
xsltproc will use the system catalog to find the local path.
Pass --nonet option to ensure the Internet is not used.
---
docbook.xsl isn't in the same location on all distributions e.g. on Fedora (symlink) and Gentoo Linux is at:
/usr/share/sgml/docbook/xsl-stylesheets/manpages/docbook.xsl
=> Use universal location for docbook.xsl

doc/Makefile.am
This is similar to commit 2106cba0a98a90451df835f3ab7b2aaf54826442
which fixed doc/generate_manpages.sh.
=> Fix build rule for manpages

src/lstm/functions.cpp, src/lstm/functions.h
Both functions are called very often, so computing the table values
at program start should be faster than computing them on demand.
=> Simplify tanh and logistic functions and precompute function tables

doc/Makefile.am
=> Avoid gmake-specific pattern substitution in Makefile.am.

configure.ac, doc/Makefile.am
* Don't try the build if xsltproc is missing.
* Don't abort the build if the stylesheet file is missing.
=> Improve robustness of manpage build

src/lstm/input.cpp
Images with width == min_width are not too small.
=> Fix check for images which are too small to scale

CMakeLists.txt, src/api/Makefile.am, src/api/baseapi.h, src/api/renderer.h, src/api/tesseractmain.cpp, src/api/wordstrboxrenderer.cpp, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h, tessdata/configs/wordstrbox
@thebigwasp provided an example of WordStr box file that works in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/tesseract-ocr/0r8QvV3j8ew/5oYrCY5_AAAJ
This PR implements it.
=> Add renderer to create WordStr box files from images

doc/tesseract.1.asc
Three commits here, first two should be straightforward:
* get.image is mentioned in tesseract(1), as get.images and not installed
* A typo and missing full stops in tesseract(1)
At first read of tesseract(1) I didn't find it easy to follow what a config was and the third commit is my attempt to improve that. That's more subjective so please do look at it critically.
=> Man page description of configs and parameters

src/arch/dotproductavx.cpp
This improves the performance with best models and should also
make training faster.
=> Optimize calculation of dot product for double vectors with AVX

src/training/degradeimage.cpp, src/training/text2image.cpp
Fixes https://github.com/tesseract-ocr/tesseract/issues/1052
=> implement PrepareDistortedPix as part of DegradeImage

src/training/validate_grapheme.cpp
Fixes errors such as:
Word started with a combiner:0x64b
Normalization failed for string 'ًا'
Encoding of string failed! Failure bytes: d9 8b d8 a7 d8 af d9 83 d8 a4 d9 85 db 94 d8 a9 d9 8a d8 b1 d8 a7 d8 af d8 a7 d9 84 d8 a7 20 d8 a9 d8 a6 d9 8a d9 87 d9 84 d8 a7 20 d8 a1 d8 a7 d8 b6 d8 b9 d8 a3 d8 a8 20 d8 a9 d9 82 d8 ab d9 84 d8 a7 20 d8 af d9 8a d8 af d8 ac d8 aa
Can't encode transcription: 'نا ًادكؤم۔ةيرادالا ةئيهلا ءاضعأب ةقثلا ديدجت' in language ''
=> Remove test for Word started with a combiner

src/training/validate_grapheme.cpp
(using the c preprocesor). Thanks @amitdo
https://github.com/tesseract-ocr/tesseract/pull/2268#pullrequestreview-207605382
=> Use alternative way to comment a block of code 

src/api/baseapi.cpp
It behaves same in scanf, but it allows proper handling of unicode
chars.
=> Allow UTF-8 variant of C locale

src/ccstruct/pageres.h, src/training/boxchar.cpp
https://www.w3.org/International/articles/inline-bidi-markup/uba-basics#numbers
> Numbers in RTL scripts run left-to-right within the right-to-left flow.
See earlier discussion in the closed PR - https://github.com/tesseract-ocr/tesseract/pull/2266
The change to ccutil/unicharset.cpp which was in earlier PR is NOT included, since U_ARABIC_NUMBER was being used there as part of condition to find if right_to_left scripts are significant in the unicharset.
https://github.com/tesseract-ocr/tesseract/blob/master/src/ccutil/unicharset.cpp#L956
=> Treat U_ARABIC_NUMBER as LTR

src/training/validate_indic.cpp
Fixes errors such as
Extracting unicharset from box file /tmp/tam-2019-03-01.pSD/tam.Noto_Sans_Tamil_Regular.exp0.box
Invalid start of grapheme sequence:D=0xbf0
Normalization failed for string '௰'
Invalid start of grapheme sequence:D=0xbf1
Normalization failed for string '௱'
Invalid start of grapheme sequence:D=0xbf2
Normalization failed for string '௲'
Invalid start of grapheme sequence:D=0xbf3
Normalization failed for string '௳'
Invalid start of grapheme sequence:D=0xbf0
Normalization failed for string '௰'
=> correct handling of 0BF0-0BFA Tamil numbers and symbols

src/ccstruct/pageres.cpp, src/ccstruct/pageres.h
Avoiding a function call will make both == and != operator faster.
=> PAGE_RES_IT: Optimize compare operators by using inline code

.travis.yml, configure.ac, src/api/Makefile.am, src/ccutil/Makefile.am, src/ccutil/tessdatamanager.cpp, src/ccutil/tessdatamanager.h, src/training/Makefile.am
This requires libarchive-dev.
Tesseract can now load traineddata files in any of the archive formats
which are supported by libarchive. Example of a zipped BagIt archive:
$ unzip -l /usr/local/share/tessdata/zip.traineddata
Archive:  /usr/local/share/tessdata/zip.traineddata
Length      Date    Time    Name
---------  ---------- -----   ----
55  2019-03-05 15:27   bagit.txt
0  2019-03-05 15:25   data/
1557  2019-03-05 15:28   manifest-sha256.txt
1082890  2019-03-05 15:25   data/eng.word-dawg
1487588  2019-03-05 15:25   data/eng.lstm
7477  2019-03-05 15:25   data/eng.unicharset
63346  2019-03-05 15:25   data/eng.shapetable
976552  2019-03-05 15:25   data/eng.inttemp
13408  2019-03-05 15:25   data/eng.normproto
4322  2019-03-05 15:25   data/eng.punc-dawg
4738  2019-03-05 15:25 …
=> Add initial support for traineddata files in standard archive formats

doc/tesseract.1.asc
Useful for custom config or when pointing tessdata to alternate
traineddata.
=> Document that configfile can be a file path

src/dict/dict.h, src/wordrec/language_model.cpp
Credit to OSS-Fuzz:
This fixes a security issue which was reported by OSS-Fuzz, see details at
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13590.
Add also some assertions to catch similar bugs.
=> Fix Heap-buffer-overflow in GenericVector<int>::size (issue #2298)

src/ccmain/ltrresultiterator.cpp
in case a ChoiceIterator is used without `lstm_choice_mode`, tesseract crashes (or similar) because the check is true and we reference not existing item
=> `accumulated_timesteps` is not a pointer but a vector

src/api/Makefile.am
On MinGW with MSYS2 environment, it fails to build libtesseract.dll.a 
due to undefined reference to libarchive function.
this PR adds libarchive linker flags explicitly.
=> Added missing linker flags for MinGW.

src/ccmain/osdetect.cpp, src/ccmain/pgedit.cpp, src/ccstruct/blobbox.cpp, src/ccutil/errcode.h
The modified definition avoids warnings caused by redundant semicolons.
Now a semicolon is required when using the macro, so a few code locations
had to be updated.
=> Fix compiler warnings caused by ASSERT_HOST

src/ccmain/tessedit.cpp, src/ccutil/params.h, src/dict/dict.cpp, src/lstm/lstmrecognizer.cpp, src/lstm/lstmrecognizer.h
- pass in `ParamsVectors` from `Tesseract`
(carrying values from langdata/config/api)
into `LSTMRecognizer::Load` and `LoadDictionary`
- after `LSTMRecognizer`'s `Dict` is initialised
(with default values), reset the variables
user_{words,patterns}_{suffix,file} from the
corresponding entries in the passed vector
=> trying to add user words/patterns again:

src/ccstruct/imagedata.cpp
The pages variables refer to the lines in document. This change makes the messages clearer without changing the variable names.
=> Change pages to lines in message

src/lstm/lstmtrainer.cpp
```
Iteration 3282: ALIGNED TRUTH : including just place 18 service Articles as could these Community to link them Forum most 0
Iteration 3282: GROUND  TRUTH : including just place 18 service Articles as could these Community to link them Forum most 0
Iteration 3282: BEST OCR TEXT : including just place 18 service Articles as could these Community to 1ink them Forum most 0
File /tmp/eng-2019-03-30.Lcy/eng.Cousine.exp0.lstmf page 41 :
Mean rms=0.346%, delta=0.157%, train=0.512%(1.009%), skip ratio=0%
Iteration 3283: ALIGNED TRUTH : first 27 then 2.100 they FIG. 1 (GeneRIF) World and ABOUT time October the service through
File ./engrestrict/eng.Cutive_Mono.exp0.lstmf page 54 (Perfect):
Mean rms=0.346%, delta=0.157%, train=0.512%(1.009%), skip ratio=0%
Iteration 3284: ALIGNED TRUTH : for , …
```
=> Change message display for debug_level -1 during lstmtraining

CONTRIBUTING.md, src/ccmain/tesseractclass.cpp, src/ccutil/unicharset.h, src/lstm/recodebeam.cpp, src/lstm/recodebeam.h, src/training/tesstrain_utils.sh
- ignore matrix outputs in ComputeTopN if they
belong to a disabled unichar_id
- pass UNICHARSET refs to check that
- in SetBlackAndWhitelist, also update the unicharset
of the lstm_recognizer_ instance, if any
=> trying to add tessedit_char_whitelist etc. again:

src/ccutil/genericvector.h
LoadDataFromFile/SaveDataToFile use fopen with unsupported file mode 'e' in MSVC.
=> Fix for MSVC

src/wordrec/params_model.cpp, src/wordrec/params_model.h, unittest/Makefile.am, unittest/params_model_test.cc
This needs the latest test submodule.
The test uses LoadFromFile which is not used otherwise, so remove that
function from class ParamsModel.
=> unittest: Fix and enable params_model_test

src/ccstruct/boxread.cpp, src/ccutil/params.cpp, src/ccutil/scanutils.h
Using std::stringstream allows working with the C locale, independent
of the current locale settings.
=>  Replace sscanf by std::stringstream

src/ccutil/params.cpp, src/ccutil/platform.h
This partially reverts commit c150b9832d7d07761ec7869a625e6c46ba62206a.
Now params.cpp includes host.h which also gets the definition for MAX_PATH.
=> Don't include windows.h from platform.h

src/api/wordstrboxrenderer.cpp
This reverts one of the changes made in commit https://github.com/tesseract-ocr/tesseract/commit/f47c7c92dd5c30af98861dad07e13b7690291454
Incorrect boxfile
```
WordStr 44 521 1493 622 0 #॥ इति श्रीरामरहस्योक्ता श्रीहनुमदष्टोत्तशतनामावळिः ॥
941 433 945 491 0
WordStr 646 433 940 491 0 #॥ समाप्ता ॥
1310 273 1314 357 0
WordStr 344 273 1309 357 0 #॥ श्रीरामभक्तिकल्पलता समाप्ता ॥
889 222 893 249 0
WordStr 627 222 888 249 0 #० - ----- - ०
1090 119 1094 211 0
WordStr 338 119 1089 211 0 #असुकरलाभैर्ग्रन्थैरमुद्रितै रद्ययावदतिरस्यैः ।
1171 79 1175 177 0
WordStr 118 79 1170 177 0 #महिततनुवर्हतु मुदं मनसि सतां रामभक्तिकल्पलता ॥
1422 0 1426 99 0
WordStr 119 0 1421 99 0 #
1422 0 1426 99 0
```
Note the duplication of the coordinates for EOL on the last line and line before that. `	 1422 0 1426 99 0` …
=> fix the coordinates for EOL tab

src/ccutil/universalambigs.cpp
This allows fixing two compiler warnings from clang++:
src/ccutil/universalambigs.cpp:23:19: warning: no previous extern declaration for non-static variable 'kUniversalAmbigsFile' [-Wmissing-variable-declarations]
src/ccutil/universalambigs.cpp:19019:18: warning: no previous extern declaration for non-static variable 'ksizeofUniversalAmbigsFile' [-Wmissing-variable-declarations]
=> universalambigs: Add missing include file

configure.ac
./configure did not set CPPFLAGS correctly on macOS due to problems with how CPPFLAGS were being set.
This caused build issues like missing `<archive.h>`
=> Fix CPPFLAGS configuration for icu4c and libarchive

src/classify/clusttool.cpp
The NonEssential parameter was wrongly derived from linear_token instead
of essential_token and therefore always set to true.
=> Fix reading of parameter from traineddata normproto component and make function independent of locale

configure.ac
AX_CHECK_COMPILE_FLAG fails if it is used with -Werror and the compiler
raises error -Wunused-macros. Add -Wno-unused-macros to disable those
errors if possible.
Simplify also the setting of several conditionals (AVX, AVX2, ...).
=> configure: Fix for latest developer tools on macOS

src/api/baseapi.cpp, src/ccutil/unicharset.cpp, src/classify/normmatch.cpp
The unittest failed with LANG=de_DE.UTF-8:
$ unittest/apiexample_test
Running main() from ../../../../unittest/../googletest/googletest/src/gtest_main.cc
[==========] Running 4 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 1 test from EuroText
[ RUN      ] EuroText.FastLatinOCR
contains_unichar_id(unichar_id):Error:Assert failed:in file ../../../../../src/ccutil/unicharset.h, line 874
=> Fix some unittests with locale de_DE.UTF-8

src/api/hocrrenderer.cpp
These classes are taken from the hOCR specification, and seem
to map well onto the BlockType types. There are probably more that
could be added.
Note that I haven't read the hOCR specification closely, so there's a
chance I misunderstood something. @kba, can you take a look and
check that the hOCR produced is valid and sensible?
=> Add different classes to hocr output depending on BlockType

unittest/baseapi_test.cc
Linker error reported in issue #2439:
unittest/baseapi_test.cc:190:
undefined reference to
`tesseract::TessBaseAPI::AdaptToWordStr(tesseract::PageSegMode, char const*)'
=> Fix linker error for baseapi_test when building without legacy engine

src/ccmain/pgedit.cpp, src/ccstruct/linlsq.cpp, src/ccstruct/pdblock.cpp, src/ccstruct/werd.cpp, src/ccutil/clst.cpp, src/ccutil/elst.cpp, src/ccutil/elst2.cpp, src/ccutil/errcode.cpp, src/ccutil/errcode.h, src/ccutil/fileerr.h, src/ccutil/lsterr.h, src/textord/edgloop.cpp
This fixes lots of warnings related to ERRCODE like the following one:
src/ccutil/errcode.h:81:15: warning:
declaration requires a global constructor [-Wglobal-constructors]
=> Fix compiler warnings

src/api/baseapi.cpp, src/ccstruct/points.cpp, src/ccutil/platform.h, src/classify/cluster.cpp, src/classify/clusttool.cpp, src/classify/fpoint.cpp, src/classify/intfeaturespace.cpp, src/classify/intfx.cpp, src/classify/intproto.cpp, src/classify/mfx.cpp, src/classify/protos.cpp, src/classify/trainingsample.cpp, src/textord/baselinedetect.cpp, src/textord/tordmain.cpp, src/training/commontraining.cpp, src/training/mergenf.cpp, src/training/mftraining.cpp, src/wordrec/chop.cpp
It is defined for all platforms when math.h or cmath is included
after defining the macro _USE_MATH_DEFINES.
Define _USE_MATH_DEFINES before any include statement to make sure
that M_PI gets defined. It is not necessary to define it conditionally
only for Windows.
=> Remove local definition of M_PI

src/classify/trainingsampleset.cpp
Fix bug in `max_max_dist` in `trainingsampleset.cpp`. This follows from https://github.com/tesseract-ocr/tesseract/pull/2451#discussion_r286318784
=> Fix bug in max_max_dist

src/api/baseapi.cpp, src/api/baseapi.h, src/ccmain/reject.cpp, src/ccutil/errcode.cpp, src/ccutil/globaloc.cpp, src/ccutil/globaloc.h
That debugging code uses very much memory and is no longer useful.
text	   data	    bss	    dec	    hex	filename
815	      0	 262144	 262959	  4032f	src/ccutil/globaloc.o
Remove also the function err_exit which was only used in ccmain/reject.cpp.
=> Remove SavePixForCrash and related code

src/ccutil/tprintf.cpp
Reduce the maximum message size from 64 KiB to 2 KiB which still should
be large enought for trace messages.
Create the smaller message on the stack instead of using a global
array to allow reentrancy and to reduce the memory use of Tesseract.
=> tprintf: Make code reentrant and use less memory

configure.ac
This prevents a link error on OpenBSD:
```
warning: could not find a rt library
Link error: rt not found!
```
=> Do not link librt on OpenBSD

configure.ac
This allows using new features of C++17 conditionally.
Simplify also the code which checks and sets the C++ version.
=> Use C++17 compiler if possible

CMakeLists.txt
First of all do not use -Xclang -fopenmp, just use -fopenmp as this feature is stable so long now. Also on UNIX you'll need to link to pthread to get OpenMP link correctly.
=> Fix OpenMP builds on Unix

src/training/text2image.cpp
C++17 drops support for `std::random_shuffle`, breaking C++17 compilers that run to compile text2image.cpp. std::shuffle is valid on C++11 through C++17, so use std::shuffle instead.
=> Fix text2image compilation on C++17 compilers

src/training/text2image.cpp
C++17 drops support for `std::random_shuffle`, breaking C++17 compilers
that run to compile text2image.cpp. std::shuffle is valid on C++11
through C++17, so use std::shuffle instead.
Due to the use `std::random_shuffle`, `text2image --render_ngrams`
would not give consistent results for different compilers or platforms.
With the current change, the same random number generator is used for
all platforms and initialized to the same seed, so training output
should be consistent.
=> [4.1] Fix text2image compilation on C++17 compilers

src/ccstruct/Makefile.am, src/ccstruct/blamer.cpp, src/ccstruct/blamer.h, src/ccutil/tesscallback.h, src/wordrec/lm_pain_points.h, src/wordrec/segsearch.cpp
It does neither need a temporary TessResultCallback2 nor the function
LMPainPoints::GenerateForBlamer.
This also allows removing more code from tesscallback.h.
=> Simplify indirect call of LMPainPoints::GeneratePainPoint

src/ccutil/tesscallback.h, src/lstm/lstmtrainer.cpp, src/lstm/lstmtrainer.h, src/training/lstmtraining.cpp, unittest/lstm_test.h
The function pointers and callbacks file_reader_, file_writer_,
checkpointer_reader_ and checkpoint_writer_ are always set to
the same values. Replacing them by direct function calls
simplifies the code and allows removing more code from tesscallback.h.
=> Simplify class LSTMTrainer

CMakeLists.txt
export variable for this commit https://github.com/tesseract-ocr/tesseract/commit/d171488e211f7494c909984a4f0e0dbdd898af78 
when build with cmake-gui  will see clarity
=> export USE_SYSTEM_ICU viriable

src/ccmain/control.cpp
This
https://github.com/tesseract-ocr/tesseract/blob/d8494f3215c107308467c961fec05e1bf04dbe0e/src/ccmain/control.cpp#L1394
invalidates `word` pointer
=> Fix crash in Tesseract::classify_word_and_language()

CMakeLists.txt
This commit points CMAKE_CXX_STANDARD to the latest non-experimental standard.
CMake announces C++14 and C++17 support even if the
compiler supports it only experimentally (c++1y and c++1z).
It breaks cmake standard detection and requires workarounds
for old compilers.
It heals build on clang 3.9, 4.0, gcc 4.8 and possible for other compilers.
=> Avoid using experimental C++14/17 support in CMake

src/ccutil/ccutil.cpp, src/ccutil/ccutil.h, src/ccutil/tprintf.cpp
It no longer uses a local buffer, so it needs less memory
and no mutex.
=> Optimize tprintf implementation

src/api/hocrrenderer.cpp, src/ccmain/linerec.cpp, src/ccmain/ltrresultiterator.cpp, src/ccmain/ltrresultiterator.h, src/ccmain/resultiterator.cpp, src/ccmain/resultiterator.h, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h, src/ccstruct/pageres.h, src/lstm/lstmrecognizer.cpp, src/lstm/lstmrecognizer.h, src/lstm/recodebeam.cpp, src/lstm/recodebeam.h
Added an improved version of the lstm_choice_mode 
The new version extracts its ratings and alternative symbol choices from the
CTC process instead of the lattice. It also makes the beamsearch broader in
an uninvasive way by doing several cascading beamsearches. After every iteration
the best symbol choice is extracted and blocked for the next iteration.
=> Improved lstm_choice_mode

src/classify/protos.cpp, src/cutil/bitvec.cpp, src/cutil/bitvec.h
The vector was already limited to MAX_NUM_PROTOS (512) entries or 64 bytes
in the old code. Now it uses that size right from the start which avoids
reallocating it later when entries are added.
The old code which reallocated the vector to expand it was buggy because
the realloc function can return a different pointer, but the code still
used the original pointer to reset the new bits.
Function ExpandBitVector is now unused and therefore removed.
=> classify: Use fixed size bit vector

src/lstm/recodebeam.cpp
The algorithm is using the new character bounding boxes which were calculated
to create better symbol choices for the lstm_choice_mode.
=> Implemented improved character bounding box algorithm

src/ccutil/unicharset.cpp, src/ccutil/unicharset.h, unittest/recodebeam_test.cc, unittest/unicharcompress_test.cc
The method was only used in unittest where it can be replaced by
UNICHARSET::load_from_file which also simplifies the code.
This allows removing the class InMemoryFilePointer and fixes a TODO.
=> Remove UNICHARSET::load_from_inmemory_file and related code

src/api/hocrrenderer.cpp, src/ccmain/linerec.cpp, src/ccmain/ltrresultiterator.cpp, src/ccmain/ltrresultiterator.h, src/ccmain/resultiterator.cpp, src/ccmain/resultiterator.h, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h, src/ccstruct/pageres.h, src/lstm/lstmrecognizer.cpp, src/lstm/recodebeam.cpp, src/lstm/recodebeam.h
Overhaul of the lstm_choice_mode
- Made the `lstm_choice_mode` compatible with `hocr_char_boxes`.
- Improved the choice mode algorithm to increase the performance.
- Cut down the different modes to the two essentiell ones.
- `lstm_choice_mode`=1 returns the timesteps segemented by character. This replaces mode 1 and 3 with no loss of information.
- `lstm_choice_mode`=2 returns alternative choices per character based on the new ctc retrieval algorithm. This replaces mode 2 and 4. The former mode 2 is completely dropped as it worked only for languages with a smaller amount of characters than output channels of the LSTM.
- Renamed `lstm_choice_amount` to `lstm_choice_iterations` because of the misleading title.
=> Lstm choice ril

src/ccmain/osdetect.cpp, src/ccutil/bitvector.cpp, src/ccutil/unicharcompress.h
Those errors can be reproduced by running the unit tests from a build with sanitizers:
./configure '--enable-debug' '--disable-openmp' '--disable-shared' 'CXX=clang++-7' \
'CXXFLAGS=-g -O0 -D_GLIBCXX_DEBUG -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=fuzzer-no-link,address,undefined -fsanitize-address-use-after-scope'
make training check
grep UndefinedBehaviorSanitizer unittest/*log
=> Fix several runtime errors detected by UndefinedBehaviorSanitizer

src/ccmain/control.cpp, src/ccstruct/pageres.cpp, src/ccstruct/pageres.h
This also fixes CID 1405626 and CID 1405627 which were introduced by commit
8ff321e41a5786f399139669ff7a94145749c45a.
=> Remove unused italic, bold in class BLOCK_RES and class WORD_RES

src/ccmain/tessedit.cpp, src/lstm/lstmrecognizer.cpp, src/lstm/lstmrecognizer.h
- add another constructor for LSTMRecognizer
which takes the language_data_path_prefix configured/selected
at runtime and passes it to the internal CCUtil
- use this in Tesseract::init_tesseract_lang_data when LSTMs
are available
(this was missing from 297d7d86ceb3b3365876b56f08a18cba066bf23f)
=> fix langdata (user words/patterns) file suffixes for LSTMs:

configure.ac, src/api/Makefile.am, src/api/baseapi.cpp
This allows OCR of images from the internet without downloading them first:
tesseract http://IMAGE_URL OUTPUT ...
It uses libcurl.
=> RFC: Add support for image or image list by URL

src/api/tesseractmain.cpp
The configuration file lstm.train causes Tesseract to generate
training data for training of an LSTM line recognizer.
In this mode, no other files with OCR results should be written.
Without this patch, Tesseract writes a small text file.
=> Don't create OCR result files when training data is created

src/ccmain/linerec.cpp, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h
Allows for disabling automatic inverting of lines when tesseract feels the inverting could be of help.
=> Optional speed optimisation

src/ccstruct/boxread.cpp, src/ccstruct/boxread.h
The function derives the file name for the .box file from an image name.
For training from existing line images, it is useful to directly support
the image names which are commonly used.
While generated images for Tesseract training typically use the name
pattern NAME.tif, other ground truth sets use NAME.bin.png for binarized
or NAME.nrm.png for grayscale images.
BoxFileName is also now a local function as it is only used locally.
=> Extend function BoxFileName to handle more common image names

src/api/altorenderer.cpp, src/api/baseapi.cpp, src/api/baseapi.h
The title can be set for hOCR and PDF output.
Currently it is also used for ALTO, so setting the title can be used
as a workaround for issue #2700.
The constant unknown_title_ is no longer needed and therefore removed.
=> Add new parameter "document_title" to set the title in OCR output files

src/ccmain/paragraphs.cpp
Environment: Window 10 Home (x64)
Processor: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz 2.71GHz
Memory: 16GB
IDE: Microsoft Visual Studio Community 2019 (Version 16.3.4)
=> Remove warning C4312 (casting integers to pointers)

tessdata/configs/lstm.train
fixes https://github.com/tesseract-ocr/tesseract/issues/2665
`il1_adaption_test` has already been removed by earlier commit.
=> remove legacy parameter disable_character_fragments from lstm.train

src/ccmain/pagesegmain.cpp, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h
I have an image with a very large, lined table where most of the text was being dropped by the FilterMusic function, which was falsely recognizing parts of the table as a music staff.
I have added a new parameter called pageseg_apply_music_mask (default of true to preserve the current behavior) to allow this function to be disabled.
I am a little unsure of the proper name for the parameter so suggestions are welcome.
=> Add pageseg_apply_music_mask option to allow disabling the music mask

src/training/tesstrain_utils.sh
Text2image has the option --ptsize which defaults to 12.  This option is not exposed through
tesstrain.sh; thus, you cannot use tesstrain.sh to explore training with
different font sizes.  I made a small modification to expose the --ptsize
option to tesstrain.sh.  It defaults to 12 if not specified.
=> Exposed the text2image option --ptsize to tesstrain.sh.

Makefile.am, configure.ac, src/api/tesseractmain.cpp
`tesseract --version` now also shows the version of libcurl and related
libraries if it was build with libcurl.
The preprocessor macro HAVE_LIBCURL is now defined in config_auto.h.
=> Show libcurl version

src/ccmain/pageiterator.cpp
Layout analysis delivers segments that often need to be non-rectangular to accomodate close neighbours, image near text, ragged/unaligned lines etc. The CLI builds on the internal, polygon-based data structures, which allow for that without conflicts/overlaps. But API users up until now could only use bounding boxes, because `BlockPolygon` did not deliver correct coordinates:
1. unlike `BoundingBox`, they were not "unrotated" (i.e. the internal deskewing has not been compensated for, giving coordinates widely out of scope)
2. unlike `BoundingBox`, they were not clipped (i.e. forced into the interval of the image/rectangle)
Both issues have been fixed here. 
But there is a third problem that I have not tackled yet: Polygon paths are often self-intersecting or otherwise unusable. This even …
=> make BlockPolygon usable

src/ccstruct/pageres.cpp
clang warnings:
src/ccstruct/pageres.cpp:903:20: warning:
implicit conversion from 'int' to 'float' changes value from
2147483647 to 2147483648 [-Wimplicit-int-float-conversion]
src/ccstruct/pageres.cpp:904:23:
warning: implicit conversion from 'int' to 'float' changes value from
-2147483647 to -2147483648 [-Wimplicit-int-float-conversion]
=> pageres: Fix compiler warnings

include/tesseract/genericvector.h, src/ccmain/control.cpp, src/ccstruct/blamer.cpp, src/ccstruct/blamer.h, src/ccstruct/pageres.cpp, src/dict/dict.cpp, src/dict/permdawg.cpp, src/dict/stopper.cpp, src/dict/trie.cpp, src/textord/tablerecog.cpp, src/wordrec/chopper.cpp, unittest/tablerecog_test.cc
length() is not needed: it can be replaced by size().
=> Remove redundant method from class GenericVector

src/api/baseapi.cpp, src/api/renderer.cpp
In my application, I spawn tesseract.exe from java and continuously send request (path to image) / receive response  (tokens) through standard pipe-stdio.
For example, tesseract is launched with following args.
```
tesseract.exe stdin stdout -c stream_filelist=true
```
Problem with the existing code, **tokens are never flushed from  tesseract.exe** when OCR is finished for the image (token is fully-buffered).  In other words, tokens will not be flushed until tesseract.exe is killed, because they are only buffered.
Based on research, this is due to the way buffering behaves differently for following streams:
Since Java communicates with the child process over a pipe, it falls into the “stdout (not a TTY)” category.
More ref: https://eklitzke.org/stdout-buffering
I was able to resolve by …
=> Fix "tesseract.exe not flushing stdout/stderr" (Issue #2859)

src/ccmain/ltrresultiterator.cpp
This fixes a segfault when running with `lstm_choice_mode=2` and querying the choice iterator.
=> ChoiceIterator: skip symbol without choices

INSTALL.GIT.md, java/Makefile.am, java/Manifest.txt
=> Update piccolo2d-core and piccolo2d-extras

src/dict/trie.h
The fix makes the definition of `\n` consistent with the examples given below the definition.  Please note that I did not check this against how it is implemented in the code.
=> [trie.h] pattern definition: fix documentation

include/tesseract/baseapi.h, unittest/baseapi_test.cc
It is now added unconditionally, so it is always available for the unittest.
=> Add TessBaseAPI::GetPageRes again

src/arch/dotproductavx.cpp, src/arch/dotproductfma.cpp, src/arch/dotproductsse.cpp, src/arch/intsimdmatrixavx2.cpp, src/arch/intsimdmatrixsse.cpp
This won't affect anything using the supplied build system. For
other projects that include tesseract within them, however, this
may make their life easier.
For example, I have an integration of Tesseract with Ghostscript,
in which tesseract is built as part of the Ghostscript build,
without using the tesseract build system.
The Ghostscript build system is makefile based, and has to work
on a range of make systems, including unix make, gnu make and
nmake. As such we have to avoid conditionals in the common
makefiles. It therefore becomes hard to build one set of files on
x86 systems, and another on (say) ARM systems.
Accordingly, this commit makes small tweaks to the architecture
specific files, so that they compile on EVERY platform; just they
only compile to anything useful on the …
=> Tweak architecture specific SIMD files for ease of compilation.

src/ccmain/linerec.cpp
At present, `Tesseract::GetRectImage` checks to see whether the `pixClipRectangle` function has failed, and returns if it has.  But in such a case, the created `clip_box` is not boxDestroyed.  Swapping the order of these two lines, as in this patch, fixes this potential small problem.
=> Destroy box before potentially exiting function (preventing a memory leak)

src/lstm/lstmrecognizer.cpp
The limit was increased from 2048 to 2560 in the past. I now had to increase it to 4096
for training from some newspaper lines, but even that was not enough when training
models with line images normalized to 64 px height.
=> Allow line images with larger width (depending on height)

src/api/baseapi.cpp, src/api/hocrrenderer.cpp, src/ccutil/tessdatamanager.cpp
If we aren't using config.h, then PACKAGE_VERSION is not
defined. Spot this, and include tess_version.h to get
TESSERACT_VERSION_STR instead.
=> Ensure PACKAGE_VERSION is defined, even without config.h

src/ccstruct/imagedata.cpp
The patch (which doesn't alter any code) is hopefully self-explanatory!  It had me a little confused for a bit.
=> Trivial code documentation fix: move comment about swap meaning for DeSerialize to correct function

src/ccmain/tessedit.cpp
If api->Init is called with OEM_DEFAULT in DISABLED_LEGACY_ENGINE
build modes, the engine mode is never set, resulting in no
words being found.
=> Fix OEM_DEFAULT in DISABLED_LEGACY_ENGINE builds.

src/arch/simddetect.cpp
Every other file already does this.
=> Guard #include "config_auto.h" with HAVE_CONFIG_H.

src/ccstruct/debugpixa.h
If TESSERACT_DISABLE_DEBUG_FONTS is defined, tesseract doesn't
atetmpt to create any debug fonts. This not only saves memory,
but it (combined with the change to optionally use Pix as
internal storage for the ImageData) allows us to use an
embedded Leptonica library with no format handlers at all.
=> Add a mechanism to avoid creating debug fonts.

src/ccstruct/imagedata.cpp, src/ccstruct/imagedata.h
By default, when we ImageData::SetPix, we write the data out as a
PNG, just to read it back in to get a compressed buffer of data.
We then use this to generate a new Pix.
In builds of Tesseract on systems where we don't have temp files,
writing files out is problematic.
Not only that, but compressing/uncompressing is slow, and on minimal
builds of leptonica, where we've disabled the format writers to reduce
memory footprint, we get no compression anyway.
In such cases, it'd be far nicer just to keep the original Pix as
the internal data.
Also, when recovering the pixmap from the ImageData, if we know we're
only going to read from the data, we can avoid duplicating it and
just use the original. This is exactly the case when GRAPHICS_DISABLED
is set.
So, introduce a …
=> Avoid tesseract writing Pix out/reading them back.

Makefile.am, configure.ac, src/api/tesseractmain.cpp, src/arch/intsimdmatrix.h, src/arch/intsimdmatrixneon.cpp, src/arch/simddetect.cpp, src/arch/simddetect.h
In tests on my pi3b+, a release build of my ghostscript integration
takes 2 minutes 27 seconds to render a PDF and OCR it with the
vanilla sources. With this NEON coded added the time drops to 37
seconds.
I have not tested the configure/Makefile changes as I'm not using
them.
=> NEON SIMD code.

src/ccstruct/coutln.cpp
This fixes a bug reported by OSS Fuzz:
https://oss-fuzz.com/issue/5697280134348800
The old code passed a negative value (-1) as argument to step_dir
when destindex was 0.
=> Fix undefined shift with negative value (oss-fuzz issue 14658)

src/ccstruct/rect.cpp, src/ccstruct/rect.h, src/ccstruct/seam.cpp, src/ccstruct/seam.h, src/ccstruct/split.cpp, src/ccstruct/split.h
OSS Fuzz reports a timeout in issue 19900
(https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19900).
Im my test, making some functions which are called most often in that test inline
reduces the execution time from 44 s to 39 s.
=> Make several functions inline for improved performance

src/ccmain/thresholder.cpp
The old code used pixConvertRGBToLuminance which only converts 32 bpp images.
=> Fix conversion of images with 16 bpp or 24 bpp to grey

CMakeLists.txt
Adding MT option for MSVC compiler option using CMAKE_MSVC_RUNTIME_LIBRARY option.
Applicable only to WIN32
=> Add MT option for MSVC compilation

CMakeLists.txt
When building with CMake and MinGW 4.9，I got these error:
> -- General configuration for Tesseract 4.1.1
> -- --------------------------------------------------------
> -- Build type: Release
> -- Compiler: GNU
> -- Used standard: C++17
> -- CXX compiler options:  -O3 -DNDEBUG
> -- Configuring done
> CMake Error in CMakeLists.txt:
>   Target "libtesseract" requires the language dialect "CXX17" , but CMake
>   does not know the compile flags to use to enable it.
> 
> CMake Error in CMakeLists.txt:
>   Target "tesseract" requires the language dialect "CXX17" , but CMake does
>   not know the compile flags to use to enable it.
> 
> -- Generating done
> CMake Generate step failed.  Build files cannot be regenerated correctly.
For MinGW 4.9，CMAKE_CXX17_STANDARD_COMPILE_OPTION is empty and …
=> Fixed CMakeLists.txt for the compilers without C++17 support

src/textord/colpartition.cpp, src/textord/colpartition.h
Runtime error with enabled sanitizer:
src/textord/colpartition.cpp:2243:66: runtime error: index -1 out of bounds for type 'tesseract::ColPartition *[6]'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/textord/colpartition.cpp:2243:66 in 
=> Fix out of bounds array access

src/lstm/recodebeam.cpp
Runtime error reported by sanitizer:
src/ccstruct/rect.h:191:44: runtime error: 50961 is outside the range of representable values of type 'short'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/ccstruct/rect.h:191:44 in
=> Fix runtime error caused by too large TBOX

include/tesseract/osdetect.h, include/tesseract/serialis.h, src/api/baseapi.cpp, src/ccmain/applybox.cpp, src/ccmain/linerec.cpp, src/ccmain/osdetect.cpp, src/ccmain/recogtraining.cpp, src/ccmain/tesseractclass.h, src/ccstruct/boxread.cpp, src/ccstruct/boxread.h, src/ccstruct/imagedata.cpp, src/ccutil/object_cache.h, src/ccutil/serialis.cpp, src/ccutil/tessdatamanager.cpp, src/ccutil/tessdatamanager.h, src/classify/blobclass.cpp, src/classify/blobclass.h, src/classify/classify.h, src/dict/dawg_cache.cpp, src/training/errorcounter.h, src/training/lstmtester.cpp, src/training/lstmtester.h, src/training/lstmtrainer.cpp, src/training/lstmtrainer.h, unittest/applybox_test.cc
This replaces the proprietary STRING data type
(801 instead of 838 lines remaining).
It also removes STRING from osdetect.h and serialis.h.
=> Use const char* for filename parameters

src/textord/baselinedetect.cpp, src/textord/baselinedetect.h
It was reported by oss-fuzz (issue 23962).
Add log output to find real images which trigger that issue.
Avoid also some conversions from float to double by always using float.
=> Fix division by 0.0 in BaselineRow::PerpDistanceFromBaseline

src/viewer/svutil.cpp, src/viewer/svutil.h
strtok_s can be used with MSVC as a replacement for strtok_r, so less
special handling is needed in the code and class SVNetwork can be
made smaller by removing member has_content.
=> Use strtok_s for MSVC in class SVNetwork

src/dict/dict.h
The kDictWildcard is never actually used, so removing it makes
no difference. It causes warnings in MSVC builds as MSVC doesn't
know how to pack a unicode value into chars.
=> Remove unused char constant that causes a warning.

src/textord/alignedblob.cpp, src/textord/colfind.cpp
This fixes 2 minor issues with foreground line separator detection.
Here is an example (using the ALTO renderer and PageViewer for display):
- before (misses small vertical and large horizontal line):
- after (fixed):
=> Fix separator line detector

src/ccmain/pagesegmain.cpp
- Issues:
- Debug information for "NoImages" just be binary image,
it don't show up the result of photo_mask_pix to developer
- Fix:
- Substract binary image to photo_mask_pix, the result
are "NoImages" binary pix
=> Correct "NoImages" in debug pdf file

CMakeLists.txt
Currently the CMake files are being installed in the `cmake` folder in the root of the install prefix. This is a bit odd. On Linux installation through CMake will create `cmake` in the `/usr` (common installation prefix on most distros), which is not desirable.
Usually CMake files are installed to the `lib/cmake` folder and export files are installed to the `lib/library-name`. That's what I changed in this PR.
=> Fix CMake install configs

src/training/pango_font_info.cpp, src/training/pango_font_info.h, unittest/pango_font_info_test.cc
They used the function pango_coverage_max which does nothing and
which has been deprecated since pango version 1.44.
=> Remove unused functions FontUtils::GetAllRenderableCharacters

CMakeLists.txt
For compatibility with older CMake, references #3112, fixes [this](https://travis-ci.org/github/tesseract-ocr/tesseract/jobs/732859406) CMake issue on Travis.
=> Use DESTINATION instead of TYPE

src/arch/simddetect.cpp
cpufeatures.h should be cpu-features.h, with the latest NDK
at least. The #if 0'd section is not required because armv8
always includes NEON.
=> Tweak SIMDDetect for ANDROID Neon.

src/lstm/lstmrecognizer.cpp
The old code tries a 2nd OCR on lines when a word confidence is below 50 %, so a single word with low confidence triggers it. This happens rather often, mostly for lines without inverted text, and costs performance.
The new code checks the mean confidence instead of the minimum. This typically improves the performance significantly and still works for lines with much inverted text.
In addition, the OCR result of the inverted image is now accepted if its mean confidence is better than the original one. In my test this improves the OCR result, especially for lines which only have some words with inverted text.
The algorithm still does not handle lines with both normal and inverted text optimally. OCR for such lines could be improved by inverting word wise or maybe by using Leptonica …
=> Modify OCR for inverted text

.gitattributes
With this set, Windows users will have text files converted from Windows style line endings (\r\n) to Unix style line endings (\n) when they’re added to the repository.
https://www.edwardthomson.com/blog/git_for_windows_line_endings.html
=> Create .gitattributes for cross os contributors

unittest/Makefile.am, unittest/tesseract_leaksanitizer.supp
The fontconfig library has some (intentional) memory leaks which
must be suppressed for unit tests with the LeakSanitizer.
This fixes the issues #3156 and #3157.
=> Suppress some LeakSanitizer errors in unit tests

CMakeLists.txt, cmake/templates/TesseractConfig.cmake.in
* Use `find_dependency` instead of `find_package`. It's recommended to use [find_dependency](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html) for CMake config files ([official tutorial](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#creating-a-package-configuration-file)).
* Now all CMake config files located in `lib/cmake/tesseract`. This is a more common practice. Previously `TesseractConfig.cmake` and `TesseractVersion.cmake` files was `lib/cmake/tesseract/tesseract` (additional subfolder).
* Fix typo in `Tesseract_INCLUDE_DIR` -> `Tesseract_INCLUDE_DIRS` (as noted in the description if this file).
=> Improve CMake configuration

src/training/pango_font_info.cpp, src/training/pango_font_info.h, unittest/pango_font_info_test.cc
This fixes the test on platforms like MacOS (maybe also Windows) which don't use the fontconfig backend by default.
Fix and improve also some other smaller issues in the pango_font_info.cpp code.
=> Force fontconfig pangocairo backend for pango_font_info_test

Makefile.am
Fixes
```none
make[2]: *** No rule to make target 'src/ccutil/unicodes.cpp', needed by 'src/ccutil/libtesseract_ccutil_la-unicodes.lo'.  Stop.
make[2]: Leaving directory '/build/tesseract-git/build-64bit'
make[1]: *** [Makefile:5519: all-recursive] Error 1
make[1]: Leaving directory '/build/tesseract-git/build-64bit'
make: *** [Makefile:2004: all] Error 2
```
=> Makefile.am: remove unicode files

src/api/tesseractmain.cpp, src/arch/simddetect.cpp
Flag neon_available_ is automatically set to true when __aarch64__ is defined,
but the actual check for neon_available_ required having also HAVE_NEON defined.
Now we check the flag also when only __aarch64__ is defined.
=> Fix use of NEON on ARMv8

src/training/tesstrain.sh
Fixes https://github.com/tesseract-ocr/tesseract/issues/3001 and other similar issues
=> No --psm 6 for lstm.train

src/training/tesstrain.py
This reverts a part of commit b34cf9d to fix issue #3001
=> Remove --psm 6 for lstm.train in tesstrain.py

src/api/baseapi.cpp, src/ccmain/control.cpp, src/ccmain/linerec.cpp, src/ccmain/tessedit.cpp, src/ccmain/tesseractclass.cpp
Build fails when ANDROID_BUILD is defined, because it removes parts of the LSTM engine, but there are still some unguarded references. But removing LSTM engine is not needed as it works perfectly fine on Android.
This macro doesn't provide any benefit anymore and is not even used in current build config. If needed, ANDROID macro should be used instead (which is already used on few places).
=> Remove ANDROID_BUILD macro

.github/workflows/dailyunittest.yml
Please see https://github.com/Shreeshrii/testactions/runs/1721570829?check_suite_focus=true for a test run.
`Macports `gets some errors while running unittests regarding `abseil`. Probably because Macports is installing a newer version of abseil. @stweil Any suggestions on how to fix this?
```
../abseil/absl/base/internal/spinlock.cc:75:35: error: no type named 'LinkerInitialized' in namespace 'absl::lts_2020_09_23::base_internal'
SpinLock::SpinLock(base_internal::LinkerInitialized,
~~~~~~~~~~~~~~~^
../abseil/absl/base/internal/spinlock.cc:79:5: error: use of undeclared identifier 'InitLinkerInitializedAndCooperative'
InitLinkerInitializedAndCooperative();
^
../abseil/absl/base/internal/spinlock.cc:92:16: error: out-of-line definition of 'InitLinkerInitializedAndCooperative' does not …
```
=> Add daily tests for macos homebrew

unittest/lstm_test.h
Some more of these messages can be reduced. Attached log from run after this change.
[lstm_test.log](https://github.com/tesseract-ocr/tesseract/files/5840764/lstm_test.log)
=> Reduce number of INFO messages from lstm_test

unittest/tesseract_leaksanitizer.supp
Fixes leak identified in 
https://github.com/Shreeshrii/tesseract/runs/1756021945?check_suite_focus=true#step:12:59
=> Fix Memory leak in ligature_table_test

CMakeLists.txt
`set_and_check` can't work with lists and regular `check` should be used instead (see [CMake issue](https://gitlab.kitware.com/cmake/cmake/-/issues/16219)). Partially fixes #3269.
**Updated:** I removed extra include from `INCLUDE_DIR` and it works now.
=> Use set instead of set_and_check

src/training/language-specific.sh
Changed
URW Bookman L -> Bonum
Century Schoolbook L -> Schola
as per suggestion by @amitdo in https://github.com/tesseract-ocr/tesseract/pull/3071#issuecomment-772792181
=> Change LATIN_FONTS to use replacement fonts from TeX Gyre collection

configure.ac
The new options allow overriding the default behaviour which checks whether the documentation can be build and whether libarchive and libcurl are available.
=> Add new configure options --disable-doc, --with-archive and --with-curl

configure.ac
I needed this change to build tesseract 3.05.02 using the android ndk.
=> Specify ADD_RT for android platform, which embeds librt in libc

src/api/tesseractmain.cpp, src/lstm/weightmatrix.cpp, src/lstm/weightmatrix.h, src/training/lstmtraining.cpp, unittest/lstm_test.h
`lstmtraining --debug_float` now detects float errors like division by zero or overflow on systems with the GNU C library.
Such a division by zero occurs when running a training because of a `momentum == -1`.
That is fixed here by skipping the adaption of the learning rate for non-positive momentum values.
The float checks are unconditionally enabled by the new code for `tesseract` to see whether they occur there, too.
=> Add new checks for floating point errors and fix a division by zero

src/wordrec/wordrec.h
to make this codebase compile on Windows.
Just a minor glitch.
---
Your latest changes around `std::string` parameters missed this bit, which popped up as a compile error in my own (custom) tesseract build for Windows.
=> master branch: missing changes that are needed too

src/api/baseapi.cpp
Tesseract reported confusing information for images without resolution:
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 642
The warning is also shown when the resolution is not used at all
when preparing data for training.
It is now suppressed when there is no resolution information
(resolution == 0).
=> Suppress resolution warning if no resolution was given

src/api/tesseractmain.cpp
They were disabled in earlier builds which used NDEBUG, too.
Allow manual setting of the Leptonica message level
with environment variable LEPT_MSG_SEVERITY.
=> Disable most Leptonica messages for tesseract by default

src/training/tesstrain_utils.sh
It helps to reproduce failed command execution during training.
=> Print command line options if run_command() failed.

src/api/baseapi.cpp
=> Suppress output of page number for TIFF files with a single image

src/lstm/recodebeam.h
lstm/recodebeam.h was using PointerVector from ccutil/genericvector.h without including it.
=> lstm: Include missing header

src/textord/cjkpitch.cpp
I met floating point error during training Japanese model.
Here is gdb output.
```
Program received signal SIGFPE, Arithmetic exception.
0x00007fcca7c14f5c in tesseract::LocalCorrelation::EstimateYFor (this=0x7ffdeae919d0, x=45, r=0.100000001)
at src/textord/cjkpitch.cpp:165
165         return rc / vote;
```
This PR fixes the issue.
=> Fix division by zero during CJK training.

src/ccmain/ltrresultiterator.cpp, src/ccmain/ltrresultiterator.h, src/ccmain/pageiterator.cpp, src/ccmain/pageiterator.h
Allows row attributes to be accessed via PageIterator without runnning full recognition - in https://github.com/sirfz/tesserocr terms, by running only `AnalyseLayout` and not `Recognize`. 
If one is only interested in baselines and row attributes, but not text detection, this reduces the runtime by about a factor of 10, which is a big deal for processing big collections of 100 000s of pages.
Here's some results for extracting baselines and row attributes from the same page, v1 is with this PR (hash codes in the second line are on extracted baseline and row data which show that the results are identical).
`
v1: using AnalyseLayout: 
bbe705a10940601631c9a5f26f3f421a
time elapsed 2.9205799102783203
v2: using Recognize: 
bbe705a10940601631c9a5f26f3f421a
time elapsed 25.913426399230957
`
Test …
=> Add RowAttributes getter to PageIterator

src/viewer/svutil.cpp, src/viewer/svutil.h
Operating system object leak when using LSTMRecognizer (that is tessdata ver 4). Each time you initialize a TessBaseAPI object you lose four mutexes.
Added destructors to SVMutex and SVSemaphore to cleanup mutex and semaphore objects.
issue [https://github.com/tesseract-ocr/tesseract/issues/3397](https://github.com/tesseract-ocr/tesseract/issues/3397)
=> Adding SVMutex and SVSemaphore destructors to avoid system objects leaks

src/ccmain/tessedit.cpp, src/ccmain/tesseractclass.h
In source code is used parameter `set_only_init_params`, but this value is then internally being used as `set_only_non_debug_params`. So the parameter name and documentation should be updated.
=> Fix wrong parameter name and documentation

include/tesseract/baseapi.h, src/api/baseapi.cpp, src/api/tesseractmain.cpp, src/ccmain/control.cpp, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h
Follow-up of https://github.com/tesseract-ocr/tesseract/pull/2784 after rebasing the branch
=> Adding --print-fonts-table parameter & tessedit_font_id configuration option

include/tesseract/baseapi.h, src/api/baseapi.cpp
When compiling tesseract master branch with legacy engine DISABLED, these bits of code would throw a tantrum as they are for legacy only.
(Cherrypicked commit back onto mainline master.)
\# Conflicts:
\#	googletest
=> fix compile error: PrintFontsTable() is for legacy builds only

configure.ac
Just a small typo, it prints `libicu-devel` what should be `libicu-dev`
=> [doc][fix] typo libicu-devel

src/training/unicharset/lstmtester.cpp
It can be handy when evaluating a new training set to see the character and word error rates for each line, rather than just the average over a set.
=> lstmeval: Print char and word error rates for each line tested

src/ccutil/object_cache.h
>for (auto i = cache_.size() - 1; i >= 0; i--) {
https://github.com/tesseract-ocr/tesseract/commit/4b5dd25b845d2ebf5ef7b15a86589d52f7b12495
The return type of .size() is unsigned, so the condition `i >= 0` will never be false and will crash.
This issue occurs when importing the Python `tesserocr` module.
```
% gdb --args bash python3
(gdb) run
>>> import tesserocr
Program received signal SIGSEGV, Segmentation fault.
tesseract::ObjectCache<tesseract::Dawg>::DeleteUnusedObjects (this=0x7ffff60d2c00 <tesseract::Dict::GlobalDawgCache()::cache>) at ./src/ccutil/object_cache.h:99
99            if (cache_[i].count <= 0) {
```
=> Fix crash in ObjectCache::DeleteUnusedObjects

include/tesseract/publictypes.h, src/ccmain/thresholder.cpp
The fact that this method uses tiles is implementation detail. It does not change the result compared to Sauvola without tiles. The use of tiles minimize memory consumption.
=> ThresholdMethod::TiledSauvola -> ThresholdMethod::Sauvola

src/api/baseapi.cpp
Added missing NULL check to avoid crash when we read property in our tesseract wrapper.
=> Null check for GetSourceYResolution

src/training/combine_tessdata.cpp
`combine_tessdata -l ...` command shows the initial value of the learning rate, but not the layer (final)learning rates that are actually used in finetuning (lstmtraining with `-continue_from` option).
This PR will add layer learning rates to the output of `combine_tessdata -l` command.
Example output:
```
% ./combine_tessdata -l ../tessdata_best/eng.traineddata
LSTM: network=[1,36,0,1Ct3,3,16Mp3,3Lfys64Lfx96Lrx96Lfx512O1c1], int_mode=0, recoding=1, iteration=814100, sample_iteration=814136, null_char=110, learning_rate=0.001, momentum=0.5, adam_beta=0.999
Layer Learning Rates: :0(Input)=0.001, :1:0(Convolve)=0.001, :1:1(ConvNL)=0.0005, :2(Maxpool)=0.001, :3:0(Lfys64)=0.0005, :4(Lfx96)=0.0005, :5:0(Lrx96)=0.0005, :6(Lfx512)=0.0005, :7(Output)=0.0005
```
```
% ./combine_tessdata -l …
```
=> Show layer specified learning rates with combine_tessdata -l

src/training/unicharset/lstmtrainer.cpp
When training is started from `lstmtraining --continue_from ...` command, various iteration counter and  error rate variables are reset by `LSTMTrainer::InitIterations()`, but `best_error_history_` and `best_error_iterations_` are not reset from the previous training state. This may cause negative time to be reported in the training log.
This PR fixes it.
```
2 Percent improvement time=-28864, best error was 7.024 @ 39917
At iteration 11053/19300/19300, Mean rms=0.359000%, delta=1.110000%, char train=4.931000%, word train=34.318000%, skip ratio=0.000000%,  New best char error = 4.931000Previous test incomplete, skipping test at iteration 10740 wrote checkpoint.
2 Percent improvement time=-28816, best error was 7.024 @ 39917
At iteration 11101/19400/19400, Mean rms=0.357000%, …
```
=> Fix missing reset of best_error_history_ in LSTMTrainer::InitIterations()

src/lstm/lstmrecognizer.h, src/lstm/plumbing.h, src/training/lstmtraining.cpp
When the `--reset_learning_rate` option is specified, it resets the learning rate stored in each layer of the network loaded with `--continue_from` to the value specified by the `--learning_rate` option.
If checkpoint is available, it does nothing.
background:
Currently, the `-learning_rate` option specified when finetuning with the `lstmtraining --continue_from ...` command is ignored. Instead, the learning rate stored in the pretrained model will be used. You can check its value with the [combine_tessdata -l command](https://github.com/tesseract-ocr/tesseract/pull/3468).
The learning rate stored in the pretrained model is different for each language, and the behavior of finetuning is also different.
So, if the user has experience in machine learning, it is useful in some situations to …
=> Add --reset_learning_rate option to lstmtraining

src/ccstruct/imagedata.cpp
lstmtraining rarely hangs in training.
DocumentData::LoadPageInBackground() and DocumentData::ReCachePages() both tries to lock pages_mutex_.
If LoadPageInBackground() locks pages_mutex_ before previous call of ReCachePages() starts LoadPageInBackground() tries to join() blocked ReCachePages() thread and waits forever. 
It occurs in very high load (CPU or disk is busy) situation.
```cpp
void DocumentData::LoadPageInBackground(int index) {
ImageData *page = nullptr;
if (IsPageAvailable(index, &page)) {
return;
}
std::lock_guard<std::mutex> lock(pages_mutex_);
if (pages_offset_ == index) {
return;
}
pages_offset_ = index;
for (auto page : pages_) {
delete page;
}
pages_.clear();
if (thread.joinable()) {
thread.join();
}
thread = std::thread(&tesseract::DocumentData::ReCachePages, this);
} …
```
=> Fix deadlock in lstmtraining.

src/lstm/convolve.h
This PR fixes the wrong order of x window size and y window size in the spec string of the convolution layer.
From VGSL Specs https://tesseract-ocr.github.io/tessdoc/tess4/VGSLSpecs.html
>C(s|t|r|l|m)**\<y\>,\<x\>,\<d\>** Convolves using a y,x window, with no shrinkage,
random infill, d outputs, with s|t|r|l|m non-linear layer.
In VGSL parsing, it is **\<y\>,\<x\>**,\<d\>. (correct)
https://github.com/tesseract-ocr/tesseract/blob/88d4028a5a44e3fd7d0d66fe187b197ffccccf4e/src/training/common/networkbuilder.cpp#L280-L281
However, the format of the spec string is **\<x\>,\<y\>**.
https://github.com/tesseract-ocr/tesseract/blob/88d4028a5a44e3fd7d0d66fe187b197ffccccf4e/src/lstm/convolve.h#L39-L41
=> Fix spec string of convolution layer

src/ccmain/pgedit.cpp, src/ccmain/pgedit.h, src/ccstruct/blobbox.h, src/textord/blkocc.h, src/textord/drawtord.h, src/textord/fpchop.cpp, src/textord/fpchop.h, src/textord/makerow.cpp, src/textord/makerow.h, src/textord/pitsync1.cpp, src/textord/pitsync1.h, src/textord/topitch.cpp, src/textord/topitch.h, src/textord/tovars.cpp, src/textord/tovars.h, src/textord/wordseg.cpp, src/textord/wordseg.h, src/wordrec/drawfx.cpp, src/wordrec/drawfx.h
The following parameters are not used anywhere anymore:
* editor_image_text_color
* editor_dbwin_name
* editor_dbwin_xpos
* editor_dbwin_ypos
* editor_dbwin_height
* editor_dbwin_width
* editor_image_height
* editor_image_width
* editor_smd_scale_factor
* textord_error_weight
* blockocc_show_result
* blockocc_desc_height
* blockocc_asc_height
* blockocc_band_count
* to_debugfile
* to_smdfile
* textord_fp_chop_snap
* textord_spline_outlier_fraction
* textord_quadratic_baselines
* textord_cblob_blockocc
* textord_spline_outlier_fraction
* pitsync_fake_depth
* textord_pitch_cheat
* textord_show_new_words
* textord_show_fixed_words
* textord_width_smooth_factor
* textord_words_width_ile
* textord_spacesize_ratiofp
* textord_blocksall_testing
* textord_test_mode
* textord_fp_min_width
* …
=> Removed unused parameters 

Makefile.am, src/arch/dotproduct.h, src/arch/intsimdmatrix.cpp, src/arch/intsimdmatrix.h, src/arch/intsimdmatrixneon.cpp, src/arch/intsimdmatrixsse.cpp, src/arch/simddetect.cpp, src/arch/simddetect.h, src/ccutil/tesstypes.h, src/lstm/fullyconnected.cpp, src/lstm/fullyconnected.h, src/lstm/functions.cpp, src/lstm/functions.h, src/lstm/lstm.cpp, src/lstm/lstm.h, src/lstm/network.cpp, src/lstm/network.h, src/lstm/networkio.cpp, src/lstm/networkio.h, src/lstm/networkscratch.h, src/lstm/plumbing.cpp, src/lstm/plumbing.h, src/lstm/weightmatrix.cpp, src/lstm/weightmatrix.h, src/training/unicharset/lstmtrainer.cpp, src/training/unicharset/lstmtrainer.h
The new header file ccutils/tesstypes.h also prepares support
for larger images by introducing a new data type for image
size and coordinates (still unused).
FloatToDouble is now a local function.
=> Prepare using float instead of double for LSTM calculations

src/arch/dotproductavx.cpp, src/arch/dotproductfma.cpp, src/arch/dotproductsse.cpp, src/arch/intsimdmatrix.h, src/arch/intsimdmatrixavx2.cpp, src/arch/simddetect.cpp, src/ccstruct/blobbox.h, src/ccstruct/matrix.h, src/ccutil/tesstypes.h, src/lstm/weightmatrix.cpp, unittest/intsimdmatrix_test.cc
Up to now Tesseract used double for training and recognition
with "best" models.
This commit replaces double by a new data type `TFloat` which
is double by default, but float if FAST_FLOAT is defined.
Ideally this should allow faster training.
=> Add TFloat data type for neural network

src/training/unicharset/lstmtrainer.cpp
Tesseract currently cannot continue LSTM training from an
integer (fast) model.
Report this to users who try it nevertheless instead of crashing
with an assertion.
=> Abort LSTM training with integer model (fixes issue #1573)

src/training/common/commontraining.cpp
Fixes: 4415209fd667 ("Remove tessopt. This fixes mastertrainer test in shared build")
=> Fix crash of shapeclustering (fixes #3564)

cmake/templates/TesseractConfig.cmake.in
In the past Tesseract library was wrongly named as "liblibtesseract" so it was needed to use "-llibtesseract" as argument for linker. The name was fixed in commit 52cac3a42ef2b823b9367b9ee2d1d84f8eda4ea0 but the ${Tesseract_LIBRARIES} variable still wrongly holds "libtesseract" and causes linker error when one is using it in target_link_libraries(...). This commit fixes that.
=> Fix linking Tesseract to project using CMake on Linux

src/api/hocrrenderer.cpp
This will make Tesseract emit the DPI of the document, if known at OCR
time. This is requird to properly interpret the x_fsize (font size)
property of words, since Tesseract scales the font size to the DPI.
See issue #3326 (https://github.com/tesseract-ocr/tesseract/issues/3326)
=> hocrrenderer: write scan_res property to the ocr_page

CMakeLists.txt, cmake/templates/TesseractConfig.cmake.in
- Use correct library name in TesseractConfig.cmake on all platforms
- Expose Tesseract_VERSION and Tesseract_VERSION_* variables in TesseractConfig.cmake
=> cmake: Improve configuration

README.md
Versions 4.1.1 and 5.0.0 still support the legacy engine with the same functionality as 3.05.02, so there is no reason to mention 3.05.02.
=> README: Remove the reference to version 3.05.02

src/training/lstmtraining.cpp, src/training/unicharset/lstmtester.cpp, src/training/unicharset/lstmtrainer.cpp
The old messages could wrongly be interpreted as CER / WER values,
but Tesseract training currently uses simple bag of characters /
bag of words error rates (see LSTMTrainer::ComputeCharError,
LSTMTrainer::ComputeWordError).
=> Improve training messages (issue #3560)

src/training/unicharset/validate_indic.cpp, src/training/unicharset/validate_javanese.cpp
warning: format ‘%c’ expects argument of type ‘int’, but argument 2 has type ‘tesseract::Validator::CharClass’ [-Wformat=]
=> Training: Fix compiler warnings

src/classify/adaptmatch.cpp, src/classify/classify.cpp, src/classify/classify.h
It was also declared in class Dict and mostly used from that class.
Setting it via API or command line never changed that used value.
=> Remove duplicate parameter certainty_scale

src/training/CMakeLists.txt
=> Fix build with cmake 3.10.2 (Ubuntu bionic)

CMakeLists.txt
=> cmake: TIFF is only used for WIN32

cmake/Configure.cmake, configure.ac, src/tesseract.cpp
feenableexcept is not supported by uclibc
Signed-off-by: Gilles Talis <gilles.talis@gmail.com>
[Retrieved (and updated to add cmake support and simplify configure.ac)
from
https://git.buildroot.net/buildroot/tree/package/tesseract-ocr/0001-Check-if-platform-supports-feenableexcept.patch]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> Check if platform supports feenableexcept

CMakeLists.txt
CMakeLists.txt uses TREE (supported since cmake 3.8) and
check_ipo_supported (supported since cmake 3.9).
Require 3.10 which is provided by Ubuntu bionic and newer distributions.
=> Require cmake 3.10 or newer

src/ccstruct/matrix.h, src/ccutil/clst.h, src/ccutil/elst.h, src/ccutil/elst2.h
Changing from class to struct causes clang compiler warnings like this one:
In file included from ../../../src/api/baseapi.cpp:63:
../../../include/tesseract/osdetect.h:29:1: warning: class 'BLOB_CHOICE_LIST' was previously declared as a struct; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
class BLOB_CHOICE_LIST;
^
../../../src/ccstruct/ratngs.h:228:1: note: previous use is here
ELISTIZEH(BLOB_CHOICE)
^
../../../src/ccutil/elst.h:804:10: note: expanded from macro 'ELISTIZEH'
struct CLASSNAME##_LIST : X_LIST<ELIST, ELIST_ITERATOR, CLASSNAME> { \
^
<scratch space>:458:1: note: expanded from here
BLOB_CHOICE_LIST
^
../../../include/tesseract/osdetect.h:29:1: note: did you mean struct here?
class BLOB_CHOICE_LIST;
^~~~~
As it is not possible …
=> Partially revert changes of list data types (fix compiler warnings)

src/api/altorenderer.cpp, src/api/baseapi.cpp, src/api/hocrrenderer.cpp
=> Handle image and line regions in output formats ALTO, hOCR and text

CMakeLists.txt
When building Tesseract, an error message appears in CMake. Depending on the CMake version, the target OpenMP::OpenMP_CXX is apparently already defined. In any case it is already present in 3.22.2. Therefore you should check if the target already exists.
Solves issue #3751
=> Check OpenMP target in CMake (issue #3751)

Makefile.am, configure.ac
MSYS2 clang64 uses the lld linker which does not support --as-needed.
The normal GNU ld uses that linker option with ELF targets but ignores
it for PE targets (.exe, .dll), so it can be removed.
Remove also the -Wl, which is only needed when linker options are
passed to the compiler but not when they are directly passed to the
linker.
=> Fix linker flags for MSYS2 clang64 builds

src/api/renderer.cpp
=> Check input for `AppendString` to avoid `strlen(nullptr)`.

configure.ac, src/arch/simddetect.cpp
FreeBSD does not have the `<asm/hwcap>` header, requiring some slightly different code to check for NEON availability.  This code might also apply to other BSD-like operating systems such as NetBSD, OpenBSD, DragonflyBSD, or iOS, but I haven't checked.
=> src/arch/simddetect.cpp: fix NEON detection on FreeBSD

src/api/capi.cpp
`strdup` returns memory allocated via `malloc`, so either `TessDeleteTextArray` should use `free` or `strdup` should be replaced by `new []`.
=> capi: Fix calling delete[] for memory allocated by malloc

src/classify/intproto.cpp, src/classify/shapeclassifier.cpp, src/textord/ccnontextdetect.cpp, src/textord/colfind.cpp, src/textord/strokewidth.cpp, src/training/common/mastertrainer.cpp, src/training/unicharset/lstmtrainer.cpp, src/viewer/scrollview.cpp, src/viewer/scrollview.h
This PR fixes memory issues that caused https://github.com/tesseract-ocr/tesseract/issues/3869. The first commit fixes the actual bug (`unique_ptr::release()` should be used instead of `unique_ptr::get()`). The second fixes the underlying problem of using plain pointers that caused the bug in the first place.
Fixes https://github.com/tesseract-ocr/tesseract/issues/3869.
Supersedes https://github.com/tesseract-ocr/tesseract/pull/3870
FYI @rmast @stweil.
=> Fix memory issues in ScrollView::MessageReceiver

src/training/ambiguous_words.cpp, src/training/classifier_tester.cpp, src/training/cntraining.cpp, src/training/combine_lang_model.cpp, src/training/combine_tessdata.cpp, src/training/dawg2wordlist.cpp, src/training/lstmeval.cpp, src/training/merge_unicharsets.cpp, src/training/mftraining.cpp, src/training/set_unicharset_properties.cpp, src/training/shapeclustering.cpp, src/training/text2image.cpp, src/training/wordlist2dawg.cpp
Add also a missing return statement and use EXIT_FAILURE
and EXIT_SUCCESS instead of 1 and 0 as return values.
=> Replace call of exit function by return statement in main function

.github/workflows/cmake.yml, .github/workflows/unittest-disablelegacy.yml
Reason: https://github.com/actions/runner-images/issues/6002
I still keep Ubuntu 18.04 in autotools CIs for now.
[skip ci]
=> CI: Remove Ubuntu 18.04

configure.ac
Fix the following build failure on `aarch64_be`:
`/home/buildroot/autobuild/instance-3/output-1/host/opt/ext-toolchain/bin/../lib/gcc/aarch64_be-none-linux-gnu/10.3.1/../../../../aarch64_be-none-linux-gnu/bin/ld: ./.libs/libtesseract.so: undefined reference to `tesseract::IntSimdMatrix::intSimdMatrixNEON'`
Fixes:
- http://autobuild.buildroot.org/results/b9246a37fcf6be4fabfc491daddadfb09e0a320a
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> configure.ac: fix build on aarch64_be

tesseract.pc.cmake
cf: https://github.com/tesseract-ocr/tesseract/blob/HEAD/tesseract.pc.in#L13
We found that bindings fail to compile when tesseract was built with cmake, because its pc file does not properly declare the leptonica dependency in the headers.
=> Fix tesseract.pc from cmake to match autotools

src/ccmain/thresholder.cpp
Maybe code for colormap removal could be simplified to `original = pixConvertTo8(original.copy(), false);` but I decided to stick to original code (in SetImage).
This change works for me for images in issues #3940 and #3092 and for thresholding_method 0,1,2.
=> fix issue #3940 - remove colormap before thresholding

src/api/pdfrenderer.cpp
=> pdfrenderer.cpp: Ignore non-text blocks

src/ccstruct/boxread.cpp
(typical for ocropy / kraken and GT without binarization)
=> lstm.train: allow .box from .raw.png too

src/api/hocrrenderer.cpp, src/ccmain/control.cpp, src/ccstruct/fontinfo.cpp, src/ccstruct/points.h, src/ccutil/params.h, src/ccutil/serialis.h, src/classify/adaptmatch.cpp, src/classify/shapeclassifier.cpp, src/dict/dawg.h, src/lstm/networkio.cpp, src/lstm/recodebeam.cpp, src/training/pango/pango_font_info.cpp, src/wordrec/chopper.cpp, src/wordrec/lm_pain_points.cpp
The latest scan reported a number of performance issues because
several `for` loops used expensive copy operations.
After adding the `const` attribute to compare operators, `const`
could also be used in most `for` loops.
=> Fix a number of performance issues (reported by Coverity Scan)

src/training/common/trainingsampleset.cpp
Fixes: cac116dd11dc0976 ("Replace more PointerVector by std::vector [...]")
=> Fix training tools for legacy engine (issue #3925)

src/training/CMakeLists.txt
Uses the targets generated by [`pkg_check_modules`](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html#command:pkg_check_modules). These targets prevents various link errors if your libs are not on the default compiler search path.
=> Fix linkage of icu and pango

src/ccutil/params.h
gcc 13 moved some includes around and as a result <cstdint> is no longer transitively included [1]. Explicitly include it for int32_t.
[1] https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> Fix build with gcc 13 by including <cstdint>

tesseract.pc.cmake
`tesseract.pc.cmake` was hardcoding libdir to `${prefix}/lib`, which is wrong for systems that place 64-bit libraries in `/usr/lib64/`. 
On Fedora, this was causing a CMake-generated `tesseract.pc`, installed to `/usr/lib64/pkgconfig/`, to produce library flags that included `-L/usr/lib`, potentially polluting 64-bit builds with 32-bit libs.
`CMAKE_INSTALL_LIBDIR` is already expected to contain the arch-corrected libdir path relative to the CMake install prefix, so it can be used to set the pkg-config `libdir` relative to `${prefix}`.
=> Fix libdir in tesseract.pc from CMake

Makefile.am, configure.ac, src/ccstruct/boxread.cpp, src/ccutil/unicharset.cpp, src/dict/dawg.h, src/dict/permdawg.cpp, src/textord/makerow.cpp, src/training/pango/pango_font_info.cpp, src/training/unicharset_extractor.cpp, src/wordrec/language_model.cpp, src/wordrec/language_model.h, src/wordrec/segsearch.cpp
Both forms are used in American English, but 'cannot' is more common (also in Tesseract code), so use it always.
=> Replace 'can not' by 'cannot'

README.md
Raised in https://github.com/tesseract-ocr/tessdoc/issues/83
=> Readme: Link to list of supported languages

src/ccmain/paragraphs.cpp
Improve the DebugDump output by slightly adjusting the format for the numeric columns, which was 3,3,3,3 and overflowing in our test runs, damaging the table layout. See rationale in the code comment:
------
// The largest (positive and negative) numbers are reported for lindent & rindent.
// While the column header has widths 5,4,4,5, it is therefore opportune to slightly
// offset the widths in the format string here to allow ample space for lindent & rindent
// while keeeping the final table output nicely readable: 4,5,5,4.
#	src/ccmain/paragraphs.cpp
-----------
Sample output: (BTW: note the '1270' in there, which previously pushed the table layout out of whack)
```
Active Paragraph Models:
#row space .. lword[widthSEL]                      rword[widthSEL] …
```
=> Improve the DebugDump output by slightly adjusting the format.

src/ccmain/pagesegmain.cpp
Enable some code blocks that were wrongly disabled when the legacy engine is disabled at compile time.
=> Fix issue #4010

snap/snapcraft.yaml
This patch fixes the outdated snap package recipe to make the snap buildable with the current Snapcraft release(7.3.1).
=> fix: Fix snap package building

src/training/unicharset/validate_myanmar.cpp
Fixes the issue reported in #4061 
1. Added 0x102c and 0x1062 in the tone mark section, in Karen these can be tones too.
2. Added the optional 0x103a, 0x1037, and 0x1038 after the tones. Asat is part of the Sgaw tone mark and dot below and visarga are used as nasal marks following the Pwo tones.
And here are some text files for testing:
[test_strings.txt](https://github.com/tesseract-ocr/tesseract/files/11398793/test_strings.txt) - A few Sgaw and Pwo test strings highlighting the errors this PR fixes.
[syllables_sgaw.txt](https://github.com/tesseract-ocr/tesseract/files/11398835/syllables_sgaw.txt) - All possible Sgaw syllables.
[syllables_pwo.txt](https://github.com/tesseract-ocr/tesseract/files/11398791/syllables_pwo.txt) - All possible Pwo syllables.
=> Support for Sgaw and W Pwo Karen languages in the Myanmar validator.

src/ccmain/paramsd.cpp, src/ccmain/pgedit.cpp, src/ccutil/errcode.cpp, src/ccutil/unicharset.cpp, src/opencl/openclwrapper.cpp, src/wordrec/findseam.cpp
Either use snprintf or std::stringstream.
=> Replace deprecated sprintf

src/training/lstmtraining.cpp, src/training/unicharset/lstmtester.cpp, src/training/unicharset/lstmtrainer.cpp, src/training/unicharset/lstmtrainer.h, unittest/lstm_test.h
- always use C ("classic") locale
- limit output of floating point values to 3 digits
- remove unneeded linefeed after log message "wrote checkpoint"
=> Improve format of logging from lstmtraining

CMakeLists.txt
This PR removes the -mfpu command line argument on aarch64, because it is not available in gcc on this architecture.
See: https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html
=> Disable -mfpu=neon for aarch64

configure.ac
FreeBSD uses git to manage Ports Tree. Tesseract, when building from the Ports Tree, is built from a tarball that doesn't have .git and then git describe is ran on top of the Ports Tree.
=> Fix build without git clone in cloned directory

src/opencl/openclwrapper.cpp
Inside initDSProfile use std::vector::resize instead of std::vector::reserve, due to later usage it by index that triggers debug cheks (reserver does not change size) under MSVC.
=> initDSProfile: correct std::vector usage

src/textord/colpartitiongrid.cpp
"auto" resulted in unsigned numbers, but htext_score and vtest_score can be negative.
Fixes: 842cca1d49617dd8 ("Fix more signed/unsigned compiler warnings")
=> Fix regression in layout detection since 5.0.0 (fixes issue #4014)

src/ccmain/tessedit.cpp
Model files which where defined with tessedit_load_sublangs in another model file where no longer loaded since Tesseract release 5.0.0-rc2.
Fixes: 9091055783ac8f03 ("Fix loading of additional model files")
=> Fix loading of sublangs (regression)

src/ccutil/tessdatamanager.cpp, src/training/combine_tessdata.cpp
Fixes #4149.
Rather than sending the listing to `stderr` send it to `stdout` like is done for the network listing.
Also document the hidden `-ld` and `-dl` switch combos in the help message.
=> Send output of combine_tessdata -d to stdout instead of stderr. Fixes #4149

autogen.sh
I did not have libtool installed, and found this
=> Move bail_out function before libtoolize check

src/api/baseapi.cpp
This allows OCR for URLs which require a session cookie.
=> Add new parameter curl_cookiefile for curl_easy_setopt

src/viewer/svutil.cpp
Fixes #3000.
Without any hints, we can end up with a UDP socket which won't work with the TCP socket that the Java ScrollView display server is listening on. Use hints for TCP v4 so that we get the right kind of socket returned.
Also, delete some obsolete comments nearby.
=> Force TCP v4 for socket to ScrollView server. Fixes #3000

include/tesseract/publictypes.h
To fix a tiny typo in a comment in `publictypes.h`.
=> Fix a tiny typo in `publictypes.h`

src/api/pdfrenderer.cpp
When giving tesseract PNG images with an indexed color map with the "pdf" output, these images come out grayscale. Removing a special case for PNG images in pdfrenderer fixes that.
I tested the patch with PNG images containing indexed color maps and containing rgb content.
=> Fix grey result of indexed PNG in pdfrenderer.

src/training/unicharset/normstrngs.cpp
IIUC, this is used when a language model / dict / dawg is in place to normalise the characters before applying hyphenation and quoting rules (which are not all covered by punctuation dawgs etc).
=> normstrngs: add more hyphens and quotes

src/arch/intsimdmatrix.cpp
In the process of developing tesseract for [SPEC CPUv8](https://www.spec.org/cpuv8/) with @zdenop 's help, we used the generic code path to future-proof the benchmark for architectures that do not yet exist. Hence we disable the intrinsics, and rather rely on the C++ code directly. Here, we found an opportunity to assist the compiler in the `IntSimdMatrix::MatrixDotVector` function. We split the loop so it first does all the work in chunks of four, and then clean up with whatever remainder is left over. If there is a guarantee that `w.dim1()` is always a multiple of four, then the remainder code is not required. So, this offers some perf improvement on the generic code path, depending on your compiler and system.
=> facilitate vectorization for generic build

src/ccstruct/imagedata.cpp
The list of the training or validation files may now contain .png files instead of .lstmf files, so it is no longer necessary to spend time and disc space for creating .box and .lstmf files for a training.
=> Support training without lstmf files

src/ccmain/paragraphs.cpp, src/ccstruct/stepblob.cpp, src/textord/alignedblob.cpp, src/textord/colfind.cpp, src/textord/makerow.cpp, src/textord/strokewidth.h, src/textord/tabfind.cpp, src/textord/tablefind.cpp, src/textord/tordmain.cpp
Hi there!
A few tiny refactors in some files.
=> A few refactors in some files

src/ccutil/ambigs.cpp
GitHub code scanning report:
Incorrect return-value check for a 'scanf'-like function
=> Fix some issues which were reported by GitHub code scanning

src/ccutil/ccutil.cpp
Conda installations patch TESSDATA_PREFIX in the binary. That does not work for std::string because the length won't be patched, so use a normal C string which can be patched.
Simplify also the code which checks the last character of datadir.
=> Improve CCUtil::main_setup (fixes issue #4230)

include/tesseract/baseapi.h, include/tesseract/capi.h, src/api/baseapi.cpp, src/api/capi.cpp, src/ccmain/pagesegmain.cpp, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h, src/textord/textord.cpp, src/textord/textord.h
Tesseract already calculates the average gradient (angle) of text lines within `Textord::TextordPage` at present.  The gradient of the text is useful information (as Tesseract performs poorly when the gradient is not [almost] zero), however the average gradient only exists within the [`Textord::TextordPage` function](https://github.com/tesseract-ocr/tesseract/blob/c9895dbad439e5ff42f45ef1d03fe5e8572f2e89/src/textord/textord.cpp#LL222C18-L222C18) at present, with no way for users to access it.  Using the API, getting the gradient currently requires running `Recognize` or `AnalyseLayout` and using the results to manually re-calculate the gradient. 
This PR allows for users to directly retrieve the existing average gradient value calculated in `Textord::TextordPage` using a function named …
=> Allow for text angle/gradient to be retrieved

src/ccstruct/blobs.h, src/ccstruct/polyaprx.cpp, src/wordrec/chop.cpp
std::asin only allows arguments in [-1, 1], but rounding errors can produce values which are slightly outside of this range and which would cause a FP exception (or wrong calculation results).
Rename also the internally used function TPOINT::length to TPOINT::length2 because it calculates the square of the length.
=> Fix FP exception in Wordrec::angle_change (issue #4242)

Makefile.am
It was not used for all sources before. Therefore some parts of the code (especially the code for training) used different compiler options. For example NDEBUG was not defined, and so the training code was built with debug assertions (resulting in potentially slower execution).
=> Use AM_CPPFLAGS also for compilation of all sources

src/lstm/recodebeam.cpp
=> Fixes #4247: remove unnecessary nullptr checks

src/training/unicharset/fileio.cpp, src/training/unicharset/lang_model_helpers.cpp
This fixes two issues reported by Codacy.
=> Avoid redundant conversion from std::string to char * to std::string

src/lstm/network.h
This function must be implemented by the derived classes.
=> Make function Network::spec pure virtual

CMakeLists.txt, tesseract.pc.cmake
Use CMake's logic to define `CMAKE_INSTALL_LIBDIR` rather than relying on a user override, and make use of the additional abstraction that the `GNUInstallDirs` module allows.
=> Make regular usage of CMAKE_INSTALL_LIBDIR and GNUInstallDirs

src/ccutil/ccutil.cpp
Don't check for a directory, because a symbolic link is also allowed.
=> Ignore illegal TESSDATA_PREFIX (not existing filesystem entry, issue #4277)

src/api/pagerenderer.cpp
Hi there,
i have a small fix to contribute regarding the PAGE-XML renderer.
Problem: Block- and line-level confidence in the PAGE XML renderer always returned 0.
Fix: Re-arrangement of variable initilization for block- and line-level confidence.
=> Fix confidence output for the PAGE XML renderer

src/api/hocrrenderer.cpp
Both `dir` and `lang` are also written if no font information was requested.
=> Set hOCR capabilities ocrp_dir and ocrp_lang unconditionally

src/ccmain/control.cpp
I noticed significant calls to `clock_gettime` so I investigated and found that we could eliminate them when they are not in use.  This was found from the continuing scrutiny of SPEC CPUv8 benchmark development. @zdenop 
Gate the sampling of the clock by the `tessedit_timing_debug` flag, which is the only time it gets used anyway. This eliminates unnecessary clock_gettime() system calls.
=> Reduce clock syscalls

src/textord/wordseg.cpp
See #4304 for full context.  
In short, `ROW` objects are expected to have valid/accurate bounding boxes, which are accessed using `row->bounding_box()`.  However, bounding box values are not calculated automatically--the method `row_obj->recalc_bounding_box()` must be run after the row is created and populated to calculate the bounding box.  This happens correctly in 5 of the 6 instances where `new ROW` is called, however does not occur in 1 case (within the `make_single_word` function that runs when `psm` is `SINGLE_WORD` or `SINGLE_CHAR`).  
This PR fixes this by adding the required call to `recalc_bounding_box` within `make_single_word`.  This brings that function in line with all the other functions that create `ROW` objects.  
This change fixes the bug described in #4304, where …
=> Calculate row bounding box in single-word mode per #4304

src/ccmain/pagesegmain.cpp, src/ccutil/ambigs.cpp, src/ccutil/unicharset.cpp, src/classify/adaptive.cpp, src/classify/clusttool.cpp, src/tesseract.cpp, src/textord/devanagari_processing.cpp, src/textord/tabfind.cpp, src/training/pango/pango_font_info.cpp, src/viewer/scrollview.cpp, src/wordrec/wordrec.cpp, unittest/mastertrainer_test.cc
- replace std::string::substr by std::string::resize
- initialize variables in initialization list
- fix several format strings
=> Fix performance and other issues reported by Codacy

src/ccutil/tprintf.cpp, src/ccutil/tprintf.h
- Remove unused macro and update comment
- Modernize and simplify the code
In a next step a `std::ofstream` which can be used instead of `tprintf` will be added.
=> Update code for tprintf

src/ccmain/control.cpp, src/ccutil/tesserrstream.h, src/ccutil/tprintf.cpp, src/ccutil/tprintf.h, src/training/common/errorcounter.cpp
The two debug message print execution times, previously in units of 0.01 seconds, now in milliseconds.
In function `ErrorCounter::ComputeErrorRate` the new code normally also avoids a call of `clock()` which is only needed for the debug message.
The new C++ stream `tesserr` can be used as an alternative to `tprintf` which is type safe and avoids lots of type casts.
=> Add C++ stream for log messages and use it in two debug messages

CMakeLists.txt
As this project follows Semantic Versioning, the shared object version should match these semantics.
The two options that make sense here are to have the soversion set to the version major (so only breaking changes are tracked) or to set to version major and minor (so breaking and API additions are tracked).
Since the Windows version of the library already uses version major and version minor, let's just do this universally.
Fixes: 832926f5afebd9a5a81343425e733708332f730f ("Update library version handling for cmake")
=> cmake: Correctly set the soversion based on SemVer properties

.github/workflows/autotools-macos.yml, .github/workflows/cmake.yml, .github/workflows/unittest-macos.yml
The macOS 12 runner image will be removed by December 3rd, 2024.
=> Replace deprecated runner macos-12 by macos-latest in GitHub actions

src/api/altorenderer.cpp, src/api/hocrrenderer.cpp, src/api/pagerenderer.cpp
Commit db52047420c54bd added the filename conversion for the hOCR renderer, but it was removed later for TSV in commit 6700edd8bcdd2a4.
Tesseract does not use a filename conversion anywhere else, so remove it for the other renderers, too.
=> Modernize code for renderers and remove filename conversion for Windows

src/tesseract.cpp
=> Support symbolic values for --oem and --psm options

Makefile.am, configure.ac, src/arch/intsimdmatrix.h, src/arch/intsimdmatrixrvv.cpp, src/arch/simddetect.cpp, src/arch/simddetect.h, src/tesseract.cpp
Convert riscv-v-spec-1.0.pdf into 111 PNG images,
then perform OCR on each one in sequence,
and measure the testing time on banana_f3:
old:        31m16.267s
new:        16m51.155s
=> Add RISC-V V support

src/ccutil/helpers.h
This reverts commit 2252936fc801aee6c65a0bae9daee0638f56febf.
Fixes: #4146, #4148, #4270
=> Fix linear congruential random number generator

src/tesseract.cpp
=> add cli `-c` parameter(s) to init vectors

src/ccmain/thresholder.cpp
handle colormaps correctly  - fixes #4127
=> handle colormaps correctly

src/dict/dawg.h
This should fix UnitTest build on main branch.
1.  I do not understand why problem occurred 2 week ago - there was irrelevant modification only in tprintf.{cpp,h}
2.  I do not understand why next `static const UNICHAR_ID kPatternUnicharID` definition is OK for unittest.
3. I do not understand why there is problem only in UnitTest and another Github Actions work fine...
=> use constexpr for kDawgMagicNumber

src/ccstruct/ratngs.cpp
punct_stripped() may currently produce invalid empty intervals (where end < start) for all-punctuation words. As a result, EqualIgnoringCaseAndTerminalPunct() crashes in this loop due to an unsigned integer underflow in w1end - w1start:
for (unsigned i = 0; i < w1end - w1start; i++) {
if (uchset->to_lower(word1.unichar_id(w1start + i)) !=
uchset->to_lower(word2.unichar_id(w2start + i))) {
return false;
}
}
Bug was introduced with the following commit:
-----------------------------------------------------------
Revision: 97048fe3e4813d6c2350a370b915563688123f2c
Author: Stefan Weil <sw@weilnetz.de>
Date: 09/10/2021 20:50:39
Message:
ccstruct: Fix some signed/unsigned compiler warnings
Remove also a local buffer in function REJMAP::print. …
=> Fix invalid empty interval in punct_stripped() for all-punctuation words

src/ccmain/thresholder.cpp
Don't use Sauvola binarization if the image has a width or height which is too small. Use LeptonicaOtsu as a fallback in this case.
This fixes the issue #4390.
=> Avoid error in pixSauvolaBinarizeTiled (issue #4390)

src/api/altorenderer.cpp
When running tesseract on a list of images and validating the alto output using the schema (https://www.loc.gov/alto/v3/alto-3-0.xsd), I had the following error:
```
Element '{http://www.loc.gov/standards/alto/ns-v3#}ComposedBlock', attribute 'ID': 'cblock_0' is not a valid value of the atomic type '{http://www.loc.gov/standards/alto/ns-v3#}BlockTypeID'.
```
Digging into the type of `BlockTypeID`, I found a `xsd:ID` restriction - meaning the `BlockTypeID` can only exist once in the whole document / is unique per document.
I incorporated the current `page_number` into the IDs thus resolving the issue.
=> Fix duplicated IDs in ALTO XML when multiple pages are present

include/tesseract/osdetect.h, src/ccmain/osdetect.cpp
Remove the private static char pointers from osdetect.h.
This does not break the API because the removed pointers are no member variables, and they could not be accessed because they were private.
As all script names were used only once, there is also no need to have additional pointer constants, and using the names directly simplifies the code.
=> Simplify code for osdetect

.github/workflows/cmake-win64.yml, .github/workflows/cmake.yml, CMakeLists.txt, cmake/BuildOptimizations.cmake, cmake/SourceLists.cmake, src/classify/adaptmatch.cpp, src/training/CMakeLists.txt, src/viewer/scrollview.cpp, src/viewer/svutil.cpp, src/viewer/svutil.h
* Don't use GLOB in CMake files - fixes #4442
* Optimization to improve build speed:
* Precompiled Headers (PCH) - Enabled by default via ENABLE_PRECOMPILED_HEADERS=ON 
* Unity Builds (Jumbo Builds) - Disabled by default via ENABLE_UNITY_BUILD=OFF. Can reduce compilation time by 30-60% but may increase memory usage 
* ccache Integration - Enabled by default via ENABLE_CCACHE=ON 
* Ninja Job Pools - Enabled by default via ENABLE_NINJA_POOL=ON
* fix several CMake macos issues
```
cmake --build build  -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_UNITY_BUILD=ON
cmake --build build --config Release --target install
```
=> Cmake optimization with warp2
