tesseract-ocr/tesseract

api/pdfrenderer.cpp
https://code.google.com/p/tesseract-ocr/issues/detail?id=1474
=>  Fix potential null pointer dereference in ccmain/paragraphs.cpp.

ccutil/hashfn.h
cherry picked from https://github.com/renard314/tess-two
=> fix to compile tesseract with clang

configure.ac
=> Fix configure.ac for OS X and -framework

api/baseapi.cpp, api/baseapi.h, api/renderer.cpp, api/renderer.h, api/tesseractmain.cpp
Works for single page and multi-page.
=> Added osd renderer for psm 0.

classify/clusttool.cpp
Coverity bug report: CID 1270420 "Free of address-of expression"
=> Fix free of buffer which was not allocated

INSTALL.GIT.md
=> Small improvements for documentation

ccutil/mainblk.cpp
=> Get tessdata prefix from executable path (only for Windows)

tessdata/configs/Makefile.am
=> Update Makefile.am - add txt config file

textord/colpartition.cpp, textord/colpartitiongrid.cpp, viewer/svutil.cpp
=> Fix compiler warnings (remove unused constants)

api/tesseractmain.cpp
This commit is better than 06fc0533c. Hopefully, this is the last fix to box training issue.
=> Fix #64. Make box training work

viewer/scrollview.cpp
=> Fix compiler warning (signed / unsigned mismatch)

api/tesseractmain.cpp
Error messages still are printed to stderr.
=> Print normal user messages to stdout instead to stderr

Dockerfile, docker-compose.yml
This builds a docker image based on the project .travis.yml
=> Dockerify using travis build script

ccmain/paragraphs.cpp, ccstruct/polyblk.cpp, ccutil/tessdatamanager.cpp, classify/adaptmatch.cpp, classify/mastertrainer.cpp, viewer/svutil.cpp
=> Fix some resource leaks reported by Coverity

cutil/cutil.h
=> cutil/cutil: Fix comment (copy+paste error)

opencl/openclwrapper.cpp
=> opencl: Fix some issues reported by gcc

opencl/opencl_device_selection.h, opencl/openclwrapper.cpp
=> opencl: Fix two small bugs (both found by gcc)

opencl/openclwrapper.cpp
=> opencl: Fix type of parameters for OpenCL functions

opencl/openclwrapper.cpp
=> Fix an unfixed merge conflict

AUTHORS
=> AUTHORS - Add community contributors

opencl/oclkernels.h
=> opencl: Format and fix OpenCL kernel code

lstm/lstmrecognizer.cpp, lstm/lstmtrainer.cpp, lstm/networkio.cpp, lstm/parallel.cpp
=> lstm: Remove several unused variables

api/baseapi.cpp, api/baseapi.h, ccmain/pageiterator.cpp, ccmain/pgedit.cpp, ccstruct/pdblock.h, ccutil/hashfn.h, classify/trainingsample.cpp, classify/trainingsampleset.cpp, cube/char_samp_set.cpp, cube/search_column.cpp, dict/dict.cpp, opencl/opencl_device_selection.h, opencl/openclwrapper.cpp, textord/fpchop.cpp, textord/makerow.cpp, training/commontraining.cpp, wordrec/chopper.cpp, wordrec/language_model.cpp
Neither delete nor free require a NULL check, so remove it.
=> Simplify delete / free usage

AUTHORS
=> AUTHORS: Add more contributors

cube/char_bigrams.cpp, cube/char_samp.cpp
Signed-off-by: Stefan Weil sw@weilnetz.de
=> cube: Fix issues reported by Coverity scan

lstm/lstm.cpp, lstm/lstmtrainer.cpp, lstm/lstmtrainer.h, lstm/recodebeam.cpp
=> lstm: Fix issues reported by Coverity scan

ccmain/thresholder.cpp, ccstruct/otsuthr.cpp, opencl/openclwrapper.cpp, opencl/openclwrapper.h
=> opencl: Remove unneeded and potentially bad type casts

opencl/openclwrapper.cpp
Fix also text for an existing check.
=> opencl: Add missing checks for OpenCL failures

ccstruct/rejctmap.cpp, neural_networks/runtime/input_file_buffer.cpp
=> Fix two typos in comments

training/ambiguous_words.cpp, training/boxchar.cpp, training/boxchar.h, training/classifier_tester.cpp, training/cntraining.cpp, training/commandlineflags.cpp, training/commontraining.cpp, training/commontraining.h, training/dawg2wordlist.cpp, training/degradeimage.cpp, training/degradeimage.h, training/fileio.cpp, training/ligature_table.cpp, training/lstmtraining.cpp, training/mftraining.cpp, training/normstrngs.cpp, training/pango_font_info.cpp, training/pango_font_info.h, training/shapeclustering.cpp, training/stringrenderer.cpp, training/text2image.cpp, training/unicharset_extractor.cpp, training/unicharset_training_utils.cpp, training/wordlist2dawg.cpp
=> training: Replace NULL by nullptr

ccmain/tesseractclass.cpp, ccmain/tesseractclass.h
Changed from 
unrej potential with no chekcs
to 
unrej potential with no checks
=> Fixed tiny typo

ccmain/equationdetect.cpp, textord/linefind.cpp
Those versions are no longer supported.
=> Remove code for old versions of Leptonica

configure.ac
=> configure.ac: Exit if compiler does not have c++11 support

training/language-specific.sh
=> err -> err_exit

lstm/lstmrecognizer.cpp, lstm/lstmtrainer.cpp, lstm/network.cpp, viewer/svutil.cpp
Include automatically generated configuration file if running autoconf
=> Fix GRAPHICS_DISABLED build, issue #679

README.md
=> Use camel case for GitHub in README.md

ccmain/tessedit.cpp, textord/scanedg.cpp
=> Fix some typos in comments (found by codespell)

README.md
=> README: Update stable version

autogen.sh
Saw this while messing around with #786 and just thought I'd go ahead and correct it really quickly.
=> Small Typo Fix

CMakeLists.txt, tesseract.pc.cmake
This can help to get same install result as after the autotools.
=> Cmake install

arch/dotproductavx.cpp
=> Fix typo in comment

ccutil/tessdatamanager.cpp, classify/intproto.cpp
This fixes some compiler warnings.
=> Remove unused local variables

opencl/openclwrapper.cpp
=> opencl: Add 'static' attributes for local functions and variables

classify/adaptmatch.cpp
=> 3.05: Fix typo in comment

appveyor.yml
=> Appveyor CI (experimental, don't pull)

.travis.yml
but allow failures
currently failing
=> test brew HEAD installs

ccmain/equationdetect.cpp, ccmain/equationdetect.h
=> EquationDetect: Remove unneeded new / delete operations

opencl/oclkernels.h, opencl/openclwrapper.cpp
=> opencl: Remove more unused code

README.md
=> README: Add Coverity badge

INSTALL.GIT.md
Add two build dependencies which were missing and update the hints for
building ScrollView.jar.
=> Update documentation for installation

training/stringrenderer.cpp, training/stringrenderer.h
=> StringRenderer::pen_color_: int[3]->double[3]

README.md
Add an Issue Template
Reorganize Readme.MD
=> Reorder README text 

.github/ISSUE_TEMPLATE.md
Eariler version as displayed when opening a new issue was not readable (too much markdown). 
Now made shorter/simpler.
=> Make less verbose

api/baseapi.cpp
=> Add new line to a few error messages.

api/baseapi.cpp
Tesseract supports hierarchies of languages and uses them since
the new files best/*.traineddata were added.
Now `tesseract --list-langs` also shows any traineddata files in
subdirectories of the tessdata directory.
=> List available languages recursively

ccmain/tesseractclass.cpp, dict/dict.cpp, wordrec/wordrec.cpp
=> Add missing spaces in help text

INSTALL.GIT.md
- minimum Leptonica version for 4.0x
- sudo ldconfig
=> Add missing information

Makefile.am
Replace the doc-dummy hack with .PHONY.
=> Clean Makefile.am

api/tesseractmain.cpp
The new text was suggested by Amit Dovev, see
https://github.com/tesseract-ocr/tesseract/pull/1325#issuecomment-366613553.
=> Improve help text for OCR engine mode

ccmain/tessedit.cpp
This simplifies the code and the user interface.
=> Don't try alternate path for tessdata

doc/combine_tessdata.1.asc
=> Fix typo in documentation

ccutil/ccutil.cpp, ccutil/ccutil.h, ccutil/mainblk.cpp
This further simplifies the finding of the tessdata directory.
=> Remove parameter m_data_sub_dir

ccstruct/ratngs.cpp, ccutil/platform.h, ccutil/tessdatamanager.cpp, ccutil/tessdatamanager.h, ccutil/unichar.cpp, ccutil/unicharcompress.cpp, ccutil/unicharset.cpp, lstm/lstmtrainer.cpp, lstm/lstmtrainer.h, training/boxchar.cpp, training/boxchar.h, training/fileio.cpp, training/fileio.h, training/lang_model_helpers.cpp, training/lang_model_helpers.h, training/ligature_table.cpp, training/ligature_table.h, training/normstrngs.cpp, training/normstrngs.h, training/pango_font_info.cpp, training/pango_font_info.h, training/stringrenderer.cpp, training/stringrenderer.h, training/text2image.cpp, training/unicharset_extractor.cpp, training/unicharset_training_utils.cpp, training/unicharset_training_utils.h, training/util.h
=> Remove old code for string class (no longer needed)

vs2010/tesseract/tesseract.rc
=> Update package version (Visual Studio)

configure.ac
=> configure: Update date, version and add project URL

Makefile.am
=> Simplify Makefile and add missing dependency for target training-install

api/pdfrenderer.cpp, ccutil/serialis.cpp, textord/baselinedetect.cpp, textord/colpartitionset.cpp, viewer/svutil.cpp
=> Fix issues reported by Coverity Scan

textord/tospace.cpp
=> Fix CID 1270406, CID 1270407 and CID 1270411 Arguments in wrong order

lstm/fullyconnected.cpp, lstm/lstm.cpp, lstm/lstm.h, lstm/lstmrecognizer.cpp, lstm/lstmrecognizer.h, lstm/lstmtrainer.cpp, lstm/lstmtrainer.h, lstm/network.cpp, lstm/network.h, lstm/networkbuilder.cpp, lstm/networkio.cpp, lstm/networkscratch.h, lstm/parallel.cpp, lstm/plumbing.cpp, lstm/plumbing.h, lstm/recodebeam.cpp, lstm/recodebeam.h, lstm/reversed.cpp, lstm/series.cpp, lstm/weightmatrix.cpp
=> lstm: Replace NULL by nullptr

configure.ac
=> configure: Remove GIT_REV which is no longer used

doc/tesseract.1.asc
=> doc: Fix asciidoc escapes for C++

CMakeLists.txt
Create also api/version.h like it is done for autoconf.
=> cmake: Get version information from VERSION file

classify/adaptive.cpp, classify/clusttool.cpp, classify/clusttool.h, classify/cutoffs.cpp, classify/intproto.cpp, classify/normmatch.cpp
=> classify: Fix warnings from Doxygen

NEWS
It was created more than 10 years ago, never changed and never used.
=> Remove NEWS stub file

CMakeLists.txt, vs2010/tesseract/tesseract.rc.in
=> cmake: Automatically build tesseract.rc with version from file

textord/workingpartset.h
=> WorkingPartSet: Remove unused constructor

ccutil/mainblk.cpp
=> Fixed Tessdata directory for Windows

training/validate_indic.cpp
Fixes https://github.com/tesseract-ocr/tesseract/issues/1135
=> Add kVedicMark to ConsumeVowelIfValid

training/validator.cpp
Fixes https://github.com/tesseract-ocr/tesseract/issues/1135
=> Add additional Unicodes to IsVedicAccent

training/ambiguous_words.cpp
=> training: Fix typo in help text

training/ambiguous_words.cpp, training/combine_tessdata.cpp, training/dawg2wordlist.cpp, training/merge_unicharsets.cpp, training/wordlist2dawg.cpp
=> training: Support new argument --version for remaining executables

training/pango_font_info.cpp
Pango versions older than 1.22.0 are not supported.
=> Remove obsolete code

training/ambiguous_words.cpp, training/combine_tessdata.cpp, training/commandlineflags.cpp, training/commontraining.cpp, training/dawg2wordlist.cpp, training/merge_unicharsets.cpp, training/wordlist2dawg.cpp
=> training: Support new command line option -v (short form for --version)

ccutil/mainblk.cpp
=> Fix tessdata prefix from executable path for Windows

training/tesstrain_utils.sh
Fixes https://github.com/tesseract-ocr/tesseract/issues/1149 and https://github.com/tesseract-ocr/tesseract/issues/1508
=> Change max_pages to zero

api/baseapi.cpp, ccmain/equationdetect.cpp, ccstruct/blobbox.cpp, ccstruct/normalis.cpp, ccstruct/pageres.cpp, ccutil/genericvector.h, ccutil/unicharmap.cpp, ccutil/unicharset.h, classify/adaptmatch.cpp, classify/trainingsampleset.cpp, textord/bbgrid.cpp, textord/bbgrid.h, textord/colfind.cpp, textord/devanagari_processing.h, textord/fpchop.cpp, textord/fpchop.h, textord/tabfind.cpp, textord/underlin.cpp, viewer/scrollview.cpp, wordrec/findseam.cpp
It is not needed because delete accepts a nullptr argument.
=> Remove nullptr checks before destructor

training/tesstrain_utils.sh
=> training: Remove some cube relicts

arch/Makefile.am, ccutil/Makefile.am, lstm/Makefile.am, training/Makefile.am, unittest/Makefile.am
'AM_INIT_AUTOMAKE()' in configure.ac sets options globally.
=> Remove 'AUTOMAKE_OPTIONS' from all Makefile.am files

src/lstm/static_shape.h
It was introduced by my latest commit 21d5ce57175e35e9df514e81f9c584f0bb2910ad.
=> Fix CID 1390821 (Uninitialized variable)

src/ccmain/equationdetect.cpp, src/ccmain/osdetect.cpp, src/ccmain/paramsd.cpp, src/cutil/callcpp.cpp, src/dict/dawg.cpp, src/textord/edgblob.cpp, src/textord/edgblob.h, src/textord/scanedg.cpp, src/textord/topitch.cpp, src/textord/tospace.cpp, src/viewer/svutil.cpp, src/wordrec/wordrec.cpp, src/wordrec/wordrec.h
Here I started work on refactoring old C-style memory management. In simple cases new/delete can be replaced by std::unique_ptr.
=> Use std::unique_ptr instead of manual memory management.

src/textord/tospace.cpp
Remove unused variable after refactoring.
=> Remove unused variable

src/api/tesseractmain.cpp
=> tesseractmain: Fail if bad command line option is given

src/api/capi.cpp, src/api/capi.h, src/ccmain/control.cpp, src/ccutil/ocrclass.h, unittest/Makefile.am, unittest/progress_test.cc
I need to use progress reporting while using C API. I have written bindings for the functionality.
=> Recognition progress in C API

src/training/mergenf.cpp, src/training/mergenf.h
=> src/training: Replace proprietary BOOL8 by standard bool data type

src/training/icuerrorcode.h
=> training: Add missing linefeed to error message

src/ccutil/scanutils.h
=> scanutils: Fix typos in comments

src/arch/Makefile.am
=> Remove some header files from public API

src/ccmain/reject.cpp, src/ccutil/params.cpp, src/classify/clusttool.cpp, src/classify/cutoffs.cpp, src/classify/normmatch.cpp, src/classify/protos.cpp, src/dict/stopper.cpp
=> Remove unneeded include statements for scanutils.h

src/arch/dotproductsse.h
The changes are based on an analysis done with include-what-you-use.
=> dotproductsse: Fix include statements

src/opencl/oclkernels.h, src/opencl/opencl_device_selection.h, src/opencl/openclwrapper.cpp, src/opencl/openclwrapper.h
=> Format OpenCL code

.clang-format
Add indentation of preprocessor directives.
=> Update rules for clang-format

src/cutil/cutil.cpp, src/cutil/cutil.h
Remove also some old comments.
=> Remove unused function long_rand

src/api/baseapi.cpp, src/classify/cluster.cpp, src/classify/clusttool.cpp, src/classify/fpoint.cpp, src/classify/intfeaturespace.cpp, src/classify/intfx.cpp, src/classify/intproto.cpp, src/classify/mfx.cpp, src/classify/protos.cpp, src/classify/trainingsample.cpp, src/cutil/const.h, src/training/commontraining.cpp, src/training/mergenf.cpp, src/wordrec/chop.cpp
One definition for pi is sufficient.
=> Replace macro PI by macro M_PI

src/classify/adaptive.cpp, src/classify/adaptmatch.cpp, src/classify/cluster.cpp, src/classify/clusttool.cpp, src/classify/cutoffs.cpp, src/classify/float2int.cpp, src/classify/fpoint.cpp, src/classify/intmatcher.cpp, src/classify/intproto.cpp, src/classify/kdtree.cpp, src/classify/mf.cpp, src/classify/mfdefs.cpp, src/classify/mfoutline.cpp, src/classify/mfx.cpp, src/classify/normmatch.cpp, src/classify/ocrfeatures.cpp, src/classify/outfeat.cpp, src/classify/picofeat.cpp, src/cutil/bitvec.cpp, src/training/cntraining.cpp, src/training/commontraining.cpp, src/training/mergenf.cpp, src/training/mftraining.cpp
Exceptions are no longer used.
Remove also some history comments and fix several comments.
=> Remove old comments for exceptions

src/lstm/network.cpp
=> Fix syntax errors introduced by last commit (regression)

src/ccmain/reject.cpp
=> Remove unused iterator

src/api/tesseractmain.cpp
Commit 629ded223ced0aab4175aabbd5d66b3e47871f58 had broken that
functionality.
=> Fix --print-parameters (regression)

src/training/tesstrain_utils.sh
By default, that script creates two new temporary directories with random
names in /tmp.
The new command line flag --workspace_dir PATH uses the given path as
a base directory for all temporary files.
That allows better reproducable training results (no random directory
names in log files).
Signed-off-by: Stefan Weil <stweil@ub-backup.bib.uni-mannheim.de>
=> training: Add new flag --workspace_dir to tesstraining_utils.sh

src/api/pdfrenderer.cpp, src/api/renderer.h
=> TessPDFRenderer: Improve robustness of API (issue #1804)

src/ccstruct/ratngs.cpp, src/ccstruct/ratngs.h, src/wordrec/language_model.cpp
CID: 1164533 (Logically dead code)
=> Fix issue detected by Coverity Scan

src/classify/mfoutline.cpp
CID: 1164604 (Nesting level does not match indentation)
=> Fix issues detected by Coverity Scan

src/textord/colfind.cpp, src/textord/colpartition.cpp, src/textord/colpartition.h, src/textord/colpartitiongrid.cpp, src/textord/strokewidth.cpp, src/textord/tablefind.cpp
This implements a TODO. Rename also some related items.
=> ColPartition: Rename median_size_ -> median_height_

src/training/CMakeLists.txt, src/training/Makefile.am, src/training/language-specific.sh, src/training/validate_javanese.cpp, src/training/validate_javanese.h, src/training/validator.cpp, src/training/validator.h
Add validator for Javanese script (based on Khmer). Validation rules may need an update after review by language experts.
=> Add support for Javanese script - aksara Jawa

src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h
=> Added detailed value description for glyph_confidences parameter

unittest/Makefile.am, unittest/commandlineflags_test.cc, unittest/validator_test.cc
Both tests only work if training is enabled.
=> Fix and enable two more unit tests

.gitignore, unittest/Makefile.am
=> Add $(LEPTONICA_LIBS) to applybox_test_LDADD

doc/tesseract.1.asc
=> Add documentation for lists of images to the tesseract man page

README.md, doc/tesseract.1.asc
Using text suggested by @stweil in https://github.com/tesseract-ocr/tesseract/issues/1276#issuecomment-426411768
=> Update man page and readme reg two OCR engines in Tesseract 4

doc/tesseract.1.asc
Add also links to the user forum and to the Wiki and update the
history text.
=> Merge and enhance documentation on language and script models

src/ccutil/genericvector.h, src/classify/intproto.cpp
See https://lgtm.com/projects/g/tesseract-ocr/tesseract/alerts.
=> Fix some warnings from static code analyzer LGTM

src/ccutil/platform.h, src/lstm/weightmatrix.cpp, src/viewer/svutil.h, src/wordrec/language_model.cpp
=> Remove code for _MSC_VER < 1900

src/lstm/lstmtrainer.h
=> Remove virtual specifiers

src/textord/colpartition.h
=> Fix integer overflow in overlap calculation

src/ccmain/paragraphs_internal.h, unittest/Makefile.am, unittest/imagedata_test.cc, unittest/include_gunit.h, unittest/lang_model_test.cc, unittest/mastertrainer_test.cc, unittest/paragraphs_test.cc
Two of them currently fail because of missing test data.
=> Add more unit tests

unittest/lstm_test.h, unittest/normstrngs_test.h
They were provided by Jeff Breidenbach <jbreiden@google.com>.
=> unittest: Add more files from Google

.lgtm.yml
=> Fix configuration for LGTM

src/lstm/recodebeam.cpp
=> Fixed a mac compiler warning in recodebeam.cpp

tessdata/configs/lstmdebug
It was provided by Jeff Breidenbach <jbreiden@google.com>.
=> Add debug configuration for LSTM

README.md
Added an example in the README for newbies like me to have a place to get started.
Also added a link to the wiki where there are more helpful examples.
=> Add example in README.md

tessdata/configs/Makefile.am
=> Add configuration file for ALTO to installation

src/api/altorenderer.cpp
=> Format new ALTO code with clang-format

src/api/tesseractmain.cpp, src/arch/simddetect.cpp, src/arch/simddetect.h
=> SIMDDetect: Use tesseract namespace and format code

configure.ac, src/arch/Makefile.am
=> Add check whether compiler supports -march=native flag

src/training/text2image.cpp, unittest/bitvector_test.cc, unittest/commandlineflags_test.cc, unittest/indexmapbidi_test.cc, unittest/normstrngs_test.cc, unittest/pango_font_info_test.cc, unittest/tatweel_test.cc
=> Fix several typos (most of them found by codespell)

src/api/hocrrenderer.cpp
Using std::stringstream simplifies the code and allows conversion of
double to string independant of the current locale setting.
=> Use std::stringstream to generate hOCR output

src/lstm/tfnetwork.cpp, src/lstm/tfnetwork.h
=> Add missing std namespace in tensorflow code

src/classify/cluster.cpp, src/cutil/oldlist.cpp, src/cutil/oldlist.h
=> Remove unused code

unittest/applybox_test.cc
Many tests have preconditions like a correct version of the test submodule
or installed traineddata files at the right location. They fail or even
crash if those preconditions are not met.
The latest version of Googletest supports skipping single tests with
GTEST_SKIP which is used here to skip tests in applybox_test when
tessdata/eng.traineddata is missing.
=> unittest: Skip test is traineddata is missing in applybox_test

src/training/tesstrain.sh, src/training/tesstrain_utils.sh
(cherry picked from commit 94b8988b8cca3812137933db00750bd6e2e84e32)
=> use --xsize instead of --x_size

doc/tesseract.1.asc
A typo and missing full stops.
=> Tidy tesseract(1)

unittest/resultiterator_test.cc
Fixes failing test for text level 3 and 4.
=> fix resultiterator_test for extra \n

cmake/Configure.cmake, configure.ac, cppan.yml, src/lstm/functions.cpp, src/lstm/functions.h
With C++14 the lookup tables can be computed by the compiler.
=> Use C++14 if supported and optionally improve lookup tables

src/ccmain/thresholder.h, src/ccstruct/ocrblock.cpp, src/ccstruct/ocrblock.h, src/ccstruct/pdblock.h, src/ccstruct/points.h, src/ccstruct/werd.cpp, src/ccstruct/werd.h, src/ccutil/unicodes.h, src/classify/clusttool.cpp, src/classify/kdtree.cpp, src/textord/blkocc.cpp, src/textord/tabfind.h, src/wordrec/lm_state.h
=> Fix doxygen comments

src/training/degradeimage.cpp, src/training/text2image.cpp
=> Fix PrepareDistortedPix based on feedback

src/lstm/convolve.h, src/lstm/input.h, src/lstm/network.cpp, src/lstm/network.h, src/lstm/reconfig.h
That class is an abstract class with several pure virtual functions.
=> Refactor class Network

doc/combine_lang_model.1.asc
the option -l for specifying the language is actually --lang.
=> Change option -l to --lang

src/api/capi.cpp, src/api/capi.h
Both capi.h and capi.cpp changes are now included in PR.
=> Add lstmbox and wordstrbox to C-API

src/api/baseapi.h, src/api/capi.cpp, src/api/capi.h, src/api/lstmboxrenderer.cpp, src/api/renderer.h, src/api/tesseractmain.cpp
Change function name for look and consistency in letter case.
=> Add missing renderers to C-API

src/api/wordstrboxrenderer.cpp
=> Format new code with clang-format

src/classify/intmatcher.cpp, src/dict/context.cpp, src/dict/dict.cpp, src/dict/dict.h, src/dict/stopper.cpp
Credit to OSS-Fuzz:
This fixes an issue which was reported by OSS-Fuzz, see details at
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13592.
OSS-Fuzz triggered this assertion:
contains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 502
=> Fix two issues reported by OSS-Fuzz

src/api/hocrrenderer.cpp, src/ccmain/ltrresultiterator.cpp, src/ccmain/ltrresultiterator.h, src/ccmain/resultiterator.cpp, src/ccmain/resultiterator.h, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h, src/ccstruct/pageres.h, src/lstm/recodebeam.cpp, src/lstm/recodebeam.h
Reworked lstm_choice_mode to make api independent from the choice mode value.
Added a new function to get timesteps segmented by the suggested symbol separator.
Reworked the choice Iterator to show correct choices for lstm-based traineddata now
=> Lstm choice ril

src/training/language-specific.sh, src/training/language_specific.py, src/training/tesstrain_utils.py
@stweil Please review.
Appyeyor is failing for unrelated reasons.
=> training script changes

src/training/tesstrain_utils.sh
=> tesstrain: check failure of subjobs

src/classify/classify.cpp, src/classify/classify.h, tessdata/configs/box.train, tessdata/configs/box.train.stderr, tessdata/configs/lstm.train
Replace also TRUE, FALSE by true, false.
=> Remove unused config variable tessedit_single_match

src/api/hocrrenderer.cpp, src/ccutil/tessdatamanager.cpp, src/classify/cluster.cpp, src/lstm/lstm.cpp, src/lstm/lstmtrainer.cpp, src/lstm/recodebeam.cpp, src/lstm/recodebeam.h, src/lstm/stridemap.cpp, src/textord/cjkpitch.cpp, src/textord/colpartition.cpp, src/textord/imagefind.h, src/textord/strokewidth.cpp, src/viewer/scrollview.cpp, src/wordrec/language_model.cpp, src/wordrec/lm_pain_points.cpp, src/wordrec/lm_pain_points.h, src/wordrec/params_model.h
=> Modernize code (clang-tidy check modernize-loop-convert)

src/api/baseapi.cpp, src/api/pdfrenderer.cpp
This makes more code independent of the locale settings.
=> Replace more snprintf by std::stringrenderer

src/api/hocrrenderer.cpp, src/ccmain/linerec.cpp, src/ccmain/ltrresultiterator.cpp, src/ccmain/ltrresultiterator.h, src/ccmain/resultiterator.cpp, src/ccmain/resultiterator.h, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h, src/ccstruct/pageres.h, src/lstm/lstmrecognizer.cpp, src/lstm/lstmrecognizer.h, src/lstm/recodebeam.cpp, src/lstm/recodebeam.h
=> Removed lstm_choice_mode for backwards compatibility with 4.0

src/api/hocrrenderer.cpp, src/ccmain/linerec.cpp, src/ccmain/ltrresultiterator.h, src/ccmain/resultiterator.cpp, src/ccmain/resultiterator.h, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h, src/ccstruct/pageres.h, src/lstm/lstmrecognizer.cpp, src/lstm/lstmrecognizer.h, src/lstm/recodebeam.cpp, src/lstm/recodebeam.h
Added some parts of the lstm_choice_mode functionality to restore compatibility with the 4.0 Version
=> Readded parts of the lstm_choice_mode functionality

src/api/pdfrenderer.cpp, src/ccmain/equationdetect.cpp, src/ccmain/equationdetect.h, src/textord/cjkpitch.cpp, src/textord/colpartitionset.cpp, src/textord/colpartitionset.h, src/textord/tordmain.cpp, unittest/intfeaturemap_test.cc, unittest/paragraphs_test.cc
=> Fix some typos (most found and fixed by codespell)

src/ccutil/unicharmap.cpp, src/classify/trainingsampleset.cpp, src/training/tesstrain_utils.py
Fixes some LGTM alerts (maybe fixes potential bugs due to them?)
=> Some LGTM alert fixes and potential bugfixes

doc/unicharset_extractor.1.asc
using the help info output by the program
=> Update documentation for unicharset_extractor

src/arch/simddetect.cpp
=> Add dot product implementation using std::inner_product

CMakeLists.txt
This commit is the cmake mirror of commit ca885da5d361e5b59d7f9ae254f7d410b8c6a85a
=> Detect and enable C++17 support for CMake builds

unittest/Makefile.am, unittest/ligature_table_test.cc
=> unittest: Fix and enable ligature_table_test

unittest/Makefile.am, unittest/scanutils_test.cc
=> unittest: Fix and enable scanutils_test

src/training/tesstrain.py
=> fix logger file encoding error.

src/training/tesstrain.py
=> close log file handle before move it.

src/viewer/svutil.cpp
=> fix start ScrollView.jar failed when lstmtraining

src/api/tesseractmain.cpp
=> fix windows stdout messy code

src/training/tesstrain_utils.py
=> fix tesstrain.py error

src/api/capi.h
=> capi: Add missing PSM_RAW_LINE to TessPageSegMode

sw.cpp
=> sw.cpp: Sync list of public headers with Autotools build

src/ccutil/params.cpp
=> Remove unimplemented +/- for parameter files

src/api/capi.cpp, src/api/capi.h
See https://github.com/tesseract-ocr/tesseract/issues/2725
=> Remove TESS_CALL.

src/ccmain/linerec.cpp, src/ccstruct/imagedata.h
Commit 94d0f77f56bb9123c4c33c97125e76e7bdb73159 tried to fix issue #2741
but created a new problem.
This commit should fix both old and new issue.
=> Fix issue #2748

doc/lstmeval.1.asc, src/training/lstmtrainer.cpp
See discussion at https://github.com/tesseract-ocr/tesstrain/issues/122#issuecomment-552067667
=> Add separator and training_iteration to checkpoint name

src/api/altorenderer.cpp
Adds ComposedBlock level to Alto rendering making it more in line with the hOCR render.
=> Added ComposedBlock level to Alto output

Makefile.am, configure.ac
=> automake: Improve build rules

README.md
=> Add badge for Google OSS-Fuzz

CONTRIBUTING.md, ChangeLog, INSTALL.GIT.md, README.md, doc/cntraining.1.asc, doc/combine_lang_model.1.asc, doc/combine_tessdata.1.asc, doc/dawg2wordlist.1.asc, doc/lstmeval.1.asc, doc/lstmtraining.1.asc, doc/merge_unicharsets.1.asc, doc/mftraining.1.asc, doc/set_unicharset_properties.1.asc, doc/shapeclustering.1.asc, doc/tesseract.1.asc, doc/text2image.1.asc, doc/unicharambigs.5.asc, doc/unicharset.5.asc, doc/unicharset_extractor.1.asc, doc/wordlist2dawg.1.asc, src/training/lstmtraining.cpp, src/training/tesstrain.py, src/training/tesstrain.sh, src/training/tesstrain_utils.py, src/training/tesstrain_utils.sh
=> Replace references to the old wiki by new URLs

src/api/baseapi.cpp
=> Report errors from curl_easy functions

configure.ac
=> Check compiler options depending on host cpu

src/arch/intsimdmatrixneon.cpp
My understanding of the intsimdmatrix mechanism was that the
inputs would be resized so that we'd only ever get "whole
blocks" of data (i.e. that num_out would be a multiple of
kNumOutputsPerRegister, and num_in would be a multiple of
kNumInputsPerRegister). Sadly, this does not seem to be the
case, as we can get called (sometimes) with num_out % 8 == 7.
It's not clear to me WHY this happens. Is it a mistake in
the calling code? A quick investigation reveals that the
offending matrices are being read from the file and are not
obviously resized before being used.
Possibly we could benefit from resizing those matrices so
that special cases in this innermost loop are not actually
required, but unless and until that is done, let's fix the
inner loop.
=> Fix intsimdmatrixneon.cpp stack corruption.

src/ccstruct/imagedata.cpp, src/ccstruct/imagedata.h
=> Fix crash caused by missing thread synchronization (issues #757, #1168 and #2191)

CMakeLists.txt, src/training/CMakeLists.txt
With this applied I am able to build tesseract using
`cmake -DGRAPHICS_DISABLED=ON -DDISABLED_LEGACY_ENGINE=ON`
=> Fix CMake build with DISABLED_LEGACY_ENGINE

src/classify/intmatcher.cpp
=> Avoid buffer overflow (issue #444)

Makefile.am, configure.ac, src/arch/simddetect.cpp
Signed-off-by: Stefan Weil <stefan.weil@bib.uni-mannheim.de>
=> Always use NEON by default for ARMv8

src/ccmain/control.cpp, src/ccstruct/points.h, src/ccstruct/ratngs.cpp, src/textord/cjkpitch.cpp, src/textord/oldbasel.cpp, src/textord/topitch.cpp
In particular, "defined but not used" (caused by GRAPHICS_DISABLED),
double constants being truncated to floats, and implicit casts.
=> Squash some warnings in MSVC build.

cmake/templates/TesseractConfig.cmake.in
Fix path issue mentioned in #3112 by @yuriisk.
=> Fix CMake targets path

src/ccstruct/blamer.h, src/classify/protos.h, src/viewer/svmnode.h
This reduces the size of those objects.
=> Pack BlamerBundle, CLASS_STRUCT and SVMenuNode

configure.ac, doc/Makefile.am
=> Add XML_CATALOG_FILES for MacOS with Homebrew

unittest/Makefile.am, unittest/lstmtrainer_test.cc
See related discussion at https://github.com/tesseract-ocr/tesseract/pull/3218#issuecomment-756782983
=> Delete TESSDATA_BEST_DIR macro

.github/workflows/dailyunittest.yml
Suggested by @egorpugin in https://github.com/tesseract-ocr/tesseract/issues/3220#issuecomment-758246368
Thanks @stweil, Github Actions work after using ssh as suggested by you in https://github.com/tesseract-ocr/tesseract/issues/3220#issuecomment-758778709
=> Add Github Action for autotools based daily unittests on ubuntu

.github/workflows/dailyunittest.yml
Remove options: [disable-legacy, fsanitize]
Use both sets of config options together with correct syntax
=> Fix config options for dailyunittest GitHub Action

doc/lstmtraining.1.asc, src/training/lstmtraining.cpp
=> lstmtraining: Interpret negative value for --max_iterations as epochs

src/training/classifier_tester.cpp, src/training/common/commontraining.cpp, src/training/common/commontraining.h, src/training/mftraining.cpp, src/training/shapeclustering.cpp, unittest/mastertrainer_test.cc
The issue was introduced in commit 6e9456415.
Partially reverting this commit fixes it.
=> Fix memory leak in mastertrainer_test (fixes issue #3215)

.github/workflows/dailycmake.yml, .github/workflows/dailyunittest.yml
* Add -fsanitize=address,undefined for unittest
*  Remove Debug builds
*  Add Compiler and Version to config
=> Daily Actions Workflow update

.github/workflows/vcpkg.yml
- no training tools
- also builds and runs basicapitest using cmake
=> Actions CI: Add workflow to build tesseract using vcpkg and cmake

src/api/tesseractmain.cpp
=> Replace calls of exit function

src/lstm/fullyconnected.h
=> Fix network specification for NT_SYMCLIP

src/classify/intproto.cpp
=> Replace std::array by std::vector to avoid stack overflow

src/api/baseapi.cpp, src/api/capi.cpp, src/ccmain/applybox.cpp, src/ccmain/control.cpp, src/ccmain/linerec.cpp, src/ccmain/pagesegmain.cpp, src/ccmain/paragraphs.cpp, src/ccmain/paramsd.cpp, src/ccmain/tesseractclass.h, src/ccstruct/fontinfo.h, src/ccstruct/ratngs.h, src/ccutil/helpers.h, src/ccutil/object_cache.h, src/ccutil/sorthelper.h, src/ccutil/unicharset.cpp, src/ccutil/unicharset.h, src/classify/adaptmatch.cpp, src/dict/trie.h, src/lstm/lstmrecognizer.h, src/lstm/networkscratch.h, src/lstm/parallel.h, src/lstm/recodebeam.cpp, src/lstm/reversed.h, src/lstm/series.h, src/training/common/commandlineflags.cpp, src/training/common/ctc.cpp, src/training/degradeimage.cpp, src/training/unicharset/lstmtrainer.cpp, unittest/unicharset_test.cc
=> Fix compiler warnings (mostly -Wsign-compare)

src/ccstruct/imagedata.cpp
=> Avoid lots of messages for training with single line images

CMakeLists.txt, Makefile.am, include/tesseract/baseapi.h, src/api/baseapi.cpp, src/ccmain/thresholder.cpp, src/ccmain/thresholder.h, src/ccstruct/otsuthr.cpp, src/ccstruct/otsuthr.h, src/opencl/openclwrapper.cpp
Remove thresholder.h from the public API.
=> Modernize code for OTSU and reduce public API further

src/ccmain/control.cpp, src/ccmain/docqual.cpp, src/ccmain/output.cpp, src/ccmain/paragraphs.cpp, src/ccmain/resultiterator.cpp, src/ccmain/tfacepp.cpp, src/ccstruct/imagedata.cpp, src/ccstruct/pageres.cpp, src/ccstruct/ratngs.cpp, src/ccstruct/ratngs.h, src/ccutil/bitvector.h, src/ccutil/mainblk.cpp, src/ccutil/unicharcompress.cpp, src/ccutil/unicharcompress.h, src/classify/adaptmatch.cpp, src/dict/dawg.cpp, src/dict/dict.cpp, src/dict/permdawg.cpp, src/dict/stopper.cpp, src/dict/trie.cpp, src/textord/cjkpitch.cpp, src/textord/colpartition.cpp, src/textord/makerow.cpp, src/textord/tablerecog.cpp, src/training/common/errorcounter.cpp, src/training/common/trainingsampleset.cpp, src/training/unicharset/lang_model_helpers.cpp, src/training/unicharset_extractor.cpp
Replace the patterns (x.size() == 0) and (x.length() == 0) by x.empty().
=> Simplify checks for emptiness

Makefile.am, src/classify/classify.cpp, src/classify/classify.h, src/classify/intproto.cpp, src/classify/shapeclassifier.cpp, src/textord/colfind.cpp, src/textord/colfind.h, src/textord/strokewidth.cpp, src/textord/strokewidth.h, src/training/common/mastertrainer.cpp, src/training/unicharset/lstmtrainer.cpp, src/training/unicharset/lstmtrainer.h, src/viewer/svmnode.cpp
=> Disable more code with GRAPHICS_DISABLED

.github/workflows/cmake-win64.yml
=> Actions CI: Build Tesseract on Windows using cmake

src/ccstruct/blobbox.cpp, src/ccstruct/blobbox.h, src/ccstruct/werd.cpp, src/textord/ccnontextdetect.cpp, src/textord/colpartition.cpp, src/textord/fpchop.cpp, src/textord/tordmain.cpp, src/textord/tospace.cpp, src/textord/underlin.cpp, src/textord/wordseg.cpp
=> Fix memory leak (OSS-Fuzz issue #32246)

src/ccutil/object_cache.h
Refactored #3431 according to @stweil 's code review.
=> Refactor ObjectCache::DeleteUnusedObjects with reverse iterator

src/ccmain/control.cpp, src/ccmain/linerec.cpp, src/ccmain/paragraphs.cpp, src/ccstruct/blobs.cpp, src/ccstruct/fontinfo.h, src/ccstruct/normalis.cpp, src/ccstruct/pageres.cpp, src/ccstruct/pageres.h, src/ccstruct/ratngs.cpp, src/ccstruct/stepblob.cpp, src/ccutil/unicharcompress.cpp, src/classify/intmatcher.cpp, src/classify/shapeclassifier.cpp, src/classify/shapetable.cpp, src/lstm/recodebeam.cpp, src/training/common/ctc.cpp, src/training/common/errorcounter.cpp, src/training/common/mastertrainer.cpp, src/training/unicharset/lstmtrainer.cpp, src/wordrec/params_model.cpp, src/wordrec/segsearch.cpp
Fixes: 9710bc0465fc0df1a5bc0e71177151e8c5901204
=> Fix vector resize with init for all elements (issue #3473)

CMakeLists.txt
=> Use CMAKE_SYSTEM_PROCESSOR to check for SIMD support options

unittest/baseapi_test.cc
=> Add unittest for static TessBaseAPI object

configure.ac, src/ccutil/tesstypes.h
=> Add new configure option --enable-float32 for faster LSTM with float

src/ccstruct/image.cpp
=> Fix cloning of Image with pix_ == nullptr (issue #537)

src/ccmain/tessedit.cpp
Fix also a regression in the for loop which handles submodels.
Fixes: 0d91c700c062 ("Modernize code in Tesseract::init_tesseract")
=> Use model prefix also for submodels

src/training/classifier_tester.cpp, src/training/cntraining.cpp, src/training/common/commontraining.cpp, src/training/common/commontraining.h, src/training/mftraining.cpp, src/training/shapeclustering.cpp, unittest/mastertrainer_test.cc
=> Simplify function LoadTrainingData and fix mastertrainer_test

src/ccmain/thresholder.cpp
Thanks to Robert Sachunsky @bertsky who pointed out the issue.
=> Fix wrong tiles parameters in Sauvola

.github/workflows/cmake.yml
Fixes Issue https://github.com/tesseract-ocr/tesseract/issues/3573
=> Actions CI: cmake - fix macos for -lcurl, add macos-11 to matrix

CMakeLists.txt, Makefile.am, configure.ac, src/tesseract.cpp, sw.cpp
=> Move src/api/tesseractmain.cpp to src/tesseract.cpp

.gitmodules, CMakeLists.txt, Makefile.am, sw.cpp, unittest/README.md
=> Move googletest to unittest/third_party/googletest

include/tesseract/baseapi.h, src/api/baseapi.cpp, src/ccmain/tesseractclass.cpp, src/ccmain/tesseractclass.h
Disable more code related to equation detection and osd.
=> Improve the disable legacy build

src/api/renderer.cpp
This change was requested in issue #3628.
=> Don't add a page separator for a single page image

unittest/resultiterator_test.cc
resultiterator_test: Disable SmallCapDropCapTest
=> Improve disable legacy build

include/tesseract/ltrresultiterator.h, include/tesseract/pageiterator.h, src/ccmain/ltrresultiterator.cpp, src/ccmain/pageiterator.cpp
Note that this is an API change for 5.0.0, but fixes compatibility with the 4.1 branch. See pull request #2971.
=> Add RowAttributes getter to PageIterator and format code

src/training/unicharset/lstmtrainer.cpp
=> Limit BCER to interval [0,1]

src/ccutil/helpers.h, src/ccutil/serialis.h, src/ccutil/unicharset.cpp
=> Allow compilation with clang-7

src/api/baseapi.cpp
=> Support up to 8 redirections when running OCR on a URL

include/tesseract/baseapi.h, include/tesseract/capi.h, include/tesseract/export.h, include/tesseract/ltrresultiterator.h, include/tesseract/ocrclass.h, include/tesseract/osdetect.h, include/tesseract/pageiterator.h, include/tesseract/publictypes.h, include/tesseract/renderer.h, include/tesseract/resultiterator.h, include/tesseract/unichar.h, include/tesseract/version.h.in
=> Clean header comments in public include files

src/ccstruct/statistc.h, unittest/stats_test.cc
=> Catch nullptr in STATS::pile_count (fix isse #3694)

ChangeLog, README.md
=> [skip_ci] Update documentation for release 5.0.1

src/api/baseapi.cpp
=> Add new parameter curl_timeout for curl_easy_setop

src/ccmain/pageiterator.cpp
=> Catch nullptr in PageIterator::Orientation to improve robustness

README.md
Thank you for this excellent project.
=> Added link to tessdata repository

CMakeLists.txt, Makefile.am, configure.ac, src/arch/dotproduct.h, src/arch/dotproductavx512.cpp, src/arch/simddetect.cpp
=> Add initial support for Intel AVX512F

sw.cpp
=> Fix sw build for AVX512

include/tesseract/ltrresultiterator.h, src/ccmain/pageiterator.cpp, src/ccmain/resultiterator.cpp, src/ccstruct/blobbox.h, src/ccstruct/coutln.cpp, src/ccstruct/normalis.cpp, src/ccstruct/pdblock.cpp, src/ccutil/ambigs.h, src/ccutil/tessdatamanager.cpp, src/ccutil/tessdatamanager.h, src/classify/intproto.h, src/dict/trie.h, src/textord/colfind.h, src/textord/colpartition.cpp, src/textord/colpartition.h, src/textord/devanagari_processing.cpp, src/textord/tospace.cpp, src/training/unicharset/lstmtrainer.h, src/wordrec/language_model.h
=> Fix some typos.

include/tesseract/capi.h, src/api/capi.cpp
=> Add C API to Init with trained data from memory

.github/workflows/autotools-macos.yml, .github/workflows/autotools-openmp.yml, .github/workflows/autotools.yml, .github/workflows/cmake.yml, .github/workflows/codeql-analysis.yml, .github/workflows/msys2.yml, .github/workflows/sw.yml, .github/workflows/unittest-disablelegacy.yml, .github/workflows/unittest-macos.yml, .github/workflows/unittest.yml, .github/workflows/vcpkg-4.1.1.yml, .github/workflows/vcpkg.yml
This PR just updates the [actions/checkout](https://github.com/actions/checkout) to version 3. 
No changes in behavior expected.
=> Update checkout action to version 3

src/classify/ocrfeatures.cpp
Fixes: 3b0759940c16b68e ("Replace more STRING by std::string")
=> Fix function tesseract::WriteFeature (issue #3925)

src/ccstruct/stepblob.h
=> Fix typo in stepblob.h

appveyor.yml
=> Update appveyor.yml - Url has changed
